### ISSUE TITLE
Crash Report 1.21.1 NeoForge with Sinytra Connector

### ISSUE THREAD

**Issue by mikhailfluffy** [ReplayMod/ReplayMod#1014]
Minecraft 1.21.1 crashing on NeoForge with FFAPI

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2024-11-07 11:05:35
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.client.KeyMapping.consumeClick()" because "com.koteinik.chunksfadein.core.Keybinds.toggleModKeybind" is null
	at TRANSFORMER/chunksfadein@2.0.0-1.21/com.koteinik.chunksfadein.core.Keybinds.handleKeybinds(Keybinds.java:27) ~[chunksfadein-neoforge-2.0.0-1.21.jar%23210!/:?] {re:mixin,re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.handler$bjl000$chunksfadein$modifyTick(Minecraft.java:10499) ~[client-1.21.1-20240808.144430-srg.jar%23204!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftclient,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftclient,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.tick(Minecraft.java:1916) ~[client-1.21.1-20240808.144430-srg.jar%23204!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftclient,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftclient,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.runTick(Minecraft.java:1161) ~[client-1.21.1-20240808.144430-srg.jar%23204!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftclient,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftclient,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.run(Minecraft.java:807) ~[client-1.21.1-20240808.144430-srg.jar%23204!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftclient,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftclient,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.main.Main.main(Main.java:230) ~[client-1.21.1-20240808.144430-srg.jar%23204!/:?] {re:classloading,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {re:mixin}
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.31.jar%23175!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-4.0.31.jar%23175!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32) ~[loader-4.0.31.jar%23175!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.31.jar%23175!/:4.0] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%23164!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%23164!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%23164!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%23164!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%23164!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%23164!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%23164!/:?] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?] {}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {re:mixin}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) [ForgeWrapper-prism-2024-02-29.jar:prism-2024-02-29] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at TRANSFORMER/chunksfadein@2.0.0-1.21/com.koteinik.chunksfadein.core.Keybinds.handleKeybinds(Keybinds.java:27) ~[chunksfadein-neoforge-2.0.0-1.21.jar%23210!/:?] {re:mixin,re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.handler$bjl000$chunksfadein$modifyTick(Minecraft.java:10499) ~[client-1.21.1-20240808.144430-srg.jar%23204!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftclient,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftclient,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
-- Uptime --
Details:
	JVM uptime: 20.011s
	Wall uptime: 2.986s
	High-res time: 17.713s
	Client ticks: 1 ticks / 0.050s
Stacktrace:
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.fillReport(Minecraft.java:2392) ~[client-1.21.1-20240808.144430-srg.jar%23204!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftclient,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftclient,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.emergencySaveAndCrash(Minecraft.java:868) ~[client-1.21.1-20240808.144430-srg.jar%23204!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftclient,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftclient,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.run(Minecraft.java:828) ~[client-1.21.1-20240808.144430-srg.jar%23204!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftclient,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftclient,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.main.Main.main(Main.java:230) ~[client-1.21.1-20240808.144430-srg.jar%23204!/:?] {re:classloading,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {re:mixin}
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.31.jar%23175!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-4.0.31.jar%23175!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32) ~[loader-4.0.31.jar%23175!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.31.jar%23175!/:4.0] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%23164!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%23164!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%23164!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%23164!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%23164!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%23164!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%23164!/:?] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?] {}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {re:mixin}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) [ForgeWrapper-prism-2024-02-29.jar:prism-2024-02-29] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: vanilla, file/SodiumTranslations.zip, fabric, file/§9AVPBR Retextured R2.zip

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2097152000 bytes (2000 MiB) / 4294967296 bytes (4096 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 12288.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.6603
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 22453.10
	Virtual memory used (MiB): 20077.85
	Swap memory total (MiB): 6144.00
	Swap memory used (MiB): 78.28
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 174963.70, total: 488369.00
	Space in storage for workdir (MiB): available: 174963.70, total: 488369.00
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4096m -Xmx8192m
	Loaded Shaderpack: (off)
	Launched Version: 1.21.1
	Launcher name: PrismLauncher
	Backend library: LWJGL version 3.3.3+5
	Backend API: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 4.6.0 NVIDIA 566.03, NVIDIA Corporation
	Window size: 1920x1061
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'neoforge'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 16/16 chunks
	Resource Packs: vanilla, file/SodiumTranslations.zip, fabric, file/§9AVPBR Retextured R2.zip (incompatible)
	Current Language: ru_ru
	Locale: en_RU
	System encoding: Cp1251
	File encoding: UTF-8
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor 
	ModLauncher: 11.0.4+main.d2e20e43
	ModLauncher launch target: forgeclient
	ModLauncher services: 
		sponge-mixin-0.15.2+mixin.0.8.7.jar mixin PLUGINSERVICE 
		loader-4.0.31.jar slf4jfixer PLUGINSERVICE 
		loader-4.0.31.jar runtime_enum_extender PLUGINSERVICE 
		at-modlauncher-10.0.1.jar accesstransformer PLUGINSERVICE 
		loader-4.0.31.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-11.0.4.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-11.0.4.jar fml TRANSFORMATIONSERVICE 
		modlauncher-11.0.4.jar connector_loader TRANSFORMATIONSERVICE 
	FML Language Providers: 
		javafml@4.0
		lowcodefml@4.0
		minecraft@4.0
	Mod List: 
		appleskin-neoforge-mc1.21-3.0.5.jar               |AppleSkin                     |appleskin                     |3.0.5+mc1.21        |Manifest: NOSIGNATURE
		badpackets-neo-0.8.1.jar                          |Bad Packets                   |badpackets                    |0.8.1               |Manifest: NOSIGNATURE
		baritone-api-neoforge-1.10.2-6-gec57888c.jar      |Baritone                      |baritoe                       |1.10.2-6-gec57888c  |Manifest: NOSIGNATURE
		BetterThirdPerson-neoforge-1.9.0.jar              |Better Third Person           |betterthirdperson             |1.9.0               |Manifest: NOSIGNATURE
		chunksfadein-neoforge-2.0.0-1.21.jar              |Chunks Fade In                |chunksfadein                  |2.0.0-1.21          |Manifest: NOSIGNATURE
		cloth-config-15.0.140-neoforge.jar                |Cloth Config v15 API          |cloth_config                  |15.0.140            |Manifest: NOSIGNATURE
		ConnectorExtras-1.12.1+1.21.1.jar                 |Connector Extras              |connectorextras               |1.12.1+1.21.1       |Manifest: NOSIGNATURE
		emi-bridge-1.12.1+1.21.1.jar                      |Connector Extras EMI Bridge   |connectorextras_emi_bridge    |1.12.1+1.21.1       |Manifest: NOSIGNATURE
		energy-bridge-1.12.1+1.21.1.jar                   |Connector Extras Energy Bridge|connectorextras_energy_bridge |1.12.1+1.21.1       |Manifest: NOSIGNATURE
		jei-bridge-1.12.1+1.21.1.jar                      |Connector Extras JEI Bridge   |connectorextras_jei_bridge    |1.12.1+1.21.1       |Manifest: NOSIGNATURE
		kubejs-bridge-1.12.1+1.21.1.jar                   |Connector Extras KubeJS Bridge|connectorextras_kubejs_bridge |1.12.1+1.21.1       |Manifest: NOSIGNATURE
		modmenu-bridge-1.12.1+1.21.1.jar                  |Connector Extras ModMenu Bridg|connectorextras_modmenu_bridge|1.12.1+1.21.1       |Manifest: NOSIGNATURE
		pehkui-bridge-1.12.1+1.21.1.jar                   |Connector Extras Pehkui Bridge|connectorextras_pehkui_bridge |1.12.1+1.21.1       |Manifest: NOSIGNATURE
		rei-bridge-1.12.1+1.21.1.jar                      |Connector Extras REI Bridge   |connectorextras_rei_bridge    |1.12.1+1.21.1       |Manifest: NOSIGNATURE
		terrablender-bridge-1.12.1+1.21.1.jar             |Connector Extras Terrablender |connectorextras_terrablender_b|1.12.1+1.21.1       |Manifest: NOSIGNATURE
		entity_model_features_neoforge_1.21-2.2.6.jar     |Entity Model Features         |entity_model_features         |2.2.6               |Manifest: NOSIGNATURE
		entity_texture_features_neoforge_1.21-6.2.5.jar   |Entity Texture Features       |entity_texture_features       |6.2.5               |Manifest: NOSIGNATURE
		forgified-fabric-api-0.104.0+2.0.15+1.21.1.jar    |Forgified Fabric API          |fabric_api                    |0.104.0+2.0.15+1.21.|Manifest: NOSIGNATURE
		fabric-api-base-0.4.42+d1308ded19.jar             |Forgified Fabric API Base     |fabric_api_base               |0.4.42+d1308ded19   |Manifest: NOSIGNATURE
		fabric-api-lookup-api-v1-1.6.68+c21168c319.jar    |Forgified Fabric API Lookup AP|fabric_api_lookup_api_v1      |1.6.68+c21168c319   |Manifest: NOSIGNATURE
		fabric-biome-api-v1-13.0.29+1e62d33c19.jar        |Forgified Fabric Biome API (v1|fabric_biome_api_v1           |13.0.29+1e62d33c19  |Manifest: NOSIGNATURE
		fabric-block-api-v1-1.0.22+a6e994cd19.jar         |Forgified Fabric Block API (v1|fabric_block_api_v1           |1.0.22+a6e994cd19   |Manifest: NOSIGNATURE
		fabric-blockrenderlayer-v1-1.1.52+b089b4bd19.jar  |Forgified Fabric BlockRenderLa|fabric_blockrenderlayer_v1    |1.1.52+b089b4bd19   |Manifest: NOSIGNATURE
		fabric-block-view-api-v2-1.0.10+9afaaf8c19.jar    |Forgified Fabric BlockView API|fabric_block_view_api_v2      |1.0.10+9afaaf8c19   |Manifest: NOSIGNATURE
		fabric-client-tags-api-v1-1.1.15+e053909619.jar   |Forgified Fabric Client Tags  |fabric_client_tags_api_v1     |1.1.15+e053909619   |Manifest: NOSIGNATURE
		fabric-command-api-v2-2.2.28+36d727be19.jar       |Forgified Fabric Command API (|fabric_command_api_v2         |2.2.28+36d727be19   |Manifest: NOSIGNATURE
		fabric-content-registries-v0-8.0.16+0a0c14ff19.jar|Forgified Fabric Content Regis|fabric_content_registries_v0  |8.0.16+0a0c14ff19   |Manifest: NOSIGNATURE
		fabric-convention-tags-v1-2.0.22+7f945d5b19.jar   |Forgified Fabric Convention Ta|fabric_convention_tags_v1     |2.0.22+7f945d5b19   |Manifest: NOSIGNATURE
		fabric-convention-tags-v2-2.7.0+d13df91319.jar    |Forgified Fabric Convention Ta|fabric_convention_tags_v2     |2.7.0+d13df91319    |Manifest: NOSIGNATURE
		fabric-data-attachment-api-v1-1.1.28+d82d50ba19.ja|Forgified Fabric Data Attachme|fabric_data_attachment_api_v1 |1.1.28+d82d50ba19   |Manifest: NOSIGNATURE
		fabric-data-generation-api-v1-20.2.19+ed29d49b19.j|Forgified Fabric Data Generati|fabric_data_generation_api_v1 |20.2.19+ed29d49b19  |Manifest: NOSIGNATURE
		fabric-entity-events-v1-1.7.0+34c3dc2d19.jar      |Forgified Fabric Entity Events|fabric_entity_events_v1       |1.7.0+34c3dc2d19    |Manifest: NOSIGNATURE
		fabric-events-interaction-v0-0.7.12+7b71cc1619.jar|Forgified Fabric Events Intera|fabric_events_interaction_v0  |0.7.12+7b71cc1619   |Manifest: NOSIGNATURE
		fabric-game-rule-api-v1-1.0.53+36d727be19.jar     |Forgified Fabric Game Rule API|fabric_game_rule_api_v1       |1.0.53+36d727be19   |Manifest: NOSIGNATURE
		fabric-gametest-api-v1-2.0.4+29f188ce19.jar       |Forgified Fabric Game Test API|fabric_gametest_api_v1        |2.0.4+29f188ce19    |Manifest: NOSIGNATURE
		fabric-item-api-v1-11.0.0+f56196c219.jar          |Forgified Fabric Item API (v1)|fabric_item_api_v1            |11.0.0+f56196c219   |Manifest: NOSIGNATURE
		fabric-item-group-api-v1-4.1.5+e324903319.jar     |Forgified Fabric Item Group AP|fabric_item_group_api_v1      |4.1.5+e324903319    |Manifest: NOSIGNATURE
		fabric-key-binding-api-v1-1.0.47+62cc7ce119.jar   |Forgified Fabric Key Binding A|fabric_key_binding_api_v1     |1.0.47+62cc7ce119   |Manifest: NOSIGNATURE
		fabric-lifecycle-events-v1-2.3.12+88bf4f7f19.jar  |Forgified Fabric Lifecycle Eve|fabric_lifecycle_events_v1    |2.3.12+88bf4f7f19   |Manifest: NOSIGNATURE
		fabric-loot-api-v2-3.0.14+a3ee712d19.jar          |Forgified Fabric Loot API (v2)|fabric_loot_api_v2            |3.0.14+a3ee712d19   |Manifest: NOSIGNATURE
		fabric-loot-api-v3-1.0.2+333dfad919.jar           |Forgified Fabric Loot API (v3)|fabric_loot_api_v3            |1.0.2+333dfad919    |Manifest: NOSIGNATURE
		fabric-message-api-v1-6.0.13+e053909619.jar       |Forgified Fabric Message API (|fabric_message_api_v1         |6.0.13+e053909619   |Manifest: NOSIGNATURE
		fabric-model-loading-api-v1-2.0.0+a6e994cd19.jar  |Forgified Fabric Model Loading|fabric_model_loading_api_v1   |2.0.0+a6e994cd19    |Manifest: NOSIGNATURE
		fabric-networking-api-v1-4.2.2+a6c6b14f19.jar     |Forgified Fabric Networking AP|fabric_networking_api_v1      |4.2.2+a6c6b14f19    |Manifest: NOSIGNATURE
		fabric-object-builder-api-v1-15.2.0+ba60825e19.jar|Forgified Fabric Object Builde|fabric_object_builder_api_v1  |15.2.0+ba60825e19   |Manifest: NOSIGNATURE
		fabric-particles-v1-4.0.2+824f924c19.jar          |Forgified Fabric Particles (v1|fabric_particles_v1           |4.0.2+824f924c19    |Manifest: NOSIGNATURE
		fabric-recipe-api-v1-5.0.12+59440bcc19.jar        |Forgified Fabric Recipe API (v|fabric_recipe_api_v1          |5.0.12+59440bcc19   |Manifest: NOSIGNATURE
		fabric-registry-sync-v0-5.1.2+0c9b5b5419.jar      |Forgified Fabric Registry Sync|fabric_registry_sync_v0       |5.1.2+0c9b5b5419    |Manifest: NOSIGNATURE
		fabric-renderer-indigo-1.7.0+acb05a3919.jar       |Forgified Fabric Renderer - In|fabric_renderer_indigo        |1.7.0+acb05a3919    |Manifest: NOSIGNATURE
		fabric-renderer-api-v1-3.4.0+acb05a3919.jar       |Forgified Fabric Renderer API |fabric_renderer_api_v1        |3.4.0+acb05a3919    |Manifest: NOSIGNATURE
		fabric-rendering-v1-5.0.5+2df007aa19.jar          |Forgified Fabric Rendering (v1|fabric_rendering_v1           |5.0.5+2df007aa19    |Manifest: NOSIGNATURE
		fabric-rendering-data-attachment-v1-0.3.48+73761d2|Forgified Fabric Rendering Dat|fabric_rendering_data_attachme|0.3.48+73761d2e19   |Manifest: NOSIGNATURE
		fabric-rendering-fluids-v1-3.1.6+857185bc19.jar   |Forgified Fabric Rendering Flu|fabric_rendering_fluids_v1    |3.1.6+857185bc19    |Manifest: NOSIGNATURE
		fabric-resource-conditions-api-v1-4.3.0+edeecbd819|Forgified Fabric Resource Cond|fabric_resource_conditions_api|4.3.0+edeecbd819    |Manifest: NOSIGNATURE
		fabric-resource-loader-v0-1.3.0+bcae32ce19.jar    |Forgified Fabric Resource Load|fabric_resource_loader_v0     |1.3.0+bcae32ce19    |Manifest: NOSIGNATURE
		fabric-screen-api-v1-2.0.25+b282c4bb19.jar        |Forgified Fabric Screen API (v|fabric_screen_api_v1          |2.0.25+b282c4bb19   |Manifest: NOSIGNATURE
		fabric-screen-handler-api-v1-1.3.86+8dbc56dd19.jar|Forgified Fabric Screen Handle|fabric_screen_handler_api_v1  |1.3.86+8dbc56dd19   |Manifest: NOSIGNATURE
		fabric-sound-api-v1-1.0.23+10b84f8419.jar         |Forgified Fabric Sound API (v1|fabric_sound_api_v1           |1.0.23+10b84f8419   |Manifest: NOSIGNATURE
		fabric-transfer-api-v1-5.2.0+aab4c96e19.jar       |Forgified Fabric Transfer API |fabric_transfer_api_v1        |5.2.0+aab4c96e19    |Manifest: NOSIGNATURE
		fabric-transitive-access-wideners-v1-6.1.0+0df3143|Forgified Fabric Transitive Ac|fabric_transitive_access_widen|6.1.0+0df3143b19    |Manifest: NOSIGNATURE
		iris-neoforge-1.8.0-beta.5+mc1.21.1.jar           |Iris                          |iris                          |1.8.0-beta.5+mc1.21.|Manifest: NOSIGNATURE
		MaFgLib-0.1.23-mc1.21.1.jar                       |MaFgLib                       |mafglib                       |0.1.23-mc1.21.1     |Manifest: NOSIGNATURE
		client-1.21.1-20240808.144430-srg.jar             |Minecraft                     |minecraft                     |1.21.1              |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		neoforge-21.1.73-universal.jar                    |NeoForge                      |neoforge                      |21.1.73             |Manifest: NOSIGNATURE
		notenoughanimations-neoforge-1.7.6-mc1.21.jar     |NotEnoughAnimations           |notenoughanimations           |1.7.6               |Manifest: NOSIGNATURE
		plasmovoice-neoforge-1.21-2.1.1.jar               |Plasmo Voice                  |plasmovoice                   |2.1.1               |Manifest: NOSIGNATURE
		sodium-neoforge-0.6.0-beta.4+mc1.21.1.jar         |Sodium                        |sodium                        |0.6.0-beta.4+mc1.21.|Manifest: NOSIGNATURE
		sound-physics-remastered-neoforge-1.21.1-1.4.6.jar|Sound Physics Remastered      |sound_physics_remastered      |1.21.1-1.4.6        |Manifest: NOSIGNATURE
		Female-Gender-Mod-neoforge-1.21-3.2.2.jar         |Wildfire's Female Gender Mod  |wildfire_gender               |3.2.2               |Manifest: NOSIGNATURE
		Xaeros_Minimap_24.6.1_NeoForge_1.21.jar           |Xaero's Minimap               |xaerominimap                  |24.6.1              |Manifest: NOSIGNATURE

**Comment by RaderRMT** [comment]
The ReplayMod is not designed to work on forge. If you want to use it on modern versions, use Fabric.

**Comment by mharbb** [comment]
> The ReplayMod is not designed to work on forge. If you want to use it on modern versions, use Fabric.

That's what synatra connector is for, It makes fabric mods work on forge

**Comment by RaderRMT** [comment]
> That's what synatra connector is for, It makes fabric mods work on forge
As I previously said, the ReplayMod is not designed to work on forge. If you want to use it on modern versions, use Fabric.
