### ISSUE TITLE
Replay not loading 

### ISSUE THREAD

**Issue by maivuhailong** [ReplayMod/ReplayMod#1025]
I pressed load while selecting it but then it just kept showing the Minecraft background with no UI or anything, it played music and the background was parallax for a while and then stopped. I have to close the window and even when opening it again and trying again gives the same results. The image below is the Minecraft window after pressing load.
![Screenshot 2024-12-04 172959](https://github.com/user-attachments/assets/f98bddba-23bc-4b17-a84e-c19ff41ed6e4)

**Comment by tedere-123** [comment]
I have a similar issue with version 1.20.1.

![image](https://github.com/user-attachments/assets/295a2c3d-bfbe-4414-ba74-717f95a58b66)

**Comment by maivuhailong** [comment]
Looks like it only have this problem on flat worlds

**Comment by NeonBlaze101** [comment]
I also have this issue on Minecraft 1.21.3 with fabric mod loader 0.16.9. My launcher (Prism) also freeze while minecraft only show the background.
Here is part of my game's log. the error repeats with different package ids:

] [Render thread/INFO]: Opening replay in viewer: [redacted_path_to_replay_save].mcpr
[18:11:54] [Thread-15/ERROR]: Loading entity tracker:
java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): PooledUnsafeDirectByteBuf(ridx: 1, widx: 1, cap: 1)
	at knot/io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-buffer-4.1.97.Final.jar:?]
	at knot/io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[netty-buffer-4.1.97.Final.jar:?]
	at knot/com.replaymod.lib.com.github.steveice10.packetlib.tcp.io.ByteBufNetInput.readByte(ByteBufNetInput.java:26) ~[replaymod-1.21.2-2.6.21.jar:?]
	at knot/com.replaymod.lib.com.github.steveice10.packetlib.tcp.io.ByteBufNetInput.readVarInt(ByteBufNetInput.java:59) ~[replaymod-1.21.2-2.6.21.jar:?]
	at knot/com.replaymod.replaystudio.protocol.packets.EntityId.getEntityId(EntityId.java:111) ~[replaymod-1.21.2-2.6.21.jar:?]
	at knot/com.replaymod.replaystudio.util.PacketUtils.getEntityId(PacketUtils.java:58) ~[replaymod-1.21.2-2.6.21.jar:?]
	at knot/com.replaymod.replaystudio.util.EntityPositionTracker.loadFromPacketData(EntityPositionTracker.java:164) ~[replaymod-1.21.2-2.6.21.jar:?]
	at knot/com.replaymod.replaystudio.util.EntityPositionTracker.load(EntityPositionTracker.java:95) ~[replaymod-1.21.2-2.6.21.jar:?]
	at knot/com.replaymod.simplepathing.gui.GuiPathing.lambda$startLoadingEntityTracker$6(GuiPathing.java:537) ~[replaymod-1.21.2-2.6.21.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[18:11:54] [Render thread/INFO]: [System] [CHAT] [Replay Mod] Error loading entity tracker: readerIndex(1) + length(1) exceeds writerIndex(1): PooledUnsafeDirectByteBuf(ridx: 1, widx: 1, cap: 1)
[18:11:54] [replaymod-async-sender/INFO]: [STDERR]: io.netty.handler.codec.DecoderException: Received unknown packet id 1333
[18:11:54] [replaymod-async-sender/INFO]: [STDERR]: 	at knot//net.minecraft.class_9136.method_56425(class_9136.java:32)
[18:11:54] [replaymod-async-sender/INFO]: [STDERR]: 	at knot//net.minecraft.class_9136.decode(class_9136.java:14)
[18:11:54] [replaymod-async-sender/INFO]: [STDERR]: 	at knot//net.minecraft.class_2543.decode(class_2543.java:31)
[18:11:54] [replaymod-async-sender/INFO]: [STDERR]: 	at knot//io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
[18:11:54] [replaymod-async-sender/INFO]: [STDERR]: 	at knot//io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
[18:11:54] [replaymod-async-sender/INFO]: [STDERR]: 	at knot//io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
[18:11:54] [replaymod-async-sender/INFO]: [STDERR]: 	at knot//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[18:11:54] [replaymod-async-sender/INFO]: [STDERR]: 	at knot//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[18:11:54] [replaymod-async-sender/INFO]: [STDERR]: 	at knot//io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[18:11:54] [replaymod-async-sender/INFO]: [STDERR]: 	at knot//io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[18:11:54] [replaymod-async-sender/INFO]: [STDERR]: 	at knot//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[18:11:54] [replaymod-async-sender/INFO]: [STDERR]: 	at knot//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[18:11:54] [replaymod-async-sender/INFO]: [STDERR]: 	at knot//io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[18:11:54] [replaymod-async-sender/INFO]: [STDERR]: 	at knot//com.replaymod.replay.FullReplaySender$2.run(FullReplaySender.java:1101)
[18:11:54] [replaymod-async-sender/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[18:11:54] [replaymod-async-sender/INFO]: [STDERR]: io.netty.handler.codec.DecoderException: Received unknown packet id 120
[18:11:54] [replaymod-async-sender/INFO]: [STDERR]: 	at knot//net.minecraft.class_9136.method_56425(class_9136.java:32)
[18:11:54] [replaymod-async-sender/INFO]: [STDERR]: 	at knot//net.minecraft.class_9136.decode(class_9136.java:14)
[18:11:54] [replaymod-async-sender/INFO]: [STDERR]: 	at knot//net.minecraft.class_2543.decode(class_2543.java:31)
[18:11:54] [replaymod-async-sender/INFO]: [STDERR]: 	at knot//io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
[18:11:54] [replaymod-async-sender/INFO]: [STDERR]: 	at knot//io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
[18:11:54] [replaymod-async-sender/INFO]: [STDERR]: 	at knot//io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
[18:11:54] [replaymod-async-sender/INFO]: [STDERR]: 	at knot//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[18:11:54] [replaymod-async-sender/INFO]: [STDERR]: 	at knot//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[18:11:54] [replaymod-async-sender/INFO]: [STDERR]: 	at knot//io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[18:11:54] [replaymod-async-sender/INFO]: [STDERR]: 	at knot//io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[18:11:54] [replaymod-async-sender/INFO]: [STDERR]: 	at knot//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[18:11:54] [replaymod-async-sender/INFO]: [STDERR]: 	at knot//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[18:11:54] [replaymod-async-sender/INFO]: [STDERR]: 	at knot//io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[18:11:54] [replaymod-async-sender/INFO]: [STDERR]: 	at knot//com.replaymod.replay.FullReplaySender$2.run(FullReplaySender.java:1101)
[18:11:54] [replaymod-async-sender/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by Decrepitdoors** [comment]
same issue on 1.21.4 fabric. replay is only 10 minutes long. could be an incompatible with a mod - here's the log https://mclo.gs/cWHA6fh
