### ISSUE TITLE
Crash when saving Replay in 1.15

### ISSUE THREAD

**Issue by CrushedPixel** [ReplayMod/ReplayMod#121]
```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 4/2/20 5:54 PM
Description: Saving replay file

io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release0(AbstractReferenceCountedByteBuf.java:100)
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:84)
	at com.replaymod.replaystudio.protocol.Packet.release(Packet.java:102)
	at com.replaymod.replaystudio.PacketData.release(PacketData.java:69)
	at com.replaymod.replaystudio.filter.SquashFilter$$Lambda$3101/373148120.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.replaymod.replaystudio.filter.SquashFilter.onPacket(SquashFilter.java:351)
	at com.replaymod.editor.gui.MarkerProcessor.apply(MarkerProcessor.java:144)
	at com.replaymod.recording.packet.PacketListener.lambda$channelInactive$8(PacketListener.java:233)
	at com.replaymod.recording.packet.PacketListener$$Lambda$3024/964803092.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1016281624 bytes (969 MB) / 2113929216 bytes (2016 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.5.1+build.294-1.15
		fabric-api-base: Fabric API Base 0.1.2+b7f9825d0c
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890c
		fabric-commands-v0: Fabric Commands (v0) 0.1.2+b7f9825d0c
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
		fabric-dimensions-v1: fabric-dimensions-v1 0.3.0+2ad156310c
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+fac69e320c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+b7f9825d0c
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+ec40b2e10c
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d60c
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.1+b7f9825d0c
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60c
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
		fabric-networking-v0: Fabric Networking (v0) 0.1.7+12515ed90c
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.3+e4c9a9c30c
		fabric-particles-v1: fabric-particles-v1 0.1.1+dfdb52d60c
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.10+f08b61330c
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.23+9290e2ed0c
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600c
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed90c
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900c
		fabric-rendering-v1: Fabric Rendering (v1) 0.1.0+534104900c
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b30c
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915800c
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba70c
		fabricloader: Fabric Loader 0.7.9+build.190
		minecraft: Minecraft 1.15.2
		replaymod: Replay Mod 1.15.2-2.2.0-b7-43-g065d713

```

**Comment by Johni0702** [comment]
Can we get the replay which caused this? Should be in `.minecraft/replay_recordings/raw/`.
(this applies to all crashes related to `MarkerProcessor` or `RandomAccessReplay`)

**Comment by LogicalGeekBoy** [comment]
I've seen reports of this too when exiting a server and the replay is trying to save. Here are two reports from two different players from the same server. I record on the same server but haven't seen this issue personally.

[Replay_Mod_Error_-_Chim_1.txt](https://github.com/ReplayMod/ReplayMod/files/4450619/Replay_Mod_Error_-_Chim_1.txt)
[crash-2020-04-07_10.38.18-client (1).txt](https://github.com/ReplayMod/ReplayMod/files/4450623/crash-2020-04-07_10.38.18-client.1.txt)

**Comment by Johni0702** [comment]
@LogicalGeekBoy This should be fixed as of the commits linked above, if you're getting similar issues on a newer version, please open a separate issue.
The reason you probably never ran into it is that it can only happen when you use the Start/Stop/Pause/Resume recording feature and I'd guess you aren't using it.
