### ISSUE TITLE
Error running latest (Stable) version of Replay mod in forge 1.12.2

### ISSUE THREAD

**Issue by explodersname** [ReplayMod/ReplayMod#154]
Whilst launching forge, everything runs as usual until the end. At the end it closes, and the Minecraft launcher comes up with an error: I hit view crash report and got this:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (replaymod-1.12.2-2.1.4.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 5/4/20 8:44 PM
Description: Unexpected error

java.lang.NoClassDefFoundError: dkf
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.replaymod.compat.shaders.ShaderReflection.<clinit>(ShaderReflection.java:32)
	at com.replaymod.compat.shaders.ShaderBeginRender.onRenderTickStart(ShaderBeginRender.java:23)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_20_ShaderBeginRender_onRenderTickStart_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickStart(FMLCommonHandler.java:355)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: dkf
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 17 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 19 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.19.98-08076-g24ab33fb8e14
	Java Version: 1.8.0_252, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 502813136 bytes (479 MB) / 1073741824 bytes (1024 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                      | Version      | Source                        | Signature |
	|:------ |:----------------------- |:------------ |:----------------------------- |:--------- |
	| LCHIJA | minecraft               | 1.12.2       | minecraft.jar                 | None      |
	| LCHIJA | mcp                     | 9.42         | minecraft.jar                 | None      |
	| LCHIJA | FML                     | 8.0.99.99    | forge-1.12.2-14.23.5.2847.jar | None      |
	| LCHIJA | forge                   | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar | None      |
	| LCHIJA | replaymod-compat        | 1.12.2-2.1.4 | replaymod-1.12.2-2.1.4.jar    | None      |
	| LCHIJA | replaymod               | 1.12.2-2.1.4 | replaymod-1.12.2-2.1.4.jar    | None      |
	| LCHIJA | replaymod-editor        | 1.12.2-2.1.4 | replaymod-1.12.2-2.1.4.jar    | None      |
	| LCHIJA | replaymod-extras        | 1.12.2-2.1.4 | replaymod-1.12.2-2.1.4.jar    | None      |
	| LCHIJA | replaymod-online        | 1.12.2-2.1.4 | replaymod-1.12.2-2.1.4.jar    | None      |
	| LCHIJA | replaymod-recording     | 1.12.2-2.1.4 | replaymod-1.12.2-2.1.4.jar    | None      |
	| LCHIJA | replaymod-render        | 1.12.2-2.1.4 | replaymod-1.12.2-2.1.4.jar    | None      |
	| LCHIJA | replaymod-replay        | 1.12.2-2.1.4 | replaymod-1.12.2-2.1.4.jar    | None      |
	| LCHIJA | replaymod-simplepathing | 1.12.2-2.1.4 | replaymod-1.12.2-2.1.4.jar    | None      |

	Loaded coremods (and transformers): 
LoadingPlugin (replaymod-1.12.2-2.1.4.jar)
  
	GL info: ' Vendor: 'Intel Open Source Technology Center' Version: '3.0 Mesa 18.0.5' Renderer: 'Mesa DRI Intel(R) HD Graphics 400 (Braswell) '
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: Mesa DRI Intel(R) HD Graphics 400 (Braswell)  GL version 3.0 Mesa 18.0.5, Intel Open Source Technology Center
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Celeron(R) CPU N3160 @ 1.60GHz
I hope you can help! also the smaller bits of text that pops up before clicking view crash report says this: The game crashed whilst unexpected error
Error: java.lang.NoClassDefFoundError: dkf
if that is also important.

**Comment by Johni0702** [comment]
Huh, that's a strange error. My only guess is that you've got Optifine lying around somewhere and Forge or something else allowed it to be loaded but not properly.
Do you maybe have a non-forge-compatible Optifine jar in your mods folder?
