### ISSUE TITLE
Replay mod crashing at 4 to 15000 frames while rendering

### ISSUE THREAD

**Issue by OliveTree-byte1244313432** [ReplayMod/ReplayMod#178]
I am trying to use the replay mod and fabric to record a timelapse in minecraft but it keeps crashing. Could someone help?

**Comment by Nemos59** [comment]
Can you send the crash report? It will be helpful to see when the crash happens

**Comment by OliveTree-byte1244313432** [comment]
The crash report is different every time but ok

**Comment by OliveTree-byte1244313432** [comment]
---- Minecraft Crash Report ----
// Sorry :(

Time: 5/15/20 11:42 AM
Description: Saving replay file

java.lang.NullPointerException: Saving replay file
	at com.replaymod.replaystudio.protocol.Packet.<init>(Packet.java:58)
	at com.replaymod.replaystudio.protocol.Packet.<init>(Packet.java:54)
	at com.replaymod.replaystudio.protocol.packets.PacketEntityMovement.write(PacketEntityMovement.java:96)
	at com.replaymod.replaystudio.filter.SquashFilter.onEnd(SquashFilter.java:504)
	at com.replaymod.editor.gui.MarkerProcessor.apply(MarkerProcessor.java:100)
	at com.replaymod.recording.packet.PacketListener.lambda$channelInactive$9(PacketListener.java:243)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Mac OS X (x86_64) version 10.13.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1210762960 bytes (1154 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.10.7+build.309-1.15
		fabric-api-base: Fabric API Base 0.1.2+b7f9825d0c
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890c
		fabric-climbable-api-v1: Fabric Climbable API (v1) 1.0.0+6ffe71e20c
		fabric-command-api-v1: Fabric Command API (v1) 1.0.2+2aebb7ff0c
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+2e0c4ff50c
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
		fabric-dimensions-v1: fabric-dimensions-v1 0.3.0+2ad156310c
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+fac69e320c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+003643510c
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+045efb460c
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d60c
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+ec951ea40c
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60c
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
		fabric-networking-v0: Fabric Networking (v0) 0.1.7+003643510c
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.0.0+796d1cc40c
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.5.1+c515a2820c
		fabric-particles-v1: fabric-particles-v1 0.1.2+ad2f81bd0c
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.10+f08b61330c
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.23+9290e2ed0c
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600c
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed90c
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900c
		fabric-rendering-v1: Fabric Rendering (v1) 1.0.0+2a034f0a0c
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b30c
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915800c
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba70c
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.0.2+915c44630c
		fabricloader: Fabric Loader 0.8.2+build.194
		minecraft: Minecraft 1.15.2
		replaymod: Replay Mod 1.15.2-2.3.0-b1

**Comment by OliveTree-byte1244313432** [comment]
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 5/15/20 7:54 AM
Description: Running marker processor

java.lang.NullPointerException: Running marker processor
	at com.replaymod.replaystudio.protocol.Packet.<init>(Packet.java:58)
	at com.replaymod.replaystudio.protocol.Packet.<init>(Packet.java:54)
	at com.replaymod.replaystudio.protocol.packets.PacketEntityMovement.write(PacketEntityMovement.java:96)
	at com.replaymod.replaystudio.filter.SquashFilter.onEnd(SquashFilter.java:504)
	at com.replaymod.editor.gui.MarkerProcessor.apply(MarkerProcessor.java:100)
	at com.replaymod.editor.gui.GuiEditReplay.lambda$apply$10(GuiEditReplay.java:160)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Mac OS X (x86_64) version 10.13.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1548160192 bytes (1476 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.10.7+build.309-1.15
		fabric-api-base: Fabric API Base 0.1.2+b7f9825d0c
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890c
		fabric-climbable-api-v1: Fabric Climbable API (v1) 1.0.0+6ffe71e20c
		fabric-command-api-v1: Fabric Command API (v1) 1.0.2+2aebb7ff0c
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+2e0c4ff50c
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
		fabric-dimensions-v1: fabric-dimensions-v1 0.3.0+2ad156310c
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+fac69e320c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+003643510c
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+045efb460c
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d60c
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+ec951ea40c
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60c
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
		fabric-networking-v0: Fabric Networking (v0) 0.1.7+003643510c
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.0.0+796d1cc40c
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.5.1+c515a2820c
		fabric-particles-v1: fabric-particles-v1 0.1.2+ad2f81bd0c
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.10+f08b61330c
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.23+9290e2ed0c
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600c
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed90c
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900c
		fabric-rendering-v1: Fabric Rendering (v1) 1.0.0+2a034f0a0c
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b30c
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915800c
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba70c
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.0.2+915c44630c
		fabricloader: Fabric Loader 0.8.2+build.194
		minecraft: Minecraft 1.15.2
		replaymod: Replay Mod 1.15.2-2.3.0-b1

**Comment by OliveTree-byte1244313432** [comment]
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 5/7/20 3:23 PM
Description: Calling Gui method

java.lang.NullPointerException: Calling Gui method
	at com.replaymod.replay.ReplayHandler.doJump(ReplayHandler.java:689)
	at com.replaymod.replay.gui.overlay.GuiReplayOverlay$7.run(GuiReplayOverlay.java:131)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.advanced.AbstractGuiTimeline.onClick(AbstractGuiTimeline.java:197)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.advanced.AbstractGuiTimeline.mouseClick(AbstractGuiTimeline.java:262)
	at com.replaymod.replay.gui.overlay.GuiMarkerTimeline.mouseClick(GuiMarkerTimeline.java:184)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.AbstractComposedGuiElement$3.invoke(AbstractComposedGuiElement.java:150)
	at com.sun.proxy.$Proxy28.mouseClick(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.AbstractComposedGuiElement$3.invoke(AbstractComposedGuiElement.java:147)
	at com.sun.proxy.$Proxy28.mouseClick(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.AbstractComposedGuiElement$2.invoke(AbstractComposedGuiElement.java:80)
	at com.sun.proxy.$Proxy28.mouseClick(Unknown Source)
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiOverlay$UserInputGuiScreen.mouseClicked(AbstractGuiOverlay.java:340)
	at net.minecraft.class_312.method_1611(class_312.java:86)
	at net.minecraft.class_437.wrapScreenError(class_437.java:447)
	at net.minecraft.class_312.method_1601(class_312.java:86)
	at net.minecraft.class_312.method_22686(class_312.java:150)
	at net.minecraft.class_1255.execute(class_1255.java:104)
	at net.minecraft.class_312.method_22684(class_312.java:150)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3050)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:98)
	at net.minecraft.class_1041.method_15998(class_1041.java:363)
	at net.minecraft.class_310.method_1523(class_310.java:1012)
	at net.minecraft.class_310.method_1514(class_310.java:619)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.replaymod.replay.ReplayHandler.doJump(ReplayHandler.java:689)
	at com.replaymod.replay.gui.overlay.GuiReplayOverlay$7.run(GuiReplayOverlay.java:131)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.advanced.AbstractGuiTimeline.onClick(AbstractGuiTimeline.java:197)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.advanced.AbstractGuiTimeline.mouseClick(AbstractGuiTimeline.java:262)
	at com.replaymod.replay.gui.overlay.GuiMarkerTimeline.mouseClick(GuiMarkerTimeline.java:184)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

-- Gui --
Details:
	Method: public abstract boolean com.replaymod.lib.de.johni0702.minecraft.gui.function.Clickable.mouseClick(com.replaymod.lib.de.johni0702.minecraft.gui.utils.lwjgl.ReadablePoint,int)
	ComposedElement: com.replaymod.replay.gui.overlay.GuiReplayOverlay$2@4052305e
	Element: com.replaymod.replay.gui.overlay.GuiReplayOverlay$2@4052305e
Stacktrace:
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.AbstractComposedGuiElement$3.invoke(AbstractComposedGuiElement.java:150)
	at com.sun.proxy.$Proxy28.mouseClick(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

-- Gui --
Details:
	Method: public abstract boolean com.replaymod.lib.de.johni0702.minecraft.gui.function.Clickable.mouseClick(com.replaymod.lib.de.johni0702.minecraft.gui.utils.lwjgl.ReadablePoint,int)
	ComposedElement: com.replaymod.lib.de.johni0702.minecraft.gui.container.GuiPanel@67c8ca0f
	Element: com.replaymod.lib.de.johni0702.minecraft.gui.container.GuiPanel@67c8ca0f
Stacktrace:
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.AbstractComposedGuiElement$3.invoke(AbstractComposedGuiElement.java:147)
	at com.sun.proxy.$Proxy28.mouseClick(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

-- Gui --
Details:
	Method: public abstract boolean com.replaymod.lib.de.johni0702.minecraft.gui.function.Clickable.mouseClick(com.replaymod.lib.de.johni0702.minecraft.gui.utils.lwjgl.ReadablePoint,int)
	ComposedElement: com.replaymod.replay.gui.overlay.GuiReplayOverlay@5af08862
	Element: com.replaymod.replay.gui.overlay.GuiReplayOverlay@5af08862
Stacktrace:
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.AbstractComposedGuiElement$2.invoke(AbstractComposedGuiElement.java:80)
	at com.sun.proxy.$Proxy28.mouseClick(Unknown Source)
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiOverlay$UserInputGuiScreen.mouseClicked(AbstractGuiOverlay.java:340)
	at net.minecraft.class_312.method_1611(class_312.java:86)

-- Affected screen --
Details:
	Screen name: com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiOverlay.UserInputGuiScreen
Stacktrace:
	at net.minecraft.class_437.wrapScreenError(class_437.java:447)
	at net.minecraft.class_312.method_1601(class_312.java:86)
	at net.minecraft.class_312.method_22686(class_312.java:150)
	at net.minecraft.class_1255.execute(class_1255.java:104)
	at net.minecraft.class_312.method_22684(class_312.java:150)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3050)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:98)
	at net.minecraft.class_1041.method_15998(class_1041.java:363)
	at net.minecraft.class_310.method_1523(class_310.java:1012)
	at net.minecraft.class_310.method_1514(class_310.java:619)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Mac OS X (x86_64) version 10.13.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1273881592 bytes (1214 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.10.1+build.307-1.15
		fabric-api-base: Fabric API Base 0.1.2+b7f9825d0c
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890c
		fabric-climbable-api-v1: Fabric Climbable API (v1) 1.0.0+6ffe71e20c
		fabric-command-api-v1: Fabric Command API (v1) 1.0.1+7b6f8bc50c
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+2e0c4ff50c
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
		fabric-dimensions-v1: fabric-dimensions-v1 0.3.0+2ad156310c
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+fac69e320c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+003643510c
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+045efb460c
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d60c
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+ec951ea40c
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60c
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
		fabric-networking-v0: Fabric Networking (v0) 0.1.7+003643510c
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.0.0+796d1cc40c
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.5.0+796d1cc40c
		fabric-particles-v1: fabric-particles-v1 0.1.2+ad2f81bd0c
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.10+f08b61330c
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.23+9290e2ed0c
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600c
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed90c
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900c
		fabric-rendering-v1: Fabric Rendering (v1) 1.0.0+2a034f0a0c
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b30c
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915800c
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba70c
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.0.2+915c44630c
		fabricloader: Fabric Loader 0.8.2+build.194
		minecraft: Minecraft 1.15.2
		mm: Manningham Mills 2.0
		optifabric: Optifabric 1.0.0-beta8
		org_slf4j_slf4j-api: slf4j-api 1.7.30
		org_slf4j_slf4j-simple: slf4j-simple 1.7.30
		org_zeroturnaround_zt-zip: zt-zip 1.14
		replaymod: Replay Mod 1.15.2-2.3.0-b1
	Launched Version: fabric-loader-0.8.2+build.194-1.15.2
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: Intel(R) HD Graphics 6000 GL version 2.1 INTEL-10.36.26, Intel Inc.
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: optifine
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre10
	OptiFine Build: 20200327-015852
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Enhanced Default v1.11.zip
	OpenGlVersion: 2.1 INTEL-10.36.26
	OpenGlRenderer: Intel(R) HD Graphics 6000
	OpenGlVendor: Intel Inc.
	CpuCount: 4

**Comment by Nemos59** [comment]
Can you try rendering your video using the latest version of the ReplayMod? I see you're still using the 2.3.0 beta version

**Comment by OliveTree-byte1244313432** [comment]
Its different every time. I had optifine installed so i tried to install optifabric but it kept saying "Can't find optifine 1.15.2" Even though i installed it. Thanks so much for being here to answer questions

**Comment by OliveTree-byte1244313432** [comment]
Ok ill report back with the new replay mod

**Comment by OliveTree-byte1244313432** [comment]
Thank you so much!! It seems to be working. I have a question though, is it normal that it is rendering like 700 frames per minute?

**Comment by Nemos59** [comment]
Rendering takes some time because of ffmpeg, we can't do anything about it

**Comment by OliveTree-byte1244313432** [comment]
Ok. Thanks again!
