### ISSUE TITLE
ReplayMod 1.8.9

### ISSUE THREAD

**Issue by xFlesss** [ReplayMod/ReplayMod#188]
For some reason when i launch minecraft with ReplayMod in mods folder my minecraft launches but it dosnt show up, after I remove the replay mod it opens perfectly fine, but if it is included it doesn't open at all. Im using Replay Mod 1.8.9.Please Help.

<details>

```
[20:25:26] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[20:25:26] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[20:25:26] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[20:25:26] [main/INFO]: Forge Mod Loader version 11.15.1.1722 for Minecraft 1.8.9 loading
[20:25:26] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Program Files (x86)\Minecraft Launcher\runtime\jre-x64
[20:25:26] [main/WARN]: The coremod io.framesplus.forge.FMLLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:25:26] [main/WARN]: The coremod forge.FMLLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:25:26] [main/WARN]: The coremod io.prplz.mousedelayfix.FMLLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:25:26] [main/WARN]: The coremod us.nickfraction.oofmod.modcore.FMLLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:25:26] [main/INFO]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.8.9_HD_U_I7.jar
[20:25:26] [main/INFO]: Loading tweaker com.replaymod.core.tweaker.ReplayModTweaker from replaymod-1.8.9-2.3.0.jar
[20:25:26] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:25:26] [main/INFO]: Loading tweak class name optifine.OptiFineForgeTweaker
[20:25:26] [main/INFO]: Loading tweak class name com.replaymod.core.tweaker.ReplayModTweaker
[20:25:26] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[20:25:26] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:25:26] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:25:26] [main/INFO]: Calling tweak class optifine.OptiFineForgeTweaker
[20:25:26] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[20:25:26] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[20:25:26] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ClassTransformer
[20:25:26] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ZIP file: C:\Users\alexa\AppData\Roaming\.minecraft\mods\OptiFine_1.8.9_HD_U_I7.jar
[20:25:26] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:25:27] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[20:25:27] [main/ERROR]: FML appears to be missing any signature data. This is not a good thing
[20:25:27] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:25:27] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:25:27] [main/INFO]: [io.framesplus.b.a:e:-1]: java.lang.ClassNotFoundException: club.sk1er.mods.core.ModCore
[20:25:27] [main/INFO]: [io.framesplus.b.a:e:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[20:25:27] [main/INFO]: [io.framesplus.b.a:e:-1]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[20:25:27] [main/INFO]: [io.framesplus.b.a:e:-1]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[20:25:27] [main/INFO]: [io.framesplus.b.a:e:-1]: 	at java.lang.Class.forName0(Native Method)
[20:25:27] [main/INFO]: [io.framesplus.b.a:e:-1]: 	at java.lang.Class.forName(Class.java:264)
[20:25:27] [main/INFO]: [io.framesplus.b.a:e:-1]: 	at io.framesplus.b.a.e(a.java)
[20:25:27] [main/INFO]: [io.framesplus.b.a:e:-1]: 	at io.framesplus.b.a.a(a.java)
[20:25:27] [main/INFO]: [io.framesplus.b.a:e:-1]: 	at io.framesplus.forge.FMLLoadingPlugin.getASMTransformerClass(FMLLoadingPlugin.java)
[20:25:27] [main/INFO]: [io.framesplus.b.a:e:-1]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:121)
[20:25:27] [main/INFO]: [io.framesplus.b.a:e:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[20:25:27] [main/INFO]: [io.framesplus.b.a:e:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:25:27] [main/INFO]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.NullPointerException
[20:25:27] [main/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[20:25:27] [main/INFO]: [java.lang.Throwable:printStackTrace:634]: 	... 10 more
[20:25:27] [main/INFO]: [io.framesplus.b.a:b:-1]: Fetching https://api.sk1er.club/modcore_versions
[20:25:28] [main/INFO]: [club.sk1er.mods.core.transform.transformers.ForgeAtButPublic:readMapFile:156]: Loaded 3 rules from ForgeAtButPublic config file modcore_at.cfg
[20:25:28] [main/INFO]: Starting Frames+ library v3
[20:25:28] [main/INFO]: [io.framesplus.util.NativeUtil:<clinit>:-1]: Loading C:\Users\alexa\AppData\Roaming\.minecraft\frames_natives\frames_plus.dll
[20:25:28] [main/INFO]: Authenticating version 2.0 for user Ange101lol
[20:25:29] [main/INFO]: Logging in with details: Server-Hash: 65569e243fdc22855e391d088a6b7dfb0d5354ed Session: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NzlmMjM2MmMwMTY3YWUyZjQ4YmZhZTA2NzVlNDJjYSIsInlnZ3QiOiIzNGYxZjA2ZGQ5MDE0OGFlYTExY2IyNjNmMTg5N2UwOSIsInNwciI6ImEyNWE4MGNkN2YzMTQxZjA5N2QxMjFmZTk2MjlhZTZiIiwiaXNzIjoiWWdnZHJhc2lsLUF1dGgiLCJleHAiOjE1OTAzNjgxNjAsImlhdCI6MTU5MDE5NTM2MH0.Ps_t07i_Kur85omfLyrU4GgJcliRfjPhKouqc2lni4E UUID: a25a80cd7f3141f097d121fe9629ae6b
[20:25:29] [main/INFO]: Mojang authentication response : 204
[20:25:29] [main/INFO]: Checking license key : trial
[20:25:33] [main/INFO]: Started Frames+ library
[20:25:33] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:25:33] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:25:33] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:25:33] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:25:33] [main/INFO]: Calling tweak class com.replaymod.core.tweaker.ReplayModTweaker
[20:25:33] [main/INFO]: [com.replaymod.extras.modcore.ModCoreInstaller:fetchString:255]: Fetching https://api.sk1er.club/modcore_versions
[20:25:33] [main/INFO]: [com.replaymod.extras.modcore.ModCoreInstaller:initialize:134]: No ModCore target for 1.8.9_forge. Aborting install
[20:25:33] [main/INFO]: [com.replaymod.core.tweaker.ReplayModTweaker:initModCore:60]: ReplayMod ModCore init result: -2
[20:25:33] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[20:25:33] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[20:25:33] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[20:25:33] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.10 Source=file:/C:/Users/alexa/AppData/Roaming/.minecraft/mods/replaymod-1.8.9-2.3.0.jar Service=LaunchWrapper Env=CLIENT
[20:25:33] [main/DEBUG]: Instantiating coremod class LoadingPlugin
[20:25:33] [main/WARN]: The coremod com.replaymod.core.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:25:33] [main/INFO]: Compatibility level set to JAVA_8
[20:25:33] [main/DEBUG]: Enqueued coremod LoadingPlugin
[20:25:33] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[20:25:33] [main/INFO]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[20:25:33] [main/INFO]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@2b34e38c
[20:25:33] [main/DEBUG]: Injecting coremod LoadingPlugin {com.replaymod.core.LoadingPlugin} class transformers
[20:25:33] [main/DEBUG]: Injection complete
[20:25:33] [main/DEBUG]: Running coremod plugin for LoadingPlugin {com.replaymod.core.LoadingPlugin}
[20:25:33] [main/DEBUG]: Running coremod plugin LoadingPlugin
[20:25:33] [main/DEBUG]: Coremod plugin class LoadingPlugin run successfully
[20:25:33] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[20:25:33] [main/INFO]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[20:25:33] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: getLaunchArguments
[20:25:33] [main/INFO]: Found 1 transformers for net.minecraft.client.Minecraft
[20:25:33] [main/INFO]: Applying transformer club.sk1er.mods.core.transformers.MinecraftTransformer on net.minecraft.client.Minecraft...
[20:25:33] [main/INFO]: A re-entrant transformer '$wrapper.club.sk1er.mods.core.forge.ClassTransformer' was detected and will no longer process meta class data
[20:25:33] [main/INFO]: Found 1 transformers for net.minecraft.client.Minecraft
[20:25:33] [main/INFO]: [io.prplz.mousedelayfix.ClassTransformer:transform:23]: Found EntityLivingBase: pr
[20:25:33] [main/INFO]: [io.prplz.mousedelayfix.ClassTransformer:transform:30]: Found getLook: d
[20:25:33] [main/INFO]: [io.prplz.mousedelayfix.ClassTransformer:transform:32]: Found Entity: pk
[20:25:33] [main/INFO]: [io.prplz.mousedelayfix.ClassTransformer:transform:34]: Found EntityPlayerSP: bew
[20:25:34] [main/INFO]: Found 1 transformers for net.minecraft.client.renderer.RenderGlobal
[20:25:34] [main/INFO]: Found 1 transformers for net.minecraft.client.renderer.EntityRenderer
[20:25:34] [main/INFO]: Overriding class: net.minecraft.client.particle.EffectRenderer
[20:25:34] [main/INFO]: Found 1 transformers for net.minecraft.nbt.NBTTagCompound
[20:25:34] [main/INFO]: Found 1 transformers for net.minecraft.entity.player.EntityPlayer
[20:25:34] [main/INFO]: [io.prplz.mousedelayfix.ClassTransformer:transform:23]: Found EntityLivingBase: pr
[20:25:34] [main/INFO]: [io.prplz.mousedelayfix.ClassTransformer:transform:30]: Found getLook: d
[20:25:34] [main/INFO]: [io.prplz.mousedelayfix.ClassTransformer:transform:32]: Found Entity: pk
[20:25:34] [main/INFO]: [io.prplz.mousedelayfix.ClassTransformer:transform:34]: Found EntityPlayerSP: bew
[20:25:34] [main/INFO]: Found 1 transformers for net.minecraft.entity.Entity
[20:25:34] [main/INFO]: Found 1 transformers for net.minecraft.client.entity.AbstractClientPlayer
[20:25:34] [main/INFO]: A re-entrant transformer '$wrapper.io.framesplus.forge.ClassTransformer' was detected and will no longer process meta class data
[20:25:34] [main/WARN]: Error loading class: net/minecraft/client/renderer/WorldRenderer$LocalRenderInformationContainer (java.lang.ClassNotFoundException: The specified class 'net.minecraft.client.renderer.WorldRenderer$LocalRenderInformationContainer' was not found)
[20:25:34] [main/WARN]: @Mixin target net.minecraft.client.renderer.WorldRenderer$LocalRenderInformationContainer was not found mixins.render.blend.replaymod.json:ContainerLocalRenderInformationAccessor
[20:25:34] [main/FATAL]: Mixin prepare failed preparing EntityAccessor in mixins.render.blend.replaymod.json: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException Critical problem: mixins.render.blend.replaymod.json:EntityAccessor target net.minecraft.entity.Entity was already transformed.
org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: mixins.render.blend.replaymod.json:EntityAccessor target net.minecraft.entity.Entity was already transformed.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:885) ~[replaymod-1.8.9-2.3.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:856) ~[replaymod-1.8.9-2.3.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:809) ~[replaymod-1.8.9-2.3.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569) ~[replaymod-1.8.9-2.3.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:506) ~[replaymod-1.8.9-2.3.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:647) [replaymod-1.8.9-2.3.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) [replaymod-1.8.9-2.3.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) [replaymod-1.8.9-2.3.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) [replaymod-1.8.9-2.3.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) [replaymod-1.8.9-2.3.0.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at java.lang.Class.forName0(Native Method) [?:1.8.0_51]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[20:25:34] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.client.main.Main
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.render.blend.replaymod.json:EntityAccessor] from phase [DEFAULT] in config [mixins.render.blend.replaymod.json] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779) ~[replaymod-1.8.9-2.3.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinPrepareError(MixinTransformer.java:728) ~[replaymod-1.8.9-2.3.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:650) ~[replaymod-1.8.9-2.3.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) ~[replaymod-1.8.9-2.3.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) ~[replaymod-1.8.9-2.3.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) ~[replaymod-1.8.9-2.3.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[replaymod-1.8.9-2.3.0.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	... 6 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: mixins.render.blend.replaymod.json:EntityAccessor target net.minecraft.entity.Entity was already transformed.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:885) ~[replaymod-1.8.9-2.3.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:856) ~[replaymod-1.8.9-2.3.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:809) ~[replaymod-1.8.9-2.3.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569) ~[replaymod-1.8.9-2.3.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:506) ~[replaymod-1.8.9-2.3.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:647) ~[replaymod-1.8.9-2.3.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) ~[replaymod-1.8.9-2.3.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) ~[replaymod-1.8.9-2.3.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) ~[replaymod-1.8.9-2.3.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[replaymod-1.8.9-2.3.0.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	... 6 more
[20:25:34] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[20:25:34] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:30)
[20:25:34] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[20:25:34] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[20:25:34] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
[20:25:34] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[20:25:34] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
</details>

**Comment by Johni0702** [comment]
This is caused by one of your other mods. Try removing as many as possible and report it to the remaining ones (there may be multiple mods required to create the right conditions for it to crash but likely only one of them is at fault).
Difficult to tell just from the log which one it is but if I'd have to take a guess, I'd go with Frames+.
