### ISSUE TITLE
Video crashes while rendering

### ISSUE THREAD

**Issue by Mentobi** [ReplayMod/ReplayMod#190]
Nearly two-hour video gets to the end of the render and it has crashed or freezes multiple times. The most recent one was my first attempt to render into MKV.  The crashes are strange. Because When I render with default everything with MP4. sometimes it crashes and sometimes it doesn't. I find if the video is longer than about 30 minutes it tends to crash more frequently.  And it's not a crash so much as it freezes in place, and I have to End task on Minecraft. When I have to do that the log files in the Appdata folder show next to nothing, but here are the logs for both the MVK (which produced a log.) and the MP4 which I cut everything except the bottom half out, as it was just me Trying to fix MVM. 

Everything except the resolution size was left at default settings. I changed the resolution from 1980 x 1080 to 16050 x 180 because that's the size it was recorded at.

Here are the logs - Attached it the log from the MP4 

note: I just noticed that Both fabric and the API has been updated recently, I'm going to update them and try it again.

(MVK Render)

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 5/22/20 10:04 PM
Description: Rendering video

java.lang.RuntimeException: GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT
	at net.minecraft.class_276.method_1239(class_276.java:146)
	at net.minecraft.class_276.method_1231(class_276.java:123)
	at net.minecraft.class_276.method_22596(class_276.java:65)
	at net.minecraft.class_276.method_1234(class_276.java:54)
	at com.replaymod.render.rendering.VideoRenderer.drawGui(VideoRenderer.java:437)
	at com.replaymod.render.rendering.VideoRenderer.updateForNextFrame(VideoRenderer.java:216)
	at com.replaymod.render.capturer.SimplePboOpenGlFrameCapturer.process(SimplePboOpenGlFrameCapturer.java:55)
	at com.replaymod.render.capturer.SimplePboOpenGlFrameCapturer.process(SimplePboOpenGlFrameCapturer.java:13)
	at com.replaymod.render.rendering.Pipeline.run(Pipeline.java:71)
	at com.replaymod.render.rendering.VideoRenderer.renderVideo(VideoRenderer.java:175)
	at com.replaymod.render.gui.GuiRenderSettings$8.run(GuiRenderSettings.java:239)
	at com.replaymod.core.ReplayMod.lambda$runLater$5(ReplayMod.java:493)
	at com.replaymod.core.ReplayMod$$Lambda$1632/235484693.run(Unknown Source)
	at net.minecraft.class_1255.method_18859(class_1255.java:173)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:135)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at com.replaymod.core.ReplayMod$ReplayModExecutor.method_5383(ReplayMod.java:472)
	at com.replaymod.replay.InputReplayTimer.method_1658(InputReplayTimer.java:72)
	at net.minecraft.class_310.method_1523(class_310.java:953)
	at net.minecraft.class_310.method_1514(class_310.java:619)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1032394656 bytes (984 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.10.1+build.306-1.15
		fabric-api-base: Fabric API Base 0.1.2+b7f9825d0c
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890c
		fabric-climbable-api-v1: Fabric Climbable API (v1) 1.0.0+6ffe71e20c
		fabric-command-api-v1: Fabric Command API (v1) 1.0.1+7b6f8bc50c
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+2e0c4ff50c
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
		fabric-dimensions-v1: fabric-dimensions-v1 0.3.0+2ad156310c
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+fac69e320c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+003643510c
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+ec40b2e10c
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d60c
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+ec951ea40c
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60c
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
		fabric-networking-v0: Fabric Networking (v0) 0.1.7+003643510c
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.0.0+796d1cc40c
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.5.0+796d1cc40c
		fabric-particles-v1: fabric-particles-v1 0.1.2+ad2f81bd0c
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.10+f08b61330c
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.23+9290e2ed0c
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600c
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed90c
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900c
		fabric-rendering-v1: Fabric Rendering (v1) 1.0.0+2a034f0a0c
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b30c
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915800c
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba70c
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.0.2+915c44630c
		fabricloader: Fabric Loader 0.8.2+build.194
		minecraft: Minecraft 1.15.2
		mm: Manningham Mills 2.0
		optifabric: Optifabric 1.0.0-beta8
		org_slf4j_slf4j-api: slf4j-api 1.7.30
		org_slf4j_slf4j-simple: slf4j-simple 1.7.30
		org_zeroturnaround_zt-zip: zt-zip 1.14
		replaymod: Replay Mod 1.15.2-2.3.0-b1
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre18
	OptiFine Build: 20200519-182630
	Render Distance Chunks: 20
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL_v7.1.05p2.zip
	OpenGlVersion: 4.6.0 NVIDIA 442.19
	OpenGlRenderer: GeForce RTX 2060/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

[2020-05-22-2.log.gz](https://github.com/ReplayMod/ReplayMod/files/4671217/2020-05-22-2.log.gz)

**Comment by Johni0702** [comment]
This has already been fixed. You're using the beta version, updated to the release.
