### ISSUE TITLE
[1.7.10] Replaymod incompatible with Resource Loader

### ISSUE THREAD

**Issue by Xanton19** [ReplayMod/ReplayMod#202]
Hi there,

I have found Replaymod to be incompatible with the Resource Loader mod, which is the case in my Modpack at least. Minecraft crashes while loading with an unexpected error and does not leave any crash-report but just shows the cause in the `latest.log` file, which seems to be related mixin that is accessing the MainMenu as seen in the crash. Any help will be appreciated and I wish you a great day.

Sincerely yours

Crash:
> [11:56:27] [main/INFO]: A re-entrant transformer 'de.pt400c.defaultsettings.core.DefaultSettingsClassTransformer' was detected and will no longer process meta class data
[11:56:27] [main/INFO]: A re-entrant transformer 'lumien.resourceloader.asm.ClassTransformer' was detected and will no longer process meta class data
[11:56:27] [main/FATAL]: Mixin prepare failed preparing GuiMainMenuAccessor in mixins.core.replaymod.json: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException Critical problem: mixins.core.replaymod.json:GuiMainMenuAccessor target net.minecraft.client.gui.GuiMainMenu was already transformed.
org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: mixins.core.replaymod.json:GuiMainMenuAccessor target net.minecraft.client.gui.GuiMainMenu was already transformed.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:885) ~[replaymod-1.7.10-2.3.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:856) ~[replaymod-1.7.10-2.3.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:809) ~[replaymod-1.7.10-2.3.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569) ~[replaymod-1.7.10-2.3.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:506) ~[replaymod-1.7.10-2.3.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:647) [replaymod-1.7.10-2.3.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) [replaymod-1.7.10-2.3.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) [replaymod-1.7.10-2.3.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) [replaymod-1.7.10-2.3.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) [replaymod-1.7.10-2.3.1.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953) [?:1.8.0_242]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:898) [?:1.8.0_242]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:881) [?:1.8.0_242]
	at java.lang.Class.forNameImpl(Native Method) [?:1.8.0_242]
	at java.lang.Class.forName(Class.java:420) [?:1.8.0_242]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[11:56:27] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.client.main.Main
	at java.lang.Class.forNameImpl(Native Method) ~[?:1.8.0_242]
	at java.lang.Class.forName(Class.java:420) ~[?:1.8.0_242]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by Johni0702** [comment]
That's a bug in Resource Loader's coremod.
It somehow caused the GuiMainMenu class to be loaded before mixin was ready for it.
Doing so is not allowed: https://github.com/MinecraftForge/MinecraftForge/blob/9274e4fe435cb415099a8216c1b42235f185443e/fml/src/main/java/cpw/mods/fml/relauncher/IFMLLoadingPlugin.java#L51-L53

**Comment by HRudyPlayZ** [comment]
Can be fixed using [https://github.com/makamys/Mixingasm](mixingasm), a recent mod made by Makamys for 1.7.10 players.
It aims to fix that kind of mixin issue.
