### ISSUE TITLE
crash on 1.12-forge loading mod list

### ISSUE THREAD

**Issue by ReinWD** [ReplayMod/ReplayMod#21]
>>---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (replaymod-1.12-2.0.1.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 10/18/17 2:08 PM
Description: Calling Gui method

java.lang.NoClassDefFoundError: net/minecraftforge/registries/RegistryManager
	at com.replaymod.core.utils.ModCompat.getInstalledNetworkMods(ModCompat.java:19)
	at com.replaymod.core.utils.ModCompat$ModInfoDifference.<init>(ModCompat.java:32)
	at com.replaymod.replay.ReplayModReplay.startReplay(ReplayModReplay.java:188)
	at com.replaymod.replay.ReplayModReplay.startReplay(ReplayModReplay.java:180)
	at com.replaymod.replay.ReplayModReplay.startReplay(ReplayModReplay.java:176)
	at com.replaymod.replay.gui.screen.GuiReplayViewer$3.run(GuiReplayViewer.java:113)
	at de.johni0702.minecraft.gui.element.AbstractGuiClickable.onClick(AbstractGuiClickable.java:71)
	at de.johni0702.minecraft.gui.element.AbstractGuiButton.onClick(AbstractGuiButton.java:98)
	at com.replaymod.replay.gui.screen.GuiReplayViewer.lambda$new$0(GuiReplayViewer.java:103)
	at de.johni0702.minecraft.gui.element.advanced.AbstractGuiResourceLoadingList.onSelectionDoubleClicked(AbstractGuiResourceLoadingList.java:158)
	at de.johni0702.minecraft.gui.element.advanced.AbstractGuiResourceLoadingList$Element.mouseClick(AbstractGuiResourceLoadingList.java:223)
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at de.johni0702.minecraft.gui.element.AbstractComposedGuiElement$3.invoke(AbstractComposedGuiElement.java:120)
	at com.sun.proxy.$Proxy38.mouseClick(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at de.johni0702.minecraft.gui.element.AbstractComposedGuiElement$3.invoke(AbstractComposedGuiElement.java:148)
	at com.sun.proxy.$Proxy38.mouseClick(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at de.johni0702.minecraft.gui.element.AbstractComposedGuiElement$3.invoke(AbstractComposedGuiElement.java:148)
	at com.sun.proxy.$Proxy38.mouseClick(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at de.johni0702.minecraft.gui.element.AbstractComposedGuiElement$3.invoke(AbstractComposedGuiElement.java:148)
	at com.sun.proxy.$Proxy38.mouseClick(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at de.johni0702.minecraft.gui.element.AbstractComposedGuiElement$3.invoke(AbstractComposedGuiElement.java:148)
	at com.sun.proxy.$Proxy38.mouseClick(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at de.johni0702.minecraft.gui.element.AbstractComposedGuiElement$2.invoke(AbstractComposedGuiElement.java:81)
	at com.sun.proxy.$Proxy38.mouseClick(Unknown Source)
	at de.johni0702.minecraft.gui.container.AbstractGuiScreen$MinecraftGuiScreen.func_73864_a(AbstractGuiScreen.java:181)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at de.johni0702.minecraft.gui.container.AbstractGuiScreen$MinecraftGuiScreen.func_146274_d(AbstractGuiScreen.java:201)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1752)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:193)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:228)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.registries.RegistryManager
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 63 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.replaymod.core.utils.ModCompat.getInstalledNetworkMods(ModCompat.java:19)
	at com.replaymod.core.utils.ModCompat$ModInfoDifference.<init>(ModCompat.java:32)
	at com.replaymod.replay.ReplayModReplay.startReplay(ReplayModReplay.java:188)
	at com.replaymod.replay.ReplayModReplay.startReplay(ReplayModReplay.java:180)
	at com.replaymod.replay.ReplayModReplay.startReplay(ReplayModReplay.java:176)
	at com.replaymod.replay.gui.screen.GuiReplayViewer$3.run(GuiReplayViewer.java:113)
	at de.johni0702.minecraft.gui.element.AbstractGuiClickable.onClick(AbstractGuiClickable.java:71)
	at de.johni0702.minecraft.gui.element.AbstractGuiButton.onClick(AbstractGuiButton.java:98)
	at com.replaymod.replay.gui.screen.GuiReplayViewer.lambda$new$0(GuiReplayViewer.java:103)
	at de.johni0702.minecraft.gui.element.advanced.AbstractGuiResourceLoadingList.onSelectionDoubleClicked(AbstractGuiResourceLoadingList.java:158)
	at de.johni0702.minecraft.gui.element.advanced.AbstractGuiResourceLoadingList$Element.mouseClick(AbstractGuiResourceLoadingList.java:223)
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)

-- Gui --
Details:
	Method: public abstract boolean de.johni0702.minecraft.gui.function.Clickable.mouseClick(org.lwjgl.util.ReadablePoint,int)
	ComposedElement: de.johni0702.minecraft.gui.element.advanced.AbstractGuiResourceLoadingList$Element@5577f4d7
	Element: de.johni0702.minecraft.gui.element.advanced.AbstractGuiResourceLoadingList$Element@5577f4d7
Stacktrace:
	at de.johni0702.minecraft.gui.element.AbstractComposedGuiElement$3.invoke(AbstractComposedGuiElement.java:120)
	at com.sun.proxy.$Proxy38.mouseClick(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)

-- Gui --
Details:
	Method: public abstract boolean de.johni0702.minecraft.gui.function.Clickable.mouseClick(org.lwjgl.util.ReadablePoint,int)
	ComposedElement: de.johni0702.minecraft.gui.element.advanced.AbstractGuiResourceLoadingList$Element@5577f4d7
	Element: de.johni0702.minecraft.gui.element.advanced.AbstractGuiResourceLoadingList$Element@5577f4d7
Stacktrace:
	at de.johni0702.minecraft.gui.element.AbstractComposedGuiElement$3.invoke(AbstractComposedGuiElement.java:148)
	at com.sun.proxy.$Proxy38.mouseClick(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)

-- Gui --
Details:
	Method: public abstract boolean de.johni0702.minecraft.gui.function.Clickable.mouseClick(org.lwjgl.util.ReadablePoint,int)
	ComposedElement: de.johni0702.minecraft.gui.container.GuiPanel@1a012645
	Element: de.johni0702.minecraft.gui.container.GuiPanel@1a012645
Stacktrace:
	at de.johni0702.minecraft.gui.element.AbstractComposedGuiElement$3.invoke(AbstractComposedGuiElement.java:148)
	at com.sun.proxy.$Proxy38.mouseClick(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)

-- Gui --
Details:
	Method: public abstract boolean de.johni0702.minecraft.gui.function.Clickable.mouseClick(org.lwjgl.util.ReadablePoint,int)
	ComposedElement: de.johni0702.minecraft.gui.container.GuiPanel@19853b58
	Element: de.johni0702.minecraft.gui.container.GuiPanel@19853b58
Stacktrace:
	at de.johni0702.minecraft.gui.element.AbstractComposedGuiElement$3.invoke(AbstractComposedGuiElement.java:148)
	at com.sun.proxy.$Proxy38.mouseClick(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)

-- Gui --
Details:
	Method: public abstract boolean de.johni0702.minecraft.gui.function.Clickable.mouseClick(org.lwjgl.util.ReadablePoint,int)
	ComposedElement: de.johni0702.minecraft.gui.element.advanced.GuiResourceLoadingList@261f902f
	Element: de.johni0702.minecraft.gui.element.advanced.GuiResourceLoadingList@261f902f
Stacktrace:
	at de.johni0702.minecraft.gui.element.AbstractComposedGuiElement$3.invoke(AbstractComposedGuiElement.java:148)
	at com.sun.proxy.$Proxy38.mouseClick(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)

-- Gui --
Details:
	Method: public abstract boolean de.johni0702.minecraft.gui.function.Clickable.mouseClick(org.lwjgl.util.ReadablePoint,int)
	ComposedElement: com.replaymod.replay.gui.screen.GuiReplayViewer@435c0d8a
	Element: com.replaymod.replay.gui.screen.GuiReplayViewer@435c0d8a
Stacktrace:
	at de.johni0702.minecraft.gui.element.AbstractComposedGuiElement$2.invoke(AbstractComposedGuiElement.java:81)
	at com.sun.proxy.$Proxy38.mouseClick(Unknown Source)
	at de.johni0702.minecraft.gui.container.AbstractGuiScreen$MinecraftGuiScreen.func_73864_a(AbstractGuiScreen.java:181)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at de.johni0702.minecraft.gui.container.AbstractGuiScreen$MinecraftGuiScreen.func_146274_d(AbstractGuiScreen.java:201)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: de.johni0702.minecraft.gui.container.AbstractGuiScreen.MinecraftGuiScreen
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1752)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:193)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:228)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 954615136 bytes (910 MB) / 1437073408 bytes (1370 MB) up to 1908932608 bytes (1820 MB)
	LiteLoader Brand: 1.12-SNAPSHOT-rAA74FDD-b3-3
	LiteLoader Mods: 4 loaded mod(s)
          - Pop Enchant Tags Revived version 1.1
          - VoxelMap version 1.6.22
          - WorldEditCUI version 1.12_00
          - Mouse Tweaks version 2.8
	LaunchWrapper: 23 active transformer(s)
          - Transformer: net.minecraftforge.fml.common.asm.transformers.PatchingTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
          - Transformer: optifine.OptiFineClassTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.BlamingTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.SideTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: renderfix.ClassTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.TerminalTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
          - Transformer: com.mumfrey.liteloader.transformers.event.EventTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.json.ModEventInjectionTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx2048m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.0.2333 Optifine OptiFine_1.12_HD_U_A1_pre 18 mods loaded, 18 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.0.2333-universal.jar) 
	UCHIJA	forge{14.21.0.2333} [Minecraft Forge] (forge-1.12-14.21.0.2333-universal.jar) 
	UCHIJA	replaymod-compat{1.12-2.0.1} [Replay Mod - Compatibility] (replaymod-1.12-2.0.1.jar) 
	UCHIJA	replaymod-replay{1.12-2.0.1} [Replay Mod - Replay] (replaymod-1.12-2.0.1.jar) 
	UCHIJA	replaymod{1.12-2.0.1} [Replay Mod] (replaymod-1.12-2.0.1.jar) 
	UCHIJA	replaymod-render{1.12-2.0.1} [Replay Mod - Render] (replaymod-1.12-2.0.1.jar) 
	UCHIJA	replaymod-editor{1.12-2.0.1} [Replay Mod - Replay Editor] (replaymod-1.12-2.0.1.jar) 
	UCHIJA	replaymod-extras{1.12-2.0.1} [Replay Mod - Extras] (replaymod-1.12-2.0.1.jar) 
	UCHIJA	replaymod-online{1.12-2.0.1} [Replay Mod - Online] (replaymod-1.12-2.0.1.jar) 
	UCHIJA	replaymod-recording{1.12-2.0.1} [Replay Mod - Recording] (replaymod-1.12-2.0.1.jar) 
	UCHIJA	replaymod-simplepathing{1.12-2.0.1} [Replay Mod - Simple Pathing] (replaymod-1.12-2.0.1.jar) 
	UCHIJA	jei{4.6.0.61} [Just Enough Items] (jei_1.12-4.6.0.61.jar) 
	UCHIJA	mousetweaks{2.8} [Mouse Tweaks] (MouseTweaks-2.8-mc1.12.jar) 
	UCHIJA	neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat-1.0.jar) 
	UCHIJA	worldedit{6.1.8-SNAPSHOT} [WorldEdit] (worldedit-forge-mc1.11.2-6.1.8-SNAPSHOT-dist.jar) 
	UCHIJA	zyinhud{1.5.5.16} [Zyin's HUD] (ZyinsHUD-1.12-1.5.5.16.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (replaymod-1.12-2.0.1.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.05' Renderer: 'GeForce GTX 1070/PCIe/SSE2'
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1070/PCIe/SSE2 GL version 4.5.0 NVIDIA 382.05, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz

it seems that a null value is called during com.replaymod.core.utils.ModCompat.getInstalledNetworkMods(ModCompat.java:19)
maybe it's net.minecraftforge.registries.RegistryManager not correctly imported.
But my minecraft client is installed with forge-1.12-14.21.0.2333.
Maybe it's not a common issue.

**Comment by Johni0702** [comment]
Update Forge, the version you're using is one of the first 1.12 builds (even before the first recommended build) and is way too old.
