### ISSUE TITLE
Jumping backwards can randomly cause a NPE

### ISSUE THREAD

**Issue by Johni0702** [ReplayMod/ReplayMod#227]
RM 1.12.2-2.3.1 on Enigmatica 2 modpack
```
java.lang.NullPointerException: Calling Gui method
    at com.replaymod.replay.ReplayHandler.doJump(ReplayHandler.java:689)
    at com.replaymod.replay.gui.overlay.GuiReplayOverlay$7.run(GuiReplayOverlay.java:131)
    at com.replaymod.lib.de.johni0702.minecraft.gui.element.advanced.AbstractGuiTimeline.onClick(AbstractGuiTimeline.java:197)
```
https://discordapp.com/channels/708304818829262910/709108200632483900/722763712993427478

**Comment by FourInchKnife** [comment]
For me this only happens when I go to 0:00 on the timeline while not in quick mode

**Comment by FourInchKnife** [comment]
I can recreate this in 1.16.3 with optifabric, optifine, and RM installed. I don't think it has to do with the number of mods.

**Comment by chopin2712** [comment]
I have the same issue, no other mod than the API of fabric.
