### ISSUE TITLE
using Exit Replay button causes java.lang.NullPointerException at com.replaymod.replay.handler.GuiHandler.onButton(GuiHandler.java:144)

### ISSUE THREAD

**Issue by TheSnoozer** [ReplayMod/ReplayMod#24]
``replaymod-1.8-2.1.0.jar``
``1.8-forge1.8-11.14.4.1577``

clicking on using Exit Replay after watching a replay causes
```
java.lang.NullPointerException
	at com.replaymod.replay.handler.GuiHandler.onButton(GuiHandler.java:144) ~[GuiHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_47_GuiHandler_onButton_Pre.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:468) ~[bxf.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548) ~[bxf.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517) ~[bxf.class:?]
	at com.replaymod.replay.InputReplayTimer.func_74275_a(InputReplayTimer.java:49) ~[InputReplayTimer.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1008) ~[bsu.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345) [bsu.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:120) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
```

**Comment by Johni0702** [comment]
This is a [known issue](https://www.replaymod.com/forum/thread/2009).
Please use the forum for bug reports because that's where everyone will be looking to see if some bug has already been reported.
