### ISSUE TITLE
crashing while rendering!

### ISSUE THREAD

**Issue by ghost** [ReplayMod/ReplayMod#462]
hi! i have this problem that when I try to render it loads for 1 seconds and then crashes!

here's the issue report: 

---- Minecraft Crash Report ----
// Why did you do that?

Time: 19/01/21 1:52 PM
Description: Exporting video

com.replaymod.render.FFmpegWriter$FFmpegStartupException
	at com.replaymod.render.FFmpegWriter.getVideoFile(FFmpegWriter.java:158)
	at com.replaymod.render.FFmpegWriter.consume(FFmpegWriter.java:121)
	at com.replaymod.render.rendering.VideoRenderer$1.consume(VideoRenderer.java:145)
	at com.replaymod.render.rendering.Pipeline$ProcessTask.run(Pipeline.java:142)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.replaymod.render.gui.GuiExportFailed.tryToRecover(GuiExportFailed.java:35)

-- Export details --
Details:
	Settings: com.replaymod.render.RenderSettings@4178ef21
	FFmpeg log: ffmpeg version 4.3.1-2021-01-01-essentials_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rawvideo, from 'pipe:':
  Duration: N/A, start: 0.000000, bitrate: 10368 kb/s
    Stream #0:0: Video: rawvideo (BGRA / 0x41524742), bgra, 180x180, 10368 kb/s, 10 tbr, 10 tbn, 10 tbc
document.mp3.mp4: Permission denied

Stacktrace:
	at com.replaymod.render.gui.GuiExportFailed.tryToRecover(GuiExportFailed.java:35)
	at com.replaymod.render.gui.GuiRenderSettings$7.run(GuiRenderSettings.java:273)
	at com.replaymod.core.ReplayMod.lambda$runLater$6(ReplayMod.java:613)
	at com.replaymod.core.ReplayMod$$Lambda$2386/1120466008.run(Unknown Source)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)
	at net.minecraft.class_1255.method_5383(class_1255.java:103)
	at com.replaymod.core.ReplayMod$ReplayModExecutor.method_5383(ReplayMod.java:575)
	at com.replaymod.replay.InputReplayTimer.method_1658(InputReplayTimer.java:81)
	at net.minecraft.class_310.method_1523(class_310.java:1012)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1441667864 bytes (1374 MB) / 2080374784 bytes (1984 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

**Comment by RaderRMT** [comment]
Try removing the `.mp3` in the file name and try rendering in an other folder (preferably the default folder)

**Comment by bl4stnight** [comment]
> Try removing the `.mp3` in the file name and try rendering in an other folder (preferably the default folder)

how do I render it in a different folder?

**Comment by Normolo** [comment]
Same problem for me,

> > Try removing the `.mp3` in the file name and try rendering in an other folder (preferably the default folder)
> 
> how do I render it in a different folder?
I don't know either.

**Comment by samxiaoLOL** [comment]
Same problum,I have tried it for many times without other mods.But different issue report:
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by samxiaoLOL** [comment]
Same problum,I have tried it for many times without other mods.But different issue report:
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by Normolo** [comment]
Might want to create another issue then @samxiaoLOL

**Comment by Gamendeberen1** [comment]
Same issue, its so anoying...

**Comment by Johni0702** [comment]
Same issue, same solution. If the same solution doesn't work for you, you don't have the same issue. Open a separate issue then.
