### ISSUE TITLE
IllegalReferenceCountException during replay save

### ISSUE THREAD

**Issue by justinmok** [ReplayMod/ReplayMod#492]
Save progress is stuck at 84%. Stack trace is different from #121 
[raw replay file](https://we.tl/t-PQBawTYADC)

```
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2021-03-08 14:14:08 PST
Description: Saving replay file

io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
    at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.3)
    at io.netty.buffer.AbstractReferenceCountedByteBuf.release0(AbstractReferenceCountedByteBuf.java:100)
    at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:84)
    at com.replaymod.replaystudio.io.ReplayOutputStream.doWrite(ReplayOutputStream.java:166)
    at com.replaymod.replaystudio.io.ReplayOutputStream.write(ReplayOutputStream.java:146)
    at com.replaymod.editor.gui.MarkerProcessor.apply(MarkerProcessor.java:193)
    at com.replaymod.recording.packet.PacketListener.lambda$channelInactive$6(PacketListener.java:296)
    at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.16.5
  Minecraft Version ID: 1.16.5
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 14.0.2, AdoptOpenJDK
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK
  Memory: 619179432 bytes (590 MB) / 3670016000 bytes (3500 MB) up to 3670016000 bytes (3500 MB)
  CPUs: 8
  JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2988m -Xmx3500m
  Suspected Mods: Replay Mod (replaymod)
  Fabric Mods: amecsapi: Amecs API 1.1.3+mc1.16.5
               antighost: AntiGhost 1.16.4-fabric0.25.1-1.1.3
               architectury: Architectury 1.3.88
               artifice: Artifice 0.13.1+1.16.2-rc1
               autoconfig1u: Auto Config v1 Updated 3.3.1
               blur: Blur (Fabric) 2.1.0
               capes: Capes 1.1.1
               chesttracker: Chest Tracker 0.8.5
               cloth-basic-math: Cloth Basic Math 0.5.1
               cloth-client-events-v0: Cloth Client Events v0 1.5.47
               cloth-config2: Cloth Config v4 4.11.14
               colormatic: Colormatic 2.2.8+mc.1.16.3
               com_moandjiezana_toml_toml4j: toml4j 0.7.2
               cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
               craftpresence: CraftPresence 1.7.6
               crowdin-translate: CrowdinTranslate 1.2
               cullleaves: Cull Leaves 2.0.0
               custom-fog: Custom Fog 1.4.0
               dynamicfps: Dynamic FPS 2.0.1
               fabric: Fabric API 0.31.0+1.16
               fabric-api-base: Fabric API Base 0.2.1+9354966b7d
               fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
               fabric-command-api-v1: Fabric Command API (v1) 1.1.0+f9b3753b7d
               fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
               fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
               fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
               fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
               fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
               fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
               fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
               fabric-language-kotlin: Fabric Language Kotlin 1.4.21+build.1
               fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
               fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
               fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
               fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
               fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
               fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
               fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
               fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
               fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
               fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
               fabricloader: Fabric Loader 0.11.2
               fabrishot: Fabrishot 1.2.3.1
               fallingtree: FallingTree 2.10.2
               fastchest: FastChest 1.0
               fiber: fiber 0.23.0-2
               iamverysmart: I Am Very Smart 2.1.0+mc1.16.1
               illuminations: Illuminations 1.4.5
               itemscroller: Item Scroller 0.15.0-dev.20210111.205029
               jankson: Jankson 3.0.1+j1.2.0
               java: OpenJDK 64-Bit Server VM 14
               lambdynlights: LambDynamicLights 1.3.4+1.16
               leaf-decay: Leaf Decay 1.2.0-1.16.1
               libgui: LibGui 3.3.5+1.16.5
               litematica: Litematica 0.0.0-dev.20210120.213004
               lithium: Lithium 0.6.1
               loadcatcher: Entrypoint Catcher 2.0.0
               malilib: MaLiLib 0.10.0-dev.21+arne.2
               mambience: MAmbience 3.0.0+1.16.5
               minecraft: Minecraft 1.16.5
               minihud: MiniHUD 0.19.0-dev.20201103.184029
               mm: Manningham Mills 2.1
               modmenu: Mod Menu 1.16.8
               mousewheelie: Mouse Wheelie 1.6.4+mc1.16.4
               notenoughcrashes: Not Enough Crashes 2.1.4+1.16.1
               okzoomer: Ok Zoomer 4.0.1+1.16.2
               org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
               org_codehaus_groovy_groovy: groovy 3.0.3
               org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
               org_jetbrains_annotations: annotations 20.0.0
               org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.21
               org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.21
               org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.21
               org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.21
               org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
               org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
               phosphor: Phosphor 0.7.1+build.11
               raisedclouds: Raised Clouds 1.0.0
               randomblockplacement: RandomBlockPlacement 1.16.5-fabric0.30.0-1.1.1
               replaymod: Replay Mod 1.16.4-2.5.2
               satin: Satin 1.5.1
               seamless_loading_screen: Seamless Loading Screen 1.3.1
               slight-gui-modifications: 'Slight' GUI Modifications 1.6.1
               smoothscrollingeverywhere: Smooth Scrolling Everywhere 3.0.3-unstable
               sodium: Sodium 0.1.0
               spruceui: SpruceUI 2.0.4+1.16
               tweed: Tweed API 3.0.0-beta.22
               vanguard: Vanguard 1.0.5
               whereisit: Where Is It 1.11.6
               xaerominimap: Xaero's Minimap 21.4.1
               xaeroworldmap: Xaero's World Map 1.12.1
```

**Comment by Johni0702** [comment]
Another raw replay file, cause above has expired: https://cdn.discordapp.com/attachments/709108200632483900/830031018425188352/bartering_farm_1.mcpr
Corresponding crash report: https://cdn.discordapp.com/attachments/709108200632483900/830027832582340608/crash_.txt
