### ISSUE TITLE
Crash while rendering with 1 device not closed

### ISSUE THREAD

**Issue by samxiaoLOL** [ReplayMod/ReplayMod#507]
Hi,I have this problem when I am rendering.
I have tried to render in different folder,and remove .mp3 in file name.
the total game crashed after render load for 1sec.
My graphics:Intel UHD Graphics on i5-10210U progresser
using larcher:HMCL

heres the issue report:
---- Minecraft Crash Report ----
// My bad.

Time: 21-4-12 下午7:37
Description: Exporting video

com.replaymod.render.FFmpegWriter$FFmpegStartupException
	at com.replaymod.render.FFmpegWriter.getVideoFile(FFmpegWriter.java:158)
	at com.replaymod.render.FFmpegWriter.consume(FFmpegWriter.java:121)
	at com.replaymod.render.rendering.VideoRenderer$1.consume(VideoRenderer.java:145)
	at com.replaymod.render.rendering.Pipeline$ProcessTask.run(Pipeline.java:142)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.replaymod.render.gui.GuiExportFailed.tryToRecover(GuiExportFailed.java:35)

-- Export details --
Details:
	Settings: com.replaymod.render.RenderSettings@704d01a8
	FFmpeg log: FFmpeg version SVN-r18639, Copyright (c) 2000-2009 Fabrice Bellard, et al.
  configuration: --enable-memalign-hack --enable-postproc --enable-gpl --enable-libfaac --enable-libfaad --enable-libgsm --enable-libmp3lame --enable-libvorbis --enable-libtheora --enable-libx264 --enable-libxvid --disable-ffserver --enable-avisynth --enable-pthreads
  libavutil     50. 3. 0 / 50. 3. 0
  libavcodec    52.27. 0 / 52.27. 0
  libavformat   52.32. 0 / 52.32. 0
  libavdevice   52. 2. 0 / 52. 2. 0
  libswscale     0. 7. 1 /  0. 7. 1
  libpostproc   51. 2. 0 / 51. 2. 0
  built on Apr 21 2009 13:44:38, gcc: 4.2.4 (TDM-1 for MinGW)
Input #0, rawvideo, from 'pipe:':
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0.0: Video: rawvideo, bgra, 1920x1080, 30 tbr, 30 tbn, 30 tbc
C:\Users\admin\Desktop\爱好\hmcl\.minecraft\ffmpeg\ffmpeg.exe: unrecognized option '-c:v'

Stacktrace:
	at com.replaymod.render.gui.GuiExportFailed.tryToRecover(GuiExportFailed.java:35)
	at com.replaymod.render.gui.GuiRenderQueue.processQueue(GuiRenderQueue.java:188)
	at com.replaymod.render.gui.GuiRenderQueue.lambda$null$3(GuiRenderQueue.java:154)
	at com.replaymod.core.ReplayMod.lambda$runLater$6(ReplayMod.java:613)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)
	at net.minecraft.class_1255.method_5383(class_1255.java:103)
	at com.replaymod.core.ReplayMod$ReplayModExecutor.method_5383(ReplayMod.java:575)
	at com.replaymod.replay.InputReplayTimer.method_1658(InputReplayTimer.java:81)
	at net.minecraft.class_310.method_1523(class_310.java:987)
	at net.minecraft.class_310.method_1514(class_310.java:656)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_281, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3482349672 bytes (3321 MB) / 4194304000 bytes (4000 MB) up to 4194304000 bytes (4000 MB)
	CPUs: 8
	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx4000m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\admin\Desktop\爱好\hmcl\.minecraft\crash-reports\crash-2021-04-12_19.37.21-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by Johni0702** [comment]
You are using an ancient version of ffmpeg (from 2009). https://www.replaymod.com/docs/#installing-ffmpeg-windows
Albeit not the immediate cause of your issue, you're also using an old ReplayMod version.
