### ISSUE TITLE
Game crashes before startup

### ISSUE THREAD

**Issue by feoranis26** [ReplayMod/ReplayMod#511]
```
[15:48:18] [main/INFO]: Loading tweak class name com.replaymod.core.tweaker.ReplayModTweaker
[15:48:18] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoSuchFieldError: INIT
[15:48:18] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.replaymod.core.tweaker.ReplayModTweaker.injectMixinTweaker(ReplayModTweaker.java:44)
[15:48:18] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.replaymod.core.tweaker.ReplayModTweaker.<init>(ReplayModTweaker.java:31)
[15:48:18] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[15:48:18] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[15:48:18] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[15:48:18] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[15:48:18] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Class.newInstance(Class.java:442)
[15:48:18] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
[15:48:18] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Java 1.8.0_291
ReplayMod 1.12.2-2.5.2

**Comment by RaderRMT** [comment]
there's nothing we can do without the log file... that's why i asked for it in your previous issue...

**Comment by feoranis26** [comment]
I am posting the log, internet is really bad so it takes a while to upload.

**Comment by feoranis26** [comment]
[2021-04-24-7.log](https://github.com/ReplayMod/ReplayMod/files/6369651/2021-04-24-7.log)

**Comment by RaderRMT** [comment]
answered in #510. this one can be closed because it's a known issue.
