### ISSUE TITLE
"Found a duplicate mod" issue in 1.12.2 and it doesn't work by updating forge

### ISSUE THREAD

**Issue by ShockedCoder** [ReplayMod/ReplayMod#539]
```
[16:21:08] [Server thread/FATAL] [FML]: Found a duplicate mod replaymod-restrictions at [/MCservers/IsekaiTechnologies/./mods/replaymod-1.12.2-2.5.2.jar, ./mods/replaymod-1.12.2-2.5.2.jar]
[16:21:08] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.common.DuplicateModsFoundException: 
Duplicate Mods:
	replaymod-restrictions : /MCservers/IsekaiTechnologies/./mods/replaymod-1.12.2-2.5.2.jar
	replaymod-restrictions : /MCservers/IsekaiTechnologies/./mods/replaymod-1.12.2-2.5.2.jar


	at net.minecraftforge.fml.common.Loader.identifyDuplicates(Loader.java:466) ~[Loader.class:?]
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:428) ~[Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568) ~[Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) ~[FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
[16:21:08] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /MCservers/IsekaiTechnologies/./crash-reports/crash-2021-07-04_16.21.08-server.txt

```

There was [no duplicate](https://i.imgur.com/WfYWmrb.png).
If it's of any importance, [here are my specs](https://i.imgur.com/OU1tn3A.png).

I looked up [an issue](https://github.com/ReplayMod/ReplayMod/issues/39#issuecomment-455318364) that said updating to 2655 forge fixed it, but you see. Most of my mods need 2854 or newer version of forge.

And since I'm new to this type of problem, I'm not sure what I should do to get rid of this error.

**Comment by RaderRMT** [comment]
the replaymod is not a server-side mod.

**Comment by ShockedCoder** [comment]
Well damn, that's my bad then.

**Comment by nickiteushan** [comment]
It happened to me recently while using GDLauncher as client-side problem. You can 'fix it' by changing **Minecraft Startup Method** to **Symlink** in **Java** settings of GDLauncher.
![Screenshot 2022-03-26 143326](https://user-images.githubusercontent.com/74980009/160239780-9143379b-cc2f-4910-ad7a-f823abb1e22d.png)
.
