### ISSUE TITLE
Preventing Construct's Armory from opening GUI

### ISSUE THREAD

**Issue by SillySnowFox** [ReplayMod/ReplayMod#561]
Something in the newest version is stopping Construct's Armory from opening it's GUI for the Armor Station and Armor Forge. The rest of Tinker's (and all other custom GUI machines) work fine.

**Comment by Johni0702** [comment]
```
Caused by: java.lang.NullPointerException
	at c4.conarm.client.gui.PreviewPlayer.func_175155_b(PreviewPlayer.java:72) ~[PreviewPlayer.class:?]
	at net.minecraft.client.entity.AbstractClientPlayer.handler$zce000$forceCachePlayerListEntry(AbstractClientPlayer.java:528) ~[bua.class:?]
	at net.minecraft.client.entity.AbstractClientPlayer.<init>(AbstractClientPlayer.java:35) ~[bua.class:?]
	at c4.conarm.client.gui.PreviewPlayer.<init>(PreviewPlayer.java:48) ~[PreviewPlayer.class:?]
	at c4.conarm.client.gui.GuiArmorStation.<init>(GuiArmorStation.java:129) ~[GuiArmorStation.class:?]
	at c4.conarm.client.gui.GuiArmorForge.<init>(GuiArmorForge.java:30) ~[GuiArmorForge.class:?]
	at c4.conarm.common.tileentities.TileArmorForge.createGui(TileArmorForge.java:41) ~[TileArmorForge.class:?]
	at slimeknights.mantle.common.GuiHandler.getClientGuiElement(GuiHandler.java:27) ~[GuiHandler.class:?]
	at net.minecraftforge.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:276) ~[NetworkRegistry.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:111) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550) ~[aed.class:?]
	at net.minecraftforge.fml.common.network.internal.OpenGuiHandler.process(OpenGuiHandler.java:50) ~[OpenGuiHandler.class:?]
	at net.minecraftforge.fml.common.network.internal.OpenGuiHandler.lambda$channelRead0$0(OpenGuiHandler.java:43) ~[OpenGuiHandler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_292]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_292]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 17 more
```
