### ISSUE TITLE
Game crashes with latest replay mod release on 1.12.2

### ISSUE THREAD

**Issue by 0-x-2-2** [ReplayMod/ReplayMod#622]
Workarounds that can be applied by the user:
Use "-noverify", this one is worse because it disables security features and causes type safety-related bugs that don't exist with the verifier that causes crashes and undefined behavior with some mods.
Delete the "javax.annotation" package from the jar file. (The best solution that works)

This was probably caused by accidentally including these in the jar to support newer versions of Java.

Linux (me):
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CorePlugin (SmoothFont-mc1.12.2-2.1.2.jar)
  Controllable (controllable-0.8.0-mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 12/12/21 11:11 AM
Description: Initializing game

com.google.common.util.concurrent.UncheckedExecutionException: java.lang.SecurityException: class "javax.annotation.Nullable"'s signer information does not match signer information of other classes in the same package
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at com.google.common.eventbus.SubscriberRegistry.getAnnotatedMethods(SubscriberRegistry.java:178)
	at com.google.common.eventbus.SubscriberRegistry.findAllSubscribers(SubscriberRegistry.java:169)
	at com.google.common.eventbus.SubscriberRegistry.register(SubscriberRegistry.java:77)
	at com.google.common.eventbus.EventBus.register(EventBus.java:191)
	at net.minecraftforge.fml.common.LoadController.<init>(LoadController.java:85)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:566)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.SecurityException: class "javax.annotation.Nullable"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:895)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.annotation.AnnotationParser.parseSig(AnnotationParser.java:439)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:241)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.reflect.Executable.declaredAnnotations(Executable.java:599)
	at java.lang.reflect.Executable.declaredAnnotations(Executable.java:597)
	at java.lang.reflect.Executable.getAnnotation(Executable.java:570)
	at java.lang.reflect.Method.getAnnotation(Method.java:622)
	at java.lang.reflect.AnnotatedElement.isAnnotationPresent(AnnotatedElement.java:258)
	at java.lang.reflect.AccessibleObject.isAnnotationPresent(AccessibleObject.java:191)
	at com.google.common.eventbus.SubscriberRegistry.getAnnotatedMethodsNotCached(SubscriberRegistry.java:186)
	at com.google.common.eventbus.SubscriberRegistry.access$000(SubscriberRegistry.java:53)
	at com.google.common.eventbus.SubscriberRegistry$1.load(SubscriberRegistry.java:159)
	at com.google.common.eventbus.SubscriberRegistry$1.load(SubscriberRegistry.java:156)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	... 20 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)

-- World Downloader Mod - not bootstrapped yet --
Details:
	WDL version: 4.1.1.0
	Targeted MC version: 1.12.2
	Actual MC version: 1.12.2
Stacktrace:
	at java.lang.Thread.getStackTrace(Thread.java:1552)
	at net.minecraft.crash.CrashReportCategory.func_85073_a(CrashReportCategory.java:116)
	at net.minecraft.crash.CrashReport.func_85057_a(CrashReport.java:351)
	at wdl.WDLHooks$BootstrapHooksListener.onCrashReportPopulateEnvironment(WDLHooks.java:147)
	at wdl.WDLHooks.onCrashReportPopulateEnvironment(WDLHooks.java:250)
	at net.minecraft.crash.CrashReport.handler$zcp000$onCrashReportPopulateEnvironment(CrashReport.java:532)
	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:144)
	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:54)
	at net.minecraft.crash.CrashReport.func_85055_a(CrashReport.java:424)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:382)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- Initialization --
Details:

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 5.15.0-1-amd64
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 403243520 bytes (384 MB) / 805306368 bytes (768 MB) up to 2147483648 bytes (2048 MB)
	LiteLoader Brand: LiteLoader startup incomplete
	LiteLoader Mods: LiteLoader startup incomplete
```

Windows:
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (replaymod-1.12.2-2.2.0-b7.jar)
  OpenEyePlugin (OpenEye.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 12/13/21 1:14 AM
Description: Initializing game

com.google.common.util.concurrent.UncheckedExecutionException: java.lang.SecurityException: class "javax.annotation.Nullable"'s signer information does not match signer information of other classes in the same package
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at com.google.common.eventbus.SubscriberRegistry.getAnnotatedMethods(SubscriberRegistry.java:178)
	at com.google.common.eventbus.SubscriberRegistry.findAllSubscribers(SubscriberRegistry.java:169)
	at com.google.common.eventbus.SubscriberRegistry.register(SubscriberRegistry.java:77)
	at com.google.common.eventbus.EventBus.register(EventBus.java:191)
	at net.minecraftforge.fml.common.LoadController.<init>(LoadController.java:86)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:541)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:227)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.SecurityException: class "javax.annotation.Nullable"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:895)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.annotation.AnnotationParser.parseSig(AnnotationParser.java:439)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:241)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.reflect.Executable.declaredAnnotations(Executable.java:602)
	at java.lang.reflect.Executable.declaredAnnotations(Executable.java:600)
	at java.lang.reflect.Executable.getAnnotation(Executable.java:572)
	at java.lang.reflect.Method.getAnnotation(Method.java:621)
	at java.lang.reflect.AnnotatedElement.isAnnotationPresent(AnnotatedElement.java:258)
	at java.lang.reflect.AccessibleObject.isAnnotationPresent(AccessibleObject.java:191)
	at com.google.common.eventbus.SubscriberRegistry.getAnnotatedMethodsNotCached(SubscriberRegistry.java:186)
	at com.google.common.eventbus.SubscriberRegistry.access$000(SubscriberRegistry.java:53)
	at com.google.common.eventbus.SubscriberRegistry$1.load(SubscriberRegistry.java:159)
	at com.google.common.eventbus.SubscriberRegistry$1.load(SubscriberRegistry.java:156)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	... 20 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at com.google.common.eventbus.SubscriberRegistry.getAnnotatedMethods(SubscriberRegistry.java:178)
	at com.google.common.eventbus.SubscriberRegistry.findAllSubscribers(SubscriberRegistry.java:169)
	at com.google.common.eventbus.SubscriberRegistry.register(SubscriberRegistry.java:77)
	at com.google.common.eventbus.EventBus.register(EventBus.java:191)
	at net.minecraftforge.fml.common.LoadController.<init>(LoadController.java:86)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:541)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:227)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 358345424 bytes (341 MB) / 637534208 bytes (608 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
LoadingPlugin (replaymod-1.12.2-2.2.0-b7.jar)
```

**Comment by Johni0702** [comment]
> replaymod-1.12.2-2.2.0-b7.jar

That's not the latest release. Not by a long shot.
And I just re-tested the latest release (2.6.3) as well as the ancient version you're using and they both launche fine for me.

I also see nothing in these crash report which would suggest anything related to the Java version. I'm guessing one of your other mods includes those classes as well (cause they're frequently used) but made the mistake to sign them, thereby preventing everyone else from including more up-to-date or just more classes in general in the same package.

**Comment by 0-x-2-2** [comment]
> > replaymod-1.12.2-2.2.0-b7.jar
> 
> That's not the latest release. Not by a long shot. And I just re-tested the latest release (2.6.3) as well as the ancient version you're using and they both launch fine for me.
> 
> I also see nothing in these crash reports which would suggest anything related to the Java version. I'm guessing one of your other mods includes those classes as well (cause they're frequently used) but made the mistake of signing them, thereby preventing everyone else from including more up-to-date or just more classes in general from the same package.

I have the same crash with `replaymod-1.12.2-2.6.3.jar`

**Comment by 0-x-2-2** [comment]
The issue was solved by using a newer version of Java.
