### ISSUE TITLE
Crash when trying to rename a new recording via the prompt

### ISSUE THREAD

**Issue by JasonHorkles** [ReplayMod/ReplayMod#635]
If the rename dialog option is on and a recording is completed, attempting to rename the file causes the game to crash

```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 12/27/21, 11:14 PM
Description: charTyped event handler

java.lang.NullPointerException: Cannot invoke "org.spongepowered.asm.mixin.injection.callback.CallbackInfo.cancel()" because "ci" is null
	at net.minecraft.class_309.handler$zlj000$charTyped(class_309.java:1629)
	at net.minecraft.class_309.handler$zlj000$charTyped(class_309.java:3102)
	at net.minecraft.class_309.method_1458(class_309.java)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_309.method_1457(class_309.java:656)
	at net.minecraft.class_309.method_22677(class_309.java:720)
	at net.minecraft.class_1255.execute(class_1255.java:118)
	at net.minecraft.class_309.method_22675(class_309.java:719)
	at org.lwjgl.glfw.GLFWCharModsCallbackI.callback(GLFWCharModsCallbackI.java:39)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:223)
	at net.minecraft.class_310.method_1523(class_310.java:1145)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_309.handler$zlj000$charTyped(class_309.java:1629)
	at net.minecraft.class_309.handler$zlj000$charTyped(class_309.java:3102)
	at net.minecraft.class_309.method_1458(class_309.java)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_309.method_1457(class_309.java:656)
	at net.minecraft.class_309.method_22677(class_309.java:720)
	at net.minecraft.class_1255.execute(class_1255.java:118)
	at net.minecraft.class_309.method_22675(class_309.java:719)
	at org.lwjgl.glfw.GLFWCharModsCallbackI.callback(GLFWCharModsCallbackI.java:39)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_500
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_309.method_1457(class_309.java:656)
	at net.minecraft.class_309.method_22677(class_309.java:720)
	at net.minecraft.class_1255.execute(class_1255.java:118)
	at net.minecraft.class_309.method_22675(class_309.java:719)
	at org.lwjgl.glfw.GLFWCharModsCallbackI.callback(GLFWCharModsCallbackI.java:39)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:223)
	at net.minecraft.class_310.method_1523(class_310.java:1145)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, VanillaTweaks.zip, Fabric Mods, replaymod_lang
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2409)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1015887152 bytes (968 MiB) / 2013265920 bytes (1920 MiB) up to 5368709120 bytes (5120 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-11700F @ 2.50GHz
	Identifier: Intel64 Family 6 Model 167 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2486
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9729
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.13
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 2.13
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 47157.82
	Virtual memory used (MB): 35056.94
	Swap memory total (MB): 14502.90
	Swap memory used (MB): 88.26
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		axolotlitemfix: Axolotl Item Fix 1.1.3
		betterf3: BetterF3 1.2.2
		clickthrough: ClickThrough 1.18-fabric0.43.1-0.4
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.1.48
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		craftpresence: CraftPresence 1.8.8
		crowdin-translate: CrowdinTranslate 1.4+1.18
		durabilityviewer: Giselbaers Durability Viewer 1.18-fabric0.43.1-1.10.2
		dynamicfps: Dynamic FPS 2.0.6
		fabric: Fabric API 0.45.0+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cd65
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+17be577f65
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a965
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d9565
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c665
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73d65
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d2957165
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378a65
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f1765
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cd65
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d9565
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f365
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cd65
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca33565
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d9565
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d9565
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d9565
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d9565
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+3b82842e65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+3ac43d9565
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1ac65
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.6+533be9ba65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d9565
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d9565
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d765
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378a65
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9514
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d9565
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d9565
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a765
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d9565
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f5565
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.6+b4f4f6cd65
		fabricloader: Fabric Loader 0.12.12
		gbfabrictools: GBfabrictools 1.3.4+1.18
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.18.1
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 3.0.1
		optifabric: OptiFabric 1.12.10
		physicsmod: Physics Mod 2.6.1
		replaymod: Replay Mod 1.18.1-2.6.3
		smoothboot: Smooth Boot 1.18-1.7.0
		sound_physics_remastered: Sound Physics Remastered 1.18.1-1.0.3
		voicechat: Simple Voice Chat 1.18.1-2.1.28
	Launched Version: fabric-loader-0.12.12-1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 497.29, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/VanillaTweaks.zip, Fabric Mods
	Current Language: English (US)
	CPU: 16x 11th Gen Intel(R) Core(TM) i7-11700F @ 2.50GHz
	OptiFine Version: OptiFine_1.18.1_HD_U_H4
	OptiFine Build: 20211212-175054
	Render Distance Chunks: 22
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 NVIDIA 497.29
	OpenGlRenderer: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.18.1
	OptiFine jar version: OptiFine_1.18.1_HD_U_H4
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:/Users/jason/AppData/Roaming/.minecraft/.optifine/OptiFine_1.18.1_HD_U_H4/Optifine-mapped.jar
	OptiFabric error: <None>
```

**Comment by Johni0702** [comment]
That looks like an issue with OptiFabric. Please report it over there: https://github.com/Chocohead/OptiFabric/issues
