### ISSUE TITLE
EOFException when using start/stop/pause

### ISSUE THREAD

**Issue by Kepler-17c** [ReplayMod/ReplayMod#668]
Reported by user Tizo#5051 - tested and confirmed in 1.18.1 with RM 2.6.3

Auto-recording works without issue, but "manual recording" causes an EOFException when disconnecting from the server.

Tested on/with `survive.ga`

Crash-report:
[crash-2022-01-25_01.53.54-client.txt](https://github.com/ReplayMod/ReplayMod/files/7929882/crash-2022-01-25_01.53.54-client.txt)

**Comment by Johni0702** [comment]
Could you please attach the corresponding raw file?

**Comment by Kepler-17c** [comment]
Sure, here it is:
I've just renamed the ending, because GitHub only accepts zips when they're named like it.
[2022_01_25_01_53_19.mcpr.zip](https://github.com/ReplayMod/ReplayMod/files/7936621/2022_01_25_01_53_19.mcpr.zip)

Markers match what I did:
- disable auto-recording and join
- start recording
- stop recording
- leave

I also tried to re-apply the markers via edit and get the same exception.

**Comment by Johni0702** [comment]
Looks like the server is intentionally send invalid chunk packets. Vanilla chokes on them as well, just not fatally (but I'd rather not just catch-ignore-all cause that'll obfuscate legitimate implementation errors):
```
[14:19:09] [Render thread/INFO] (Minecraft) [CHAT] [Server] Überprüfung wurde gestartet, bitte warte und bewege dich nicht...
[14:19:09] [Render thread/FATAL] (Minecraft) Error executing task on Client
 java.lang.IndexOutOfBoundsException: null
	at io.netty.buffer.EmptyByteBuf.readShort(EmptyByteBuf.java:533) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at net.minecraft.network.PacketByteBuf.readShort(PacketByteBuf.java:1023) ~[minecraft-mapped.jar:?]
	at net.minecraft.world.chunk.ChunkSection.fromPacket(ChunkSection.java:156) ~[minecraft-mapped.jar:?]
	at net.minecraft.world.chunk.WorldChunk.loadFromPacket(WorldChunk.java:445) ~[minecraft-mapped.jar:?]
	at net.minecraft.client.world.ClientChunkManager.loadChunkFromPacket(ClientChunkManager.java:101) ~[minecraft-mapped.jar:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.loadChunk(ClientPlayNetworkHandler.java:665) ~[minecraft-mapped.jar:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.onChunkData(ClientPlayNetworkHandler.java:660) ~[minecraft-mapped.jar:?]
	at net.minecraft.network.packet.s2c.play.ChunkDataS2CPacket.apply(ChunkDataS2CPacket.java:45) ~[minecraft-mapped.jar:?]
	at net.minecraft.network.packet.s2c.play.ChunkDataS2CPacket.apply(ChunkDataS2CPacket.java:12) ~[minecraft-mapped.jar:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils.java:21) ~[minecraft-mapped.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:151) [minecraft-mapped.jar:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23) [minecraft-mapped.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:125) [minecraft-mapped.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:110) [minecraft-mapped.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1080) [minecraft-mapped.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:733) [minecraft-mapped.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:238) [minecraft-mapped.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568) [fabric-loader-0.12.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.12.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.5.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
[14:19:09] [Render thread/INFO] (Minecraft) [CHAT] [Server] Überprüfung erfolgreich bestanden.
```
