### ISSUE TITLE
Replay mod wont save video's from our server.

### ISSUE THREAD

**Issue by Bantoo1231** [ReplayMod/ReplayMod#69]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  LoadingPlugin (zreplaymod-1.12.2-2.2.0-b7 (1).jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 7/30/19 3:08 PM
Description: Saving replay file

java.io.IOException: decoding
	at com.replaymod.replaystudio.io.ReplayInputStream.fillBuffer(ReplayInputStream.java:233)
	at com.replaymod.replaystudio.io.ReplayInputStream.readPacket(ReplayInputStream.java:184)
	at com.replaymod.editor.gui.MarkerProcessor.apply(MarkerProcessor.java:146)
	at com.replaymod.recording.packet.PacketListener.lambda$channelInactive$8(PacketListener.java:225)
	at com.replaymod.recording.packet.PacketListener$$Lambda$1766/686491969.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Value biomesop has no mapping for key class com.replaymod.lib.com.github.steveice10.mc.protocol.data.game.world.WorldType.
	at com.replaymod.lib.com.github.steveice10.mc.protocol.data.MagicValues.key(MagicValues.java:1081)
	at com.replaymod.lib.com.github.steveice10.mc.protocol.packet.ingame.server.ServerJoinGamePacket.read(ServerJoinGamePacket.java:80)
	at com.replaymod.lib.com.github.steveice10.packetlib.tcp.TcpPacketCodec.decode(TcpPacketCodec.java:41)
	at com.replaymod.replaystudio.studio.protocol.StudioCodec.decode(StudioCodec.java:42)
	at com.replaymod.replaystudio.io.ReplayInputStream.fillBuffer(ReplayInputStream.java:229)
	... 5 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1148720576 bytes (1095 MB) / 3120562176 bytes (2976 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 6, tallocated: 105
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 40 mods loaded, 40 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version           | Source                                               | Signature                                |
	|:------ |:-------------------- |:----------------- |:---------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2            | minecraft.jar                                        | None                                     |
	| LCHIJA | mcp                  | 9.42              | minecraft.jar                                        | None                                     |
	| LCHIJA | FML                  | 8.0.99.99         | forge-1.12.2-14.23.5.2838.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                | 14.23.5.2838      | forge-1.12.2-14.23.5.2838.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | replaymod            | 1.12.2-2.2.0-b7   | zreplaymod-1.12.2-2.2.0-b7 (1).jar                   | None                                     |
	| LCHIJA | bibliocraft          | 2.4.5             | BiblioCraft[v2.4.5][MC1.12.2].jar                    | None                                     |
	| LCHIJA | biomesoplenty        | 7.0.1.2399        | BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar        | None                                     |
	| LCHIJA | buildcraftlib        | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                         | None                                     |
	| LCHIJA | buildcraftcore       | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                         | None                                     |
	| LCHIJA | buildcraftbuilders   | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                         | None                                     |
	| LCHIJA | buildcrafttransport  | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                         | None                                     |
	| LCHIJA | buildcraftsilicon    | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                         | None                                     |
	| LCHIJA | buildcraftenergy     | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                         | None                                     |
	| LCHIJA | jei                  | 4.15.0.268        | jei_1.12.2-4.15.0.268.jar                            | None                                     |
	| LCHIJA | forestry             | 5.8.2.387         | forestry_1.12.2-5.8.2.387.jar                        | None                                     |
	| LCHIJA | buildcraftcompat     | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                         | None                                     |
	| LCHIJA | buildcraftfactory    | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                         | None                                     |
	| LCHIJA | buildcraftrobotics   | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                         | None                                     |
	| LCHIJA | ctm                  | MC1.12.2-0.3.3.22 | CTM-MC1.12.2-0.3.3.22.jar                            | None                                     |
	| LCHIJA | chisel               | MC1.12.2-0.2.1.35 | Chisel-MC1.12.2-0.2.1.35.jar                         | None                                     |
	| LCHIJA | mantle               | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                             | None                                     |
	| LCHIJA | tconstruct           | 1.12.2-2.12.0.135 | TConstruct-1.12.2-2.12.0.135.jar                     | None                                     |
	| LCHIJA | conarm               | 1.2.4             | conarm-1.12.2-1.2.4.jar                              | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | cookingforblockheads | 6.4.70            | CookingForBlockheads_1.12.2-6.4.70.jar               | None                                     |
	| LCHIJA | customnpcs           | 1.12              | CustomNPCs_1.12.2(30Jan19).jar                       | None                                     |
	| LCHIJA | extrautils2          | 1.0               | extrautils2-1.12-1.9.9.jar                           | None                                     |
	| LCHIJA | fairylights          | 2.1.7             | fairylights-2.1.7-1.12.2.jar                         | None                                     |
	| LCHIJA | llibrary             | 1.7.19            | llibrary-1.7.19-1.12.2.jar                           | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | fossil               | 8.0.2             | fossilsarcheology-8.0.2.jar                          | None                                     |
	| LCHIJA | cfm                  | 6.3.0             | furniture-6.3.0-1.12.2.jar                           | None                                     |
	| LCHIJA | waila                | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                          | None                                     |
	| LCHIJA | iceandfire           | 1.7.1             | iceandfire-1.7.1-1.12.2.jar                          | None                                     |
	| LCHIJA | ironchest            | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.69.845.jar                      | None                                     |
	| LCHIJA | journeymap           | 1.12.2-5.5.4      | journeymap-1.12.2-5.5.4.jar                          | None                                     |
	| LCHIJA | naturescompass       | 1.5.1             | NaturesCompass-1.12.2-1.5.1.jar                      | None                                     |
	| LCHIJA | harvestcraft         | 1.12.2zb          | Pam's+HarvestCraft+1.12.2zd+Surprise+for+Yogcast.jar | None                                     |
	| LCHIJA | sgcraft              | 1.13.2            | SGCraft-2.0.1.jar                                    | None                                     |
	| LCHIJA | waystones            | 4.0.67            | Waystones_1.12.2-4.0.67.jar                          | None                                     |
	| LCHIJA | zoocraftdiscoveries  | 1.0               | Zoocraft+Discoveries+1.12.2-1.3.0.jar                | None                                     |
	| LCHIJA | jurassicraft         | 2.1.21            | JurassiCraft-1.12.2-2.1.21.jar                       | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
LoadingPlugin (zreplaymod-1.12.2-2.2.0-b7 (1).jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

**Comment by LindaJuffermans** [comment]
Still an issue in replaymod-1.12.2-2.2.0-b7

**Comment by Johni0702** [comment]
@LindaJuffermans There hasn't been much work on the RM in general (yours is the same version as OP's). This particular issue is one fundamental to how the RM implements some of its features (in a way which isn't particularly compatible with third-party mods, in this case BoP).

I've started an attempt at solving the underlying issue a while back (https://github.com/ReplayMod/ReplayStudio/commit/120feb9bd3133e8a05b3780852bf5ad671c41bcb & https://github.com/ReplayMod/ReplayMod/commit/af8803d6b5fb1db1c3cc72b999239070678e750a) but have yet to test and fix any issues with it (and given how much was changed, there almost certainly will be lots of those). It's also currently part of by 1.15 branch (though it doesn't technically have to be, I just happened to do it at the same time cause 1.15 would have required changes anyway), so for a proper release, that have to be worked on as well.
I am not currently working on it (due to lack of time / more fun things to work on).

Note though that affected replays can usually be recovered (they're in `.minecraft/replay_recordings/raw/`) but ofc any of the affected RM features won't work with them. If you refrain from using the Start/Stop/Pause/Resume recording feature, which is the one failing in OP's report, it shouldn't even fail to save in the first place (though ofc other affected RM features will still not work with them).
