### ISSUE TITLE
Crash when editing keyframes

### ISSUE THREAD

**Issue by slicedlime** [ReplayMod/ReplayMod#7]
What I did:
- Edit a position keyframe.
- Change the yaw value.

Description: Calling Gui method

java.lang.NullPointerException: Calling Gui method
	at com.replaymod.simplepathing.gui.GuiEditKeyframe$Position.save(GuiEditKeyframe.java:255)
	at com.replaymod.simplepathing.gui.GuiEditKeyframe.lambda$new$1(GuiEditKeyframe.java:107)
	at de.johni0702.minecraft.gui.element.AbstractGuiClickable.onClick(AbstractGuiClickable.java:71)
	at de.johni0702.minecraft.gui.element.AbstractGuiButton.onClick(AbstractGuiButton.java:97)
	at de.johni0702.minecraft.gui.element.AbstractGuiClickable.mouseClick(AbstractGuiClickable.java:53)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

[crash-2017-01-31_16.44.33-client.txt](https://github.com/ReplayMod/ReplayMod/files/742480/crash-2017-01-31_16.44.33-client.txt)

Running 1.8 branch synced 2017-01-30.

**Comment by Thelm76** [comment]
same problem with 1.11.2 b6 (but not with b5), clicking on "done" in the keyframe editor

http://paste.ee/p/Tk5wD

**Comment by Johni0702** [comment]
Fixed in 40e1d85.
