### ISSUE TITLE
VarInt too long loading recording

### ISSUE THREAD

**Issue by LindaJuffermans** [ReplayMod/ReplayMod#723]
ReplayMod 1.17.1-2.6.4
Trying to load attached recording gets Minecraft stuck in a loop; have to kill to exit.

```
[16:20:03] [Render thread/INFO]: Opening replay in viewer: C:\Program Files (x86)\MultiMC\instances\Fabric 1.17.1\.minecraft\replay_recordings\2022_04_17_08_18_24.mcpr
[16:20:03] [Thread-20/ERROR]: Loading entity tracker:
java.io.IOException: VarInt too long (length must be <= 5)
	at com.replaymod.lib.com.github.steveice10.packetlib.tcp.io.ByteBufNetInput.readVarInt(ByteBufNetInput.java:62) ~[replaymod-1.17.1-2.6.4.jar:?]
	at com.replaymod.replaystudio.protocol.packets.EntityId.getEntityId(EntityId.java:107) ~[replaymod-1.17.1-2.6.4.jar:?]
	at com.replaymod.replaystudio.util.PacketUtils.getEntityId(PacketUtils.java:58) ~[replaymod-1.17.1-2.6.4.jar:?]
	at com.replaymod.replaystudio.util.EntityPositionTracker.loadFromPacketData(EntityPositionTracker.java:164) ~[replaymod-1.17.1-2.6.4.jar:?]
	at com.replaymod.replaystudio.util.EntityPositionTracker.load(EntityPositionTracker.java:95) ~[replaymod-1.17.1-2.6.4.jar:?]
	at com.replaymod.simplepathing.gui.GuiPathing.lambda$startLoadingEntityTracker$6(GuiPathing.java:534) ~[replaymod-1.17.1-2.6.4.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

Recording:
[2022_04_17_08_18_24.zip](https://github.com/ReplayMod/ReplayMod/files/8501799/2022_04_17_08_18_24.zip)

Full log:
[latest.log](https://github.com/ReplayMod/ReplayMod/files/8501798/latest.log)

**Comment by Johni0702** [comment]
I finally found the time to take a deeper look into this, and afaict all that's wrong with the replay is that all the packet ids (and seemingly only the ids) are wrong.
And not just completely wrong but there seems to be a pattern to it. Afaict they seem to be the corresponding 1.16.2-5 ids, even though the replay is for 1.17.1.

I don't see any way for that to happen with just ReplayMod and the original reporter has left the Discord, so I'll be assuming that they were using something like ViaFabric or MultiConnect (or another mod which allows you to connect to older server) during recording and close this as invalid.
