### ISSUE TITLE
Load playback center video and crash directly

### ISSUE THREAD

**Issue by SugarShugen** [ReplayMod/ReplayMod#727]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2022/4/26 下午3:21
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1937.method_8320(net.minecraft.class_2338)" because "worldSchematic" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.2)
	at fi.dy.masa.litematica.render.OverlayRenderer.updateBlockInfoLines(OverlayRenderer.java:614)
	at fi.dy.masa.litematica.render.OverlayRenderer.renderBlockInfoLines(OverlayRenderer.java:489)
	at fi.dy.masa.litematica.render.OverlayRenderer.renderHoverInfo(OverlayRenderer.java:471)
	at fi.dy.masa.litematica.event.RenderHandler.onRenderGameOverlayPost(RenderHandler.java:52)
	at fi.dy.masa.malilib.event.RenderEventHandler.onRenderGameOverlayPost(RenderEventHandler.java:66)
	at net.minecraft.client.gui.hud.InGameHud.handler$dpd000$onGameOverlayPost(InGameHud:6017)
	at net.minecraft.client.gui.hud.InGameHud.render(InGameHud:416)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:858)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1122)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737)
	at net.minecraft.client.main.Main.main(Main:236)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at fi.dy.masa.litematica.render.OverlayRenderer.updateBlockInfoLines(OverlayRenderer.java:614)
	at fi.dy.masa.litematica.render.OverlayRenderer.renderBlockInfoLines(OverlayRenderer.java:489)
	at fi.dy.masa.litematica.render.OverlayRenderer.renderHoverInfo(OverlayRenderer.java:471)
	at fi.dy.masa.litematica.event.RenderHandler.onRenderGameOverlayPost(RenderHandler.java:52)
	at fi.dy.masa.malilib.event.RenderEventHandler.onRenderGameOverlayPost(RenderEventHandler.java:66)
	at net.minecraft.class_329.handler$dpd000$onGameOverlayPost(class_329.java:6017)
	at net.minecraft.class_329.method_1753(class_329.java:416)

-- Affected level --
Details:
	All players: 2 total; [CameraEntity['Sugar'/-1789435, l='ClientLevel', x=-1239.50, y=-59.50, z=-153.50], class_745['Sugar'/121, l='ClientLevel', x=-1235.93, y=-59.00, z=-140.33]]
	Chunk stats: 1024, 452
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 3755392 game time, 124151 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Default, Compliance+64x+-+Beta+3.zip, [1.18.1]MASA全家桶汉化包.zip, Sugar-music, Sugar-方块, XeKr 原版红石显示1.18.zip, Redstone（放在红石显示上层）, XeKr超护眼材质v2.zip, 怪蛋护眼.zip, 河豚太阳.zip, 通用 Fandol字体包（放在最底层）.zip, betterbeds/connectedbeds, betterbeds/fancybeds, Faithful Tweaks Enchanted Books.zip, sugar-enchant, replaymod_lang

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1399313448 bytes (1334 MiB) / 2097152000 bytes (2000 MiB) up to 8522825728 bytes (8128 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 4600H with Radeon Graphics         
	Identifier: AuthenticAMD Family 23 Model 96 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.99
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 512.00
	Graphics card #0 deviceId: 0x1636
	Graphics card #0 versionInfo: DriverVersion=27.20.11028.5001
	Graphics card #1 name: NVIDIA GeForce GTX 1650
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x1f99
	Graphics card #1 versionInfo: DriverVersion=27.21.14.5749
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 27005.32
	Virtual memory used (MB): 15203.56
	Swap memory total (MB): 11264.00
	Swap memory used (MB): 216.68
	JVM Flags: 12 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -Xmn128m -Xmx8126m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Fabric Mods: 
		advancedchatbox: AdvancedChatBox 1.18-1.1.3
		advancedchatcore: AdvancedChatCore 1.18.2-1.4.4
		advancedchatfilters: AdvancedChatFilters 1.18.2-1.2.2
		advancedchathud: AdvancedChatHUD 1.18.2-1.2.3
		advancedchatlog: AdvancedChatLog 1.18-1.2.0
		advancementinfo: AdvancementInfo 1.18.2-fabric0.47.10-1.3.1
		appleskin: AppleSkin 2.4.0+mc1.18.2
		architectury: Architectury 4.1.34
		bbor: BoundingBoxOutlineReloaded 2.4+HuajiMUR-1.18.2
		bedrockminer: Bedrock Miner 1.0.0
		betterbeds: Better Beds 1.2.0
		betterblockoutline: BetterBlockOutline 1.4.2-1.18.1
		betterpingdisplay: Better Ping Display 1.1.1
		blue_endless_jankson: jankson 1.2.1
		caffeineconfig: CaffeineConfig 1.1.0
		carpet: Carpet Mod 1.4.66
		carpet-extra: Carpet Extra 1.4.64
		carpet-tctc-addition: Carpet TCTC Addition 1.1.8+d0f86ca
		carpet-tis-addition: Carpet TIS Addition 1.31.2
		cherishedworlds: Cherished Worlds 2.0.1-1.18
		chesttracker: Chest Tracker 1.1.10
		citresewn: CIT Resewn 1.0.1+1.18.2
		citresewn-defaults: CIT Resewn: Defaults 1.0.1+1.18.2
		clickthrough: ClickThrough 1.18.2-fabric0.47.10-0.4
		clientcommands: Client Commands 2.6.3
		clientcommands-scripting: Clientcommands Scripting 1.3.1
		cloth-api: Cloth API 3.2.64
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 3.2.64
		cloth-common-events-v1: Cloth Common Events v1 3.2.64
		cloth-config: Cloth Config v6 6.2.57
		cloth-datagen-api-v1: Cloth Datagen v1 3.2.64
		cloth-scissors-api-v1: Cloth Scissors API v1 3.2.64
		cloth-utils-v1: Cloth Utils v1 3.2.64
		com_carrotsearch_hppc: hppc 0.9.0
		com_electronwill_night-config_core: core 3.6.5
		com_electronwill_night-config_toml: toml 3.6.5
		com_github_darkkronicle_konstruct_addons: addons 2.0.2-build1
		com_github_darkkronicle_konstruct_core: core 2.0.2-build1
		com_googlecode_json-simple_json-simple: json-simple 1.1.1
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		command-gui-buttons: QuickBind 1.4+1.18.2
		conditional-mixin: conditional mixin 0.2.0
		continuity: Continuity 1.1.0+1.18.2
		crowdin-translate: CrowdinTranslate 1.4+1.18.2
		customskinloader: CustomSkinLoader 14.13
		easiervillagertrading: EasierVillagerTrading 1.18.2-fabric0.47.10-1.5.4
		edu_washington_cs_knowitall_opennlp-chunk-models: opennlp-chunk-models 1.5
		edu_washington_cs_knowitall_opennlp-postag-models: opennlp-postag-models 1.5
		edu_washington_cs_knowitall_opennlp-tokenize-models: opennlp-tokenize-models 1.5
		explayerenderer: ExtraPlayerRenderer 2.1.3
		fabric: Fabric API 0.48.0+1.18.2
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.7+d7c144a860
		fabric-biome-api-v1: Fabric Biome API (v1) 8.0.3+801ec85b60
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
		fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
		fabric-containers-v0: Fabric Containers (v0) 0.1.21+d7c144a860
		fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.2+d82b939260
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.11+3ac43d9560
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.17+2540745460
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.13+d7c144a860
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
		fabric-item-api-v1: Fabric Item API (v1) 1.3.3+691a79b560
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.10+3ac43d9560
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.11+d7c144a860
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.0.4+d1027f7d60
		fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.21+d882b91560
		fabric-networking-v0: Fabric Networking (v0) 0.3.8+b4f4f6cd60
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.0.3+40c91ec860
		fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.8+0d9ab37260
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.17+d8c7b9ae60
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
		fabric-rendering-v1: Quilted Fabric Rendering (v1) 2.0.0+1.18.2-SNAPSHOT
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.2+d1027f7d60
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.14+40c91ec860
		fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.14+cca23f9360
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.0.0+40c91ec860
		fabricloader: Fabric Loader 0.13.3
		fabrilousupdater: FabrilousUpdater 2.6+1.18.2
		fastchest: FastChest 1.2+1.18
		g4mespeed: G4mespeed 1.3.0
		gbfabrictools: GBfabrictools 1.3.4+1.18.2
		ias: In-Game Account Switcher 7.1.3
		imblocker: IMBlockerFabric 1.0.17
		indium: Indium 1.0.2+mc1.18.2
		inspecio: Inspecio 1.3.0+1.18
		inventoryhud: Inventory HUD + 3.4.2
		inventoryprofilesnext: Inventory Profiles Next 1.3.5
		inventorytabs: Inventory Tabs 0.4.2-1.18.1
		io_github_maowimpl_owo: owo 2.0.0
		iris: Iris 1.2.2-build.32
		itemscroller: Item Scroller craftfix-1.2.6
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		javax_measure_unit-api: unit-api 2.1.3
		javax_xml_bind_jaxb-api: jaxb-api 2.3.1
		kommandlib: KommandLib 0.1.0-1.18.1
		krypton: Krypton 0.1.9
		kyrptconfig: Kyrpt Config 1.3.4-1.18
		language-loader-fix: Language-Loader-Fix 1.2.0+ecea89d
		lazydfu: LazyDFU 0.1.2
		libgui: LibGui 5.1.0+1.18
		libninepatch: LibNinePatch 1.1.0
		litematica: Litematica 0.11.1
		litematica_printer: Litematica Printer 2.1
		lithium: Lithium 0.7.9
		magiclib: MagicLib 0.3.24
		magiclib-compat-mc1_18: MagicLib Compat 0.3.24
		malilib: MaLiLib 0.12.1
		masa_gadget_mod: Masa Gadget 2.0.9.1
		mcwifipnp: LAN World Plug-n-Play 1.5.4
		minecraft: Minecraft 1.18.2
		minihud: MiniHUD 0.22.0
		minihud-injector: MiniHUD-Injector 1.2.0+916ad27
		modmenu: Mod Menu 3.1.0
		more-statistics: More Statistics 2.0.0
		multiconnect-api: MultiConnect API 1.5.10
		nbttooltip: NBT Tooltip 1.5.0-fabric
		net_loomchild_segment: segment 2.0.3
		net_sf_trove4j_trove4j: trove4j 3.0.3
		notenoughcrashes: Not Enough Crashes 4.1.4+1.18.2
		ommc: Oh My Minecraft Client 0.4.2
		orderly: Orderly 2.0.1-alpha.2+custom-1.18
		org_anarres_jcpp: jcpp 1.4.14
		org_apache_commons_commons-csv: commons-csv 1.8
		org_apache_opennlp_opennlp-tools: opennlp-tools 1.9.3
		org_carrot2_morfologik-fsa: morfologik-fsa 2.1.7
		org_carrot2_morfologik-fsa-builders: morfologik-fsa-builders 2.1.7
		org_carrot2_morfologik-speller: morfologik-speller 2.1.7
		org_carrot2_morfologik-stemming: morfologik-stemming 2.1.7
		org_javadelight_delight-nashorn-sandbox: delight-nashorn-sandbox 0.2.5
		org_jetbrains_intellij_deps_trove4j: trove4j 1.0.20200330
		org_joml_joml: joml 1.10.2
		org_languagetool_language-en: language-en 5.5
		org_languagetool_languagetool-core: languagetool-core 5.5
		org_mariuszgromada_math_mathparser_org-mxparser: MathParser.org-mXparser 4.4.2
		org_openjdk_nashorn_nashorn-core: nashorn-core 15.3
		org_webjars_bower_js-beautify: js-beautify 1.9.0
		org_yaml_snakeyaml: snakeyaml 1.29
		pca: Plusls carpet addition mod 0.2.5
		phosphor: Phosphor 0.8.1
		pistorder: Pistorder 1.5.0
		quickshulker: Quick Shulker 1.3.6-1.18
		quilt_base: Quilt Base API 1.0.0+1.18.2-SNAPSHOT
		quilt_client_command: Quilt Client Command API 1.0.0+1.18.2-SNAPSHOT
		quilt_command: Quilt Command API 1.0.0+1.18.2-SNAPSHOT
		quilt_lifecycle_events: Quilt Lifecycle Events 1.0.0+1.18.2-SNAPSHOT
		quilt_resource_loader: Quilt Resource Loader 1.0.0+1.18.2-SNAPSHOT
		quilt_tags: Quilt Tags API 1.0.0+1.18.2-SNAPSHOT
		quilt_tooltip: Quilt Tooltip API 1.0.0+1.18.2-SNAPSHOT
		quilted-fabric-api-base: Quilted Fabric API Base 1.0.0+1.18.2-SNAPSHOT
		quilted-fabric-command-api-v1: Quilted Fabric Command API (v1) 2.0.0+1.18.2-SNAPSHOT
		quilted-fabric-lifecycle-events-v1: Quilted Fabric Lifecycle Events (v1) 2.0.1+1.18.2-SNAPSHOT
		quilted-fabric-resource-loader-v0: Quilted Fabric Resource Loader (v0) 1.0.0+1.18.2-SNAPSHOT
		reeses-sodium-options: Reese's Sodium Options 1.4.2
		replaymod: Replay Mod 1.18.2-2.6.4
		roughlyenoughitems: Roughly Enough Items 8.0.442
		shulkerutils: shulkerutils 1.0.4-1.18
		smoothboot: Smooth Boot 1.18.2-1.7.0
		sodium: Sodium 0.4.1+replaymod.rev.23e83a1
		sodium-extra: Sodium Extra 0.4.3
		tech_units_indriya: indriya 1.3
		tech_uom_lib_uom-lib-common: uom-lib-common 1.1
		tweakermore: TweakerMore 2.10.1
		tweakeroo: Tweakeroo 0.13.1
		whereisit: Where Is It 1.14.10
		worldedit: WorldEdit 7.2.10+1742f98
		worldeditcui: WorldEditCUI 1.18.2+01
		wthit: wthit 4.8.0
		xaero_map_addition: Xaero Map Addition 0.2.1
		xaero_map_addition-compat-mc1_18: Xaero Map Addition Compat 0.2.1
		xaerominimap: Xaero's Minimap 22.4.0
		xaeroworldmap: Xaero's World Map 1.20.5
	Loaded Shaderpack: (off)
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1650/PCIe/SSE2 GL version 3.2.0 NVIDIA 457.49, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: bbor (incompatible), vanilla, file/Compliance+64x+-+Beta+3.zip, file/[1.18.1]MASA全家桶汉化包.zip, file/Sugar-music (incompatible), file/Sugar-方块 (incompatible), file/XeKr 原版红石显示1.18.zip, file/Redstone（放在红石显示上层） (incompatible), file/XeKr超护眼材质v2.zip (incompatible), file/怪蛋护眼.zip (incompatible), file/河豚太阳.zip (incompatible), file/通用 Fandol字体包（放在最底层）.zip (incompatible), betterbeds/connectedbeds, betterbeds/fancybeds, file/Faithful Tweaks Enchanted Books.zip (incompatible), file/sugar-enchant (incompatible)
	Current Language: 简体中文 (中国)
	CPU: 12x AMD Ryzen 5 4600H with Radeon Graphics 
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Litematica (litematica), MaLiLib (malilib)

**Comment by Johni0702** [comment]
I cannot reproduce this using just litematica (0.11.2), mailib (0.12.1) and ReplayMod (2.6.4).
There's this existing issue looking exactly like yours on litematica's tracker, so this might be one of your other mods conflicting with it: https://github.com/maruohon/litematica/issues/514

**Comment by nenjaban** [comment]
[crashreplaymod2.6.4.txt](https://github.com/ReplayMod/ReplayMod/files/8630810/crashreplaymod2.6.4.txt)
[crashreplaymod2.6.5.txt](https://github.com/ReplayMod/ReplayMod/files/8630811/crashreplaymod2.6.5.txt)
I can reproduce this using replaymod 2.6.4 and 2.6.5 and litematica 0.11.2
