### ISSUE TITLE
RM not compatible with Distand Horizons LOD mod when Loading a replay.

### ISSUE THREAD

**Issue by VoidSpectrum** [ReplayMod/ReplayMod#761]
When loading a replay with the Distant Horizons mod enabled, the screen stays as the blank dirt screen, and the log is filled with thousands of lines per minute.
`[00:17:41] [Render thread/ERROR]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_746.method_3130()" because "this.field_3690.field_1724" is null
	at net.minecraft.class_634.method_11115(class_634.java:1340) ~[client-intermediary.jar:?]
	at net.minecraft.class_2713.method_11753(class_2713.java:59) ~[client-intermediary.jar:?]
	at net.minecraft.class_2713.method_11054(class_2713.java:12) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1095) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:734) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]`
	
And so on, however at the begining of Loading, it says:

`[00:17:38] [Render thread/ERROR]: Error executing task on Client
java.lang.NullPointerException: Cannot read field "field_3761" because the return value of "net.minecraft.class_310.method_1558()" is null
	at fabric.com.seibel.lod.common.wrappers.minecraft.MinecraftClientWrapper.getCurrentServerIp(MinecraftClientWrapper.java:146) ~[DistantHorizons-1.6.7a-1.19.jar:?]
	at com.seibel.lod.core.util.LodUtil.getServerFolderName(LodUtil.java:254) ~[DistantHorizons-1.6.7a-1.19.jar:?]
	at com.seibel.lod.core.util.LodUtil.getWorldID(LodUtil.java:218) ~[DistantHorizons-1.6.7a-1.19.jar:?]
	at com.seibel.lod.core.api.EventApi.worldLoadEvent(EventApi.java:142) ~[DistantHorizons-1.6.7a-1.19.jar:?]
	at com.seibel.lod.fabric.ClientProxy.worldLoadEvent(ClientProxy.java:125) ~[DistantHorizons-1.6.7a-1.19.jar:?]
	at net.minecraft.class_638.handler$bac000$loadWorldEvent(class_638.java:2148) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.<init>(class_638.java:179) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11120(class_634.java:366) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.method_11567(class_2678.java:86) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.method_11054(class_2678.java:20) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1095) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:734) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
[2022-07-26-4.log](https://github.com/ReplayMod/ReplayMod/files/9187582/2022-07-26-4.log)

	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]`

Disabling Distant Horizons and attempting to load the replay again works perfectly,

**Comment by Johni0702** [comment]
This is an issue in DH. They assume that if you're not in singleplayer or realms, you must be in multiplayer, but that's not true with RM.
Report it to them.
