### ISSUE TITLE
When playing with mcheli this crash happens when i record for too long. But somtimes when it dose record for that long all the chunks that has mcheli items dont load

### ISSUE THREAD

**Issue by Gamersooreal** [ReplayMod/ReplayMod#770]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 8/31/22 10:55 PM
Description: Saving replay file

java.lang.IndexOutOfBoundsException: readerIndex(1) + length(4) exceeds writerIndex(3): PooledUnsafeDirectByteBuf(ridx: 1, widx: 3, cap: 3)
	at com.replaymod.lib.com.github.steveice10.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1477)
	at com.replaymod.lib.com.github.steveice10.netty.buffer.AbstractByteBuf.readInt(AbstractByteBuf.java:810)
	at com.replaymod.lib.com.github.steveice10.packetlib.tcp.io.ByteBufNetInput.readInt(ByteBufNetInput.java:51)
	at com.replaymod.replaystudio.protocol.packets.EntityId.getEntityId(EntityId.java:106)
	at com.replaymod.replaystudio.util.PacketUtils.getEntityId(PacketUtils.java:58)
	at com.replaymod.replaystudio.filter.SquashFilter.onPacket(SquashFilter.java:249)
	at com.replaymod.editor.gui.MarkerProcessor.apply(MarkerProcessor.java:215)
	at com.replaymod.recording.packet.PacketListener.lambda$channelInactive$6(PacketListener.java:296)
	at com.replaymod.recording.packet.PacketListener$$Lambda$19033/474143859.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3643230616 bytes (3474 MB) / 6341787648 bytes (6048 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E7 36 mods loaded, 36 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAAA	CodeChickenCore{1.0.7.48} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAAA	securitycraft{v1.8.10} [SecurityCraft] ([1.7.10]+SecurityCraft+v1.8.10.jar) 
	UCHIJAAAAA	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips-1.7.1.jar) 
	UCHIJAAAAA	blockarmor{1.1} [Block Armor] (BlockArmor-1.7.10-1.1.jar) 
	UCHIJAAAAA	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UCHIJAAAAA	BuildCraft|Core{7.1.24} [BuildCraft] (buildcraft-7.1.24.jar) 
	UCHIJAAAAA	BuildCraft|Builders{7.1.24} [BC Builders] (buildcraft-7.1.24.jar) 
	UCHIJAAAAA	BuildCraft|Robotics{7.1.24} [BC Robotics] (buildcraft-7.1.24.jar) 
	UCHIJAAAAA	BuildCraft|Silicon{7.1.24} [BC Silicon] (buildcraft-7.1.24.jar) 
	UCHIJAAAAA	BuildCraft|Energy{7.1.24} [BC Energy] (buildcraft-7.1.24.jar) 
	UCHIJAAAAA	BuildCraft|Transport{7.1.24} [BC Transport] (buildcraft-7.1.24.jar) 
	UCHIJAAAAA	BuildCraft|Factory{7.1.24} [BC Factory] (buildcraft-7.1.24.jar) 
	UCHIJAAAAA	MineTweaker3{3.1.0} [MineTweaker 3] (CraftTweaker-1.7.10-3.1.0-legacy.jar) 
	UCHIJAAAAA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d(29oct17).jar) 
	UCHIJAAAA	Dynmap{2.6-beta-1-2035} [Dynmap] (Dynmap-2.6-beta-1-forge-1.7.10.jar) 
	UCHIJAAAA	hbm{1.0.27 BETA (4228)} [Hbm's Nuclear Tech] (HBM-NTM-[1.0.27_X4228H1].jar) 
	UCHIJAAAA	IronChest{6.0.39.728} [Iron Chest] (ironchest-1.7.10-6.0.39.728-universal.jar) 
	UCHIJAAAA	journeymap{5.1.4p2} [JourneyMap] (journeymap-1.7.10-5.1.4p2-unlimited.jar) 
	UCHIJAAAA	LotsOfFood{1.7.10} [Lots of Food] (Lots of Food-1.7.10.jar) 
	UCHIJAAAA	malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar) 
	UCHIJAAAA	malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (malisisdoors-1.7.10-1.13.2.jar) 
	UCHIJAAAA	mcheli{1.0.4} [MC Helicopter] (mcheli) 
	UCHIJAAAA	MTRM{1.0} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.7.10-1.1.1.jar) 
	UCHIJAAAA	mw{1.11.7.7} [Modern Warfare] (mw-1.11.7.7_mc1.7.10 (1).jar) 
	UCHIJAAAA	recipehandler{1.7.10} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.3(1.7.10).jar) 
	UCHIJAAAA	replaymod-restrictions{1.7.10-2.5.2} [Replay Mod - Restrictions] (replaymod-1.7.10-2.5.2.jar) 
	UCHIJAAAA	replaymod{1.7.10-2.5.2} [Replay Mod] (replaymod-1.7.10-2.5.2.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.6} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.6-118.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.2.1} [Thermal Dynamics] (ThermalDynamics-1.7.101.2.1-172.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.1.5} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.5-248.jar) 
	UCHIJAAAA	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.7.10-6.1.1-dist.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	CoFHCore: -[1.7.10]3.1.4-329
	ThermalFoundation: -[1.7.10]1.2.6-118
	ThermalDynamics: -[1.7.10]1.2.1-172
	ThermalExpansion: -[1.7.10]4.1.5-248
	OptiFine Version: OptiFine_1.7.10_HD_U_E7
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 516.94
	OpenGlRenderer: NVIDIA GeForce RTX 3060/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by forwardslashh** [comment]
Same
