### ISSUE TITLE
Crashing while rendering

### ISSUE THREAD

**Issue by mrksbgg** [ReplayMod/ReplayMod#777]
Hello there! I got an error while trying to render a video.

Here's the error:

```
---- Minecraft Crash Report ----
// You're mean.

Time: 08.10.2022, 09:04
Description: Exporting video

com.replaymod.render.FFmpegWriter$FFmpegStartupException
	at com.replaymod.render.FFmpegWriter.getVideoFile(FFmpegWriter.java:163)
	at com.replaymod.render.FFmpegWriter.consume(FFmpegWriter.java:121)
	at com.replaymod.render.rendering.VideoRenderer$1.consume(VideoRenderer.java:154)
	at com.replaymod.render.rendering.Pipeline$ParallelSafeConsumer.consume(Pipeline.java:150)
	at com.replaymod.render.rendering.Pipeline$ProcessTask.run(Pipeline.java:118)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:


-- Head --
Thread: Render thread
Stacktrace:
	at com.replaymod.render.gui.GuiExportFailed.tryToRecover(GuiExportFailed.java:34)

-- Export details --
Details:
	Settings: RenderSettings{renderMethod=Default Rendering, encodingPreset=MP4 - Custom Bitrate, videoWidth=1920, videoHeight=1080, framesPerSecond=60, bitRate=125829120, outputFile=C:\Users\sibag\AppData\Roaming\.minecraft\.\replay_videos\2022_10_08_09_04_18.mp4, renderNameTags=true, includeAlphaChannel=false, stabilizeYaw=false, stabilizePitch=false, stabilizeRoll=false, chromaKeyingColor=null, sphericalFovX=360, sphericalFovY=180, injectSphericalMetadata=false, depthMap=false, cameraPathExport=false, antiAliasing=None, exportCommand='', exportArgumentsPreBgra='', exportArguments='-y -f rawvideo -pix_fmt bgra -s %WIDTH%x%HEIGHT% -r %FPS% -i - %FILTERS%-an -c:v libx264 -b:v %BITRATE% -pix_fmt yuv420p "%FILENAME%"', highPerformance=false}
	FFmpeg log: ffmpeg version n5.1.2-2-g79bd6a21a0-20221007 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --disable-avisynth --enable-libdav1d --disable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --disable-frei0r --enable-libgme --enable-libkvazaar --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --disable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --disable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --disable-libx264 --disable-libx265 --disable-libxavs2 --disable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20221007
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
Input #0, rawvideo, from 'pipe:':
  Duration: N/A, start: 0.000000, bitrate: 3981312 kb/s
  Stream #0:0: Video: rawvideo (BGRA / 0x41524742), bgra, 1920x1080, 3981312 kb/s, 60 tbr, 60 tbn
Unknown encoder 'libx264'

Stacktrace:
	at com.replaymod.render.gui.GuiExportFailed.tryToRecover(GuiExportFailed.java:34)
	at com.replaymod.render.gui.GuiRenderSettings$7.run(GuiRenderSettings.java:247)
	at com.replaymod.core.versions.scheduler.SchedulerImpl.lambda$runLater$3(SchedulerImpl.java:113)
	at net.minecraft.class_1255.method_18859(class_1255.java:198)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:163)
	at net.minecraft.class_1255.method_5383(class_1255.java:140)
	at com.replaymod.core.versions.scheduler.SchedulerImpl$ReplayModExecutor.method_5383(SchedulerImpl.java:78)
	at com.replaymod.core.versions.scheduler.SchedulerImpl.runTasks(SchedulerImpl.java:85)
	at com.replaymod.core.ReplayMod.runTasks(ReplayMod.java:201)
	at com.replaymod.replay.InputReplayTimer.method_1658(InputReplayTimer.java:66)
	at net.minecraft.class_310.method_1523(class_310.java:1092)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

P.S: Sorry for my bad English, I'm Russian.

**Comment by RaderRMT** [comment]
You're using a version of FFmpeg that doesn't have the `libx264` encoder. Please follow [this section](https://www.replaymod.com/docs/#installing-ffmpeg-windows) of the documentation to install a compatible FFmpeg version.

**Comment by mrksbgg** [comment]
Thank you!
