### ISSUE TITLE
Can't save a replay

### ISSUE THREAD

**Issue by iambeingtracked** [ReplayMod/ReplayMod#783]
Basically I can't save a replay, because each time I try to do so, it gives this error:
```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2022-10-24 22:15:58
Description: Saving replay file

java.io.IOException: Expected 0 sky light sections but got 18
	at com.replaymod.replaystudio.protocol.packets.PacketUpdateLight.readData(PacketUpdateLight.java:115)
	at com.replaymod.replaystudio.protocol.packets.PacketChunkData.readLoad(PacketChunkData.java:344)
	at com.replaymod.replaystudio.protocol.packets.PacketChunkData.read(PacketChunkData.java:59)
	at com.replaymod.replaystudio.filter.SquashFilter.onPacket(SquashFilter.java:393)
	at com.replaymod.editor.gui.MarkerProcessor.apply(MarkerProcessor.java:217)
	at com.replaymod.recording.packet.PacketListener.lambda$channelInactive$6(PacketListener.java:305)
	at java.base/java.lang.Thread.run(Thread.java:1589)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 6.0.2-arch1-1
	Java Version: 19.0.1, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: edited
	CPUs: edited
	Processor Vendor: edited
	Processor Name: edited
	Identifier: edited
	Microarchitecture: unknown
	Frequency (GHz): edited
	Number of physical packages: 1
	Number of physical CPUs: edited
	Number of logical CPUs: edited
	Graphics card #0 name: edited
	Graphics card #0 vendor: edited
	Graphics card #0 VRAM (MB): edited
	Graphics card #0 deviceId: edited
	Graphics card #0 versionInfo: unknown
	Graphics card #177 
	Graphics card #1 vendor: edited
	Graphics card #1 VRAM (MB): edited
	Graphics card #1 deviceId: edited
	Graphics card #1 versionInfo: unknown
	Virtual memory max (MB): edited
	Virtual memory used (MB): edited
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	Fabric Mods: 
		antighost: AntiGhost 1.19.1-fabric0.58.5-1.1.5
		architectury: Architectury 6.2.46
		autoclicker-fabric: Auto Clicker 1.19.2-1.4.2-build.19
		betterblockoutline: BetterBlockOutline 1.5.1-1.19
		betterdroppeditems: Better Dropped Items 1.4.1-1.19
		blur: Blur (Fabric) 2.6.0
			midnightlib: MidnightLib 0.5.2
			satin: Satin 1.8.0
		bobby: Bobby 4.0.0
			com_typesafe_config: config 1.4.2
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		chat_heads: Chat Heads 0.7.1
		chesttracker: Chest Tracker 1.1.17
			libgui: LibGui 6.0.0-beta.5+1.19-pre1
				jankson: Jankson 4.1.1+j1.2.1
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
			whereisit: Where Is It 1.14.11
		clickthrough: ClickThrough 1.19.1-fabric0.58.5-0.4
			crowdin-translate: CrowdinTranslate 1.4+1.19
			gbfabrictools: GBfabrictools 1.3.4+1.19
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		darkkore: DarkKore 0.3.1-1.19
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_json: json 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_github_darkkronicle_konstruct_addons: addons 2.0.3-build1
			com_github_darkkronicle_konstruct_core: core 2.0.3-build1
		do-a-barrel-roll: Do a Barrel Roll 1.3.2+1.19
			com_github_llamalad7_mixinextras: MixinExtras 0.1.0-rc5
		ecs: Elytra/Chestplate Swapper 1.2.1-MC1.19
		emotecraft: Emotecraft 2.2.5
			bendy-lib: Bendy api 2.1.2
			player-animator: Player Animator 0.3.5
		fabric-api: Fabric API 0.62.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.12+93d8cb8290
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.10+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.18+c6af733c90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.21+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.2+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.12+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.8+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.29+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.35+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.3.1+624e468e90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.2+93d8cb8290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.6+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.2.0+b598f4ac90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.32+0dd10df690
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.19+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.29+c6af733c90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.29+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.22+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.5.8+93d8cb8290
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.30+93d8cb8290
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.21+93d8cb8290
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.19+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.0+33ffe9ec90
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.4+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.7+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.4+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.15+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.18+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.5+c6af733c90
			fabric-networking-v0: Fabric Networking (v0) 0.3.22+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.12+93d8cb8290
			fabric-particles-v1: Fabric Particles (v1) 1.0.11+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.26+c6af733c90
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.11+c6af733c90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.13+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.21+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.15+aeb40ebe90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.8+c6af733c90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.23+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.0+73145abb90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.12+a29562c890
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.7.0+93d8cb8290
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.27+93d8cb8290
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.1+1cc24b1b90
			fabric-textures-v0: Fabric Textures (v0) 1.0.21+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.1+93d8cb8290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.1+42d99c3290
		fabric-language-kotlin: Fabric Language Kotlin 1.8.4+kotlin.1.7.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.3
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.0
		fabricloader: Fabric Loader 0.14.9
		gammautils: Gamma Utils 1.6.10
		iris: Iris 1.4.0
			io_github_douira_glsl-transformer: glsl-transformer 1.0.0-pre21.2
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.10.1
		java: OpenJDK 64-Bit Server VM 19
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		libipn: libIPN 1.0.0
		litematica: Litematica 0.12.5
		lithium: Lithium 0.9.1
		malilib: MaLiLib 0.13.0
		minecraft: Minecraft 1.19.2
		modmenu: Mod Menu 4.0.6
		no-telemetry: No Telemetry 1.4.0
		nochatreports: No Chat Reports 1.19.2-v1.13.5
		notenoughanimations: NotEnoughAnimations 1.6.1
		perspectivemod: Perspective Mod Redux 0.0.5_01
		plasmo_voice: Plasmo Voice 1.2.19
		replaymod: Replay Mod 1.19.1-2.6.8
		roughlyenoughitems: Roughly Enough Items 9.1.550
			error_notifier: Error Notifier 1.0.9
		shulkerboxtooltip: Shulker Box Tooltip 3.0.9-beta.1+1.19-rc2
			mm: Manningham Mills 2.3
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		torohealth: ToroHealth Damage Indicators 1.19-fabric-1
		wi_zoom: WI Zoom 1.4-MC1.19.2
	Loaded Shaderpack: (off)
	```
I edited some of the hardware details for the sake of privacy.
I'm using the Replay Mod v2.6.8 for Minecraft 1.19.2 + 1.19.1 (requires Fabric)
The launcher I use is MultiMC

**Comment by iambeingtracked** [comment]
I assume it might be Gamma Utils messing with brightness in unexpected ways due to this message:
`java.io.IOException: Expected 0 sky light sections but got 18`

**Comment by Johni0702** [comment]
Based on reports we've been getting on Discord, I don't think this is caused by any third-party client-side mod. It seems to be happening on specific servers only.
If you don't mind, could you share one such replay (you can find it in `.minecraft/replay_recordings/raw` after the crash)?

**Comment by iambeingtracked** [comment]
For some reason it stopped happening. When I get a crash like this I'll send the raw file.
Meanwhile I want to ask, do those raw files have something private?
E.g. if I did something I don't want anyone to see, will it be okay to upload that raw file to the public?

**Comment by Johni0702** [comment]
They are regular replay files but for the entirety of the session, without Start/Stop/Pause/Resume taken into consideration (cause that's where your error is thrown). As such, they contain everything the server sent you in that session, e.g. your uuid, username and skin at the time, any chat that was happening at the time, signs in the chunks around you (and ofc the chunks themselves), etc. Pretty much everything you can see when you watch that replay (and a few smaller extra things you can't see in the replay but which the server sent you for when you where playing, like the initial content of your inventory).

**Comment by iambeingtracked** [comment]
Hello there again.
I think it's actually Gamma Utils that caused the issue. When I record a replay with gamma set to 100% it never crashes, however if gamma is set to 1500% (the default value in Gamma Utils) it crashes most of the times.

**Comment by Johni0702** [comment]
After a quick look at Gamma Util's code, that does not seem plausible. It is entirely client-side and as such should not have any effect on the recording.
