### ISSUE TITLE
Expected 0 sky light sections but got 18

### ISSUE THREAD

**Issue by Johni0702** [ReplayMod/ReplayMod#788]
Seems to happen fairly reliably on some (relatively small amount of) servers. Likely related to server software / plugin / proxy or the like.
Sample: https://cdn.discordapp.com/attachments/1038360013267271690/1038369779414736896/2022_11_05_11_04_05.mcpr

```
java.io.IOException: Expected 0 sky light sections but got 18
	at com.replaymod.replaystudio.protocol.packets.PacketUpdateLight.readData(PacketUpdateLight.java:115)
	at com.replaymod.replaystudio.protocol.packets.PacketChunkData.readLoad(PacketChunkData.java:344)
	at com.replaymod.replaystudio.protocol.packets.PacketChunkData.read(PacketChunkData.java:59)
	at com.replaymod.replaystudio.filter.SquashFilter.onPacket(SquashFilter.java:393)
	at com.replaymod.editor.gui.MarkerProcessor.apply(MarkerProcessor.java:217)
	at com.replaymod.recording.packet.PacketListener.lambda$channelInactive$6(PacketListener.java:305)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Johni0702** [comment]
Cannot reproduce with given sample.
