### ISSUE TITLE
Show preview not working.

### ISSUE THREAD

**Issue by ShitHead1234** [ReplayMod/ReplayMod#82]
Show preview button is not working.

then the mod hangs.......

nothing works on replaymod.

maybe learn not to program minecraft mods on github (owner MS), minecraft (owner MS, for $2.500.000.000), windows (owner MS).

**Comment by ShitHead1234** [comment]
I've never seen so much shit in my whole life like minecraft.
Anything MS touches dies.

**Comment by ShitHead1234** [comment]
![image](https://user-images.githubusercontent.com/55334137/64914527-3224ad80-d754-11e9-9fed-cebf823c4d5f.png)

**Comment by ShitHead1234** [comment]
[01:02:00] [main/INFO]: Loading for game Minecraft 1.14.4
[01:02:03] [main/INFO]: [FabricLoader] Loading 29 mods: minecraft@1.14.4, fabric-renderer-api-v1@0.1.1+591e97ae42, fabric-networking-blockentity-v0@0.1.1+591e97ae42, fabric-keybindings-v0@0.1.1+591e97ae42, fabricloader@0.6.1+build.165, fabric-renderer-indigo@0.1.13+591e97ae42, fabric-containers-v0@0.1.2+591e97ae42, fabric-biomes-v1@0.1.0+591e97ae42, fabric-crash-report-info-v1@0.1.1+591e97ae42, fabric-events-interaction-v0@0.1.1+591e97ae42, fabric-api-base@0.1.0+2983bc0442, fabric-rendering-v0@0.1.1+591e97ae42, replaymod@1.14.4-2.2.0-b7, fabric-rendering-data-attachment-v1@0.1.0+591e97ae42, fabric-resource-loader-v0@0.1.3+591e97ae42, fabric-textures-v0@0.1.4+591e97ae42, fabric-content-registries-v0@0.1.1+591e97ae42, fabric-tag-extensions-v0@0.1.1+591e97ae42, fabric-rendering-fluids-v1@0.1.2+36f27aa342, fabric-commands-v0@0.1.1+591e97ae42, fabric-registry-sync-v0@0.2.2+591e97ae42, fabric-mining-levels-v0@0.1.0+591e97ae42, fabric-loot-tables-v1@0.1.0+591e97ae42, fabric-events-lifecycle-v0@0.1.1+591e97ae42, fabric@0.3.2+build.226-1.14, fabric-models-v0@0.1.0+591e97ae42, fabric-item-groups-v0@0.1.0+591e97ae42, fabric-object-builders-v0@0.1.1+591e97ae42, fabric-networking-v0@0.1.3+591e97ae42
[01:02:03] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/D:/PACMAN/MultiMC/libraries/net/fabricmc/sponge-mixin/0.7.11.38/sponge-mixin-0.7.11.38.jar Service=Knot/Fabric Env=CLIENT
[01:02:03] [main/INFO]: Compatibility level set to JAVA_8
[01:02:03] [main/WARN]: Error loading class: shadersmod/client/ShadersRender (java.lang.ClassNotFoundException: shadersmod/client/ShadersRender)
[01:02:03] [main/WARN]: Error loading class: net/optifine/shaders/ShadersRender (java.lang.ClassNotFoundException: net/optifine/shaders/ShadersRender)
[01:02:04] [main/INFO]: Setting user: Pacman_Graphics
[01:02:08] [main/INFO]: [Indigo] Registering Indigo renderer!
[01:02:11] [main/WARN]: Skipping bad option: lastServer:
[01:02:11] [main/INFO]: LWJGL Version: 3.2.2 build 10
[01:02:11] [Thread-31/INFO]: Cannot offer OpenEye, server returned: 404 Not Found
[01:02:16] [main/WARN]: Mixin apply failed mixins.compat.shaders.replaymod.json:MixinShaderRenderChunk -> net.minecraft.class_851: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @Inject annotation on handler$replayModCompat_disableIsPlayerUpdate$zgm000 could not find any targets matching 'isPlayerUpdate' in the target class net.minecraft.class_851. Using refmap mixins.replaymod.refmap.json
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @Inject annotation on handler$replayModCompat_disableIsPlayerUpdate$zgm000 could not find any targets matching 'isPlayerUpdate' in the target class net.minecraft.class_851. Using refmap mixins.replaymod.refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:421) ~[sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:172) ~[sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:159) ~[sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:151) ~[sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:44) ~[sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:472) ~[sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1180) ~[sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:930) ~[sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:318) ~[sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:281) ~[sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353) ~[sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724) [sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703) [sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509) [sponge-mixin-0.7.11.38.jar:0.7.11.38+unknown-b0.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:180) [fabric-loader-0.6.1+build.165.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143) [fabric-loader-0.6.1+build.165.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_221]
	at net.minecraft.class_761.<init>(class_761.java:230) [intermediary-minecraft-1.14.4-client.jar:?]
	at net.minecraft.class_310.method_1503(class_310.java:569) [intermediary-minecraft-1.14.4-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:394) [intermediary-minecraft-1.14.4-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:155) [intermediary-minecraft-1.14.4-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:178) [fabric-loader-0.6.1+build.165.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131) [fabric-loader-0.6.1+build.165.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.6.1+build.165.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[01:02:16] [main/INFO]: Narrator library for x64 successfully loaded
[01:02:30] [main/INFO]: OpenAL initialized.
[01:02:30] [main/INFO]: Sound engine started

**Comment by ShitHead1234** [comment]
Spending weeks for a few minutes of video.....
:P
