### ISSUE TITLE
1.8.9 Quickmode init failure

### ISSUE THREAD

**Issue by LazyKB** [ReplayMod/ReplayMod#820]
Occurs on a specific Replay 

The Replay is on Hypixel and involves a lot of world changing

Other mods are present, can be seen in the report I believe

Linda suspected Patcher as a FAQ cause of the problem 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  PatcherTweaker (Patcher-1.8.1 (1.8.9).jar)
  FMLLoadingPlugin (Hytilities-Reborn-1.4.1.jar)
  Glint Colorizer ([1.8.9] GlintColorizer - 1.0.jar)
  LoadingPlugin (Armor_Glint_1.0.jar)
  FMLLoadingPlugin (MouseDelayFix-1.0.jar)
  ModTweaker (Patcher-1.8.1 (1.8.9).jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 2/7/23 1:43 PM
Description: Failed to initialize quick mode. It will not be available.

java.lang.NullPointerException: Failed to initialize quick mode. It will not be available.
	at com.replaymod.replaystudio.protocol.packets.PacketChunkData$PalettedStorage.get(PacketChunkData.java:792)
	at com.replaymod.replaystudio.rar.containers.BlockStateTree$Builder.update(BlockStateTree.java:111)
	at com.replaymod.replaystudio.rar.analyse.ReplayAnalyzer.analyse(ReplayAnalyzer.java:160)
	at com.replaymod.replaystudio.rar.RandomAccessReplay.analyseReplay(RandomAccessReplay.java:158)
	at com.replaymod.replaystudio.rar.RandomAccessReplay.load(RandomAccessReplay.java:85)
	at com.replaymod.replay.QuickReplaySender.lambda$initialize$2(QuickReplaySender.java:140)
	at java.lang.Thread.run(Thread.java:750)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_345, Temurin
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Temurin
	Memory: 935949240 bytes (892 MB) / 2948595712 bytes (2812 MB) up to 2948595712 bytes (2812 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms3072m -Xmx3072m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_M6_pre2 25 mods loaded, 25 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version      | Source                                       |
	| ------ | -------------------- | ------------ | -------------------------------------------- |
	| UCHIJA | mcp                  | 9.19         | minecraft.jar                                |
	| UCHIJA | FML                  | 8.0.99.99    | forge-1.8.9-11.15.1.2318-1.8.9-universal.jar |
	| UCHIJA | Forge                | 11.15.1.2318 | forge-1.8.9-11.15.1.2318-1.8.9-universal.jar |
	| UCHIJA | Glint-Colorizer      | 1.0          | minecraft.jar                                |
	| UCHIJA | mousedelayfix        | 1.0          | minecraft.jar                                |
	| UCHIJA | essential            | 1.0.0        | Essential (forge_1.8.9).jar                  |
	| UCHIJA | replaymod            | 1.8.9-2.6.10 | replaymod-1.8.9-2.6.10.jar                   |
	| UCHIJA | onecore              | 1.3.4        | OneCore.jar                                  |
	| UCHIJA | qSts                 | 1.6.3        | 1.8.9.quickStats-1.6.3.jar                   |
	| UCHIJA | customcrosshairmod   | 0.5.1-Forge  | [1.8.9] Crosshairmod-v0.5.1.jar              |
	| UCHIJA | armorglint           | 1.0          | Armor_Glint_1.0.jar                          |
	| UCHIJA | behindyouv3          | 3.1.0        | BehindYouV3-3.1.0.jar                        |
	| UCHIJA | betterchat           | 1.5          | betterchat-1.5-for-1.8.9.jar                 |
	| UCHIJA | fw                   | 1.3.0        | Borderless-Windowed-Mod-1.10.2.jar           |
	| UCHIJA | csb                  | 1.4.4        | CustomSelectionBox-1.8.9-1.4.4.jar           |
	| UCHIJA | evergreenhud         | 641c7c4      | EvergreenHUD (1.4.0.0-rev.641c7c4).jar       |
	| UCHIJA | hytilities-reborn    | 1.4.1        | Hytilities-Reborn-1.4.1.jar                  |
	| UCHIJA | ias                  | 7.1.3        | InGameAccountSwitcher-Forge-1.8.9-7.1.3.jar  |
	| UCHIJA | keystrokesmod        | 8.1.2        | Keystrokes-8.1.2 (1.8.9).jar                 |
	| UCHIJA | minecraftcapes       | 10           | MinecraftCapes+Forge+1.8.9-v10.jar           |
	| UCHIJA | sk1er_old_animations | 0.2.0        | OldAnimations_1.0.0_-_beta_10.1.jar          |
	| UCHIJA | orangesimplemod      | 1.0          | Orange's+Simple+Mods-1.2.jar                 |
	| UCHIJA | particlesenhanced    | 1.2.0        | ParticlesEnhanced-1.2.0.jar                  |
	| UCHIJA | patcher              | 1.8.1        | Patcher-1.8.1 (1.8.9).jar                    |
	| UCHIJA | timechanger          | 2.1          | TimeChanger-2.2.1.jar                        |

	Loaded coremods (and transformers): 
PatcherTweaker (Patcher-1.8.1 (1.8.9).jar)
  club.sk1er.patcher.tweaker.ClassTransformer
FMLLoadingPlugin (Hytilities-Reborn-1.4.1.jar)
  net.wyvest.hytilities.forge.ClassTransformer
Glint Colorizer ([1.8.9] GlintColorizer - 1.0.jar)
  me.powns.glintcolorizer.asm.itemrender.RenderItemTransformer
LoadingPlugin (Armor_Glint_1.0.jar)
  me.aycy.armorglint.asm.Transformer
FMLLoadingPlugin (MouseDelayFix-1.0.jar)
  io.prplz.mousedelayfix.ClassTransformer
ModTweaker (Patcher-1.8.1 (1.8.9).jar)
  club.sk1er.patcher.tweaker.other.ModClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 517.02' Renderer: 'NVIDIA GeForce RTX 3060/PCIe/SSE2'
	OptiFine Version: OptiFine_1.8.9_HD_U_M6_pre2
	OptiFine Build: 20211101-204933
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL_v8.2.01.zip
	OpenGlVersion: 4.6.0 NVIDIA 517.02
	OpenGlRenderer: NVIDIA GeForce RTX 3060/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

**Comment by Fr-Dae** [comment]
link to : 
- https://github.com/ReplayMod/ReplayMod/issues/807
- https://github.com/ReplayMod/ReplayMod/issues/1012
- https://github.com/ReplayMod/ReplayMod/issues/1112

**Comment by Fr-Dae** [comment]
If you accidentally press the ‘quick replay’ button (which nobody knows what this feature is actually supposed to do),

it freezes the replay in progress, loads something endlessly before crashing (or the user has to force it to close).

### Debug Information

<details>
<summary>Client Info</summary>

```java
Create:
	Mod Version: 6.0.10
	Mod Git Commit: ac0c444d9828da3453ae8cc65338e8de063286fb
	Ponder Version: 1.0.82+mc1.21.1
	NeoForge Version: 21.1.228
	Minecraft Version: 1.21.1

Graphics:
	Flywheel Version: 1.0.6
	Flywheel Backend: flywheel:indirect
	OpenGL Renderer: Quadro M1200/PCIe/SSE2
	OpenGL Version: 4.6.0 NVIDIA 580.142
	Graphics Mode: fast
	PojavLauncher Detected: false

System Information:
	Operating System: Linux (amd64) version 7.0.0-15-generic
	Java Version: 21.0.11-ea, Ubuntu
	JVM Flags: 2 total; -Xms512m -Xmx8192m
	Memory: 338059536 bytes (322 MiB) / 2529165312 bytes (2412 MiB) up to 8589934592 bytes (8192 MiB)
	Total Memory: 2207882992 bytes (2105 MiB) / 2529165312 bytes (2412 MiB)
	CPU: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz @ 2.30 GHz; 4 cores / 4 threads on 1 socket(s)
	Graphics cards: none

Other Mods:
	Forgified Fabric Renderer API (v1): 3.4.1+9125b6dc19
	Fabric Language Kotlin: 1.13.11_kotlin.2.3.21
	BetterGrassify: 1.7.0+neoforge.1.21.1
	Create Deco: 2.1.3
	Forgified Fabric Item API (v1): 11.2.0+0c57911319
	Forgified Fabric Rendering Fluids (v1): 3.1.6+a51883b219
	ModMenu Badges Lib: 2023.6.1
	Placeholder API: 2.4.0-pre.2_1.21
	Create Aeronautics: 1.2.1
	Forgified Fabric Convention Tags: 2.1.5+7f945d5b19
	Xaero's World Map: 1.40.16
	Forgified Fabric Command API (v2): 2.2.28+36d727be19
	Forgified Fabric BlockView API (v2): 1.0.11+e9036fd419
	Forgified Fabric Convention Tags (v2): 2.11.1+87e5848019
	ReForgedPlay Mod: 0.3
	Forgified Fabric Data Attachment API (v1): 1.4.5+26d408aa19
	LambDynamicLights: 4.8.8+1.21.1
	Iris: 1.8.12-snapshot+mc1.21.1-local
	Veil: 4.0.0
	Create Simulated: 1.2.1
	Forgified Fabric Screen API (v1): 2.0.25+0ae1214819
	Sinytra Connector: 2.0.0-beta.14+1.21.1
	Cloth Config v15 API: 15.0.140
	Forgified Fabric API: 0.116.7+2.2.4+1.21.1
	Pride Lib: 1.2.4+1.21.1
	Forgified Fabric Content Registries (v0): 8.0.19+5e0d320019
	MCPitanLib: 3.6.8-1.21.1-neoforge
	Konkrete: 1.9.9
	Entity Model Features: 3.2.4
	Entity Texture Features: 7.1
	Forgified Fabric Game Rule API (v1): 1.0.53+36d727be19
	Mod Menu: 11.0.4
	Forgified Fabric API Lookup API (v1): 1.6.71+c290471319
	SuperMartijn642's Core Lib: 1.1.21
	Curios API: 9.5.1+1.21.1
	Replay Mod: 2.6.18
	Forgified Fabric Entity Events (v1): 1.8.0+5ede667619
	Architectury: 13.0.8
	LambDynamicLights (Runtime): 4.8.8+1.21.1
	Forgified Fabric Loot API (v2): 3.0.15+a3ee712d19
	Forgified Fabric Loot API (v3): 1.0.3+333dfad919
	Light Overlay: 12.0.0
	Forgified Fabric Rendering Data Attachment (v1): 0.3.49+73761d2e19
	Mod Sound Volume Options: 1.0.6-1.21
	Forgified Fabric Networking API (v1): 4.3.0+30a980d919
	Jade Addons: 6.1.0+neoforge
	Fancy Jukebox: 0.6.0
	Forgified Fabric Lifecycle Events (v1): 2.6.0+e40d8add19
	Forgified Fabric Key Binding API (v1): 1.0.47+62cc7ce119
	Forgified Fabric Client Tags: 1.1.15+e053909619
	Forgified Fabric Transfer API (v1): 5.4.3+a25cb45619
	Create: Copycats+: 3.0.4+mc.1.21.1-neoforge
	Forgified Fabric Model Loading API (v1): 2.1.0+6e8f52c719
	Just Enough Items: 19.27.0.340
	XaeroLib: 1.1.15
	Create Aeronautics: 1.2.1
	Forgified Fabric Screen Handler API (v1): 1.3.90+8dbc56dd19
	Forgified Fabric Resource Loader (v0): 1.3.1+4ea8954419
	Forgified Fabric Rendering (v1): 5.1.0+1a09bd5a19
	Forgified Fabric Renderer - Indigo: 1.7.1+9125b6dc19
	Traveler's Backpack: 10.1.35
	Bad Packets: 0.8.2
	Animatica: 0.6.1_1.21
	BetterJukebox: 1.1.0
	Create: Curios Backtank: 1.0.1
	Sodium: 0.6.13+mc1.21.1
	Forgified Fabric Particles (v1): 4.0.2+824f924c19
	Forgified Fabric Transitive Access Wideners (v1): 6.2.0+6c854b6f19
	Create Offroad: 1.2.1
	fps display: 1.0.0
	CompatDatapacks: 1.0.13.210-neoforge
	Forgified Fabric API Base: 0.4.42+d1308ded19
	Mouse Tweaks: 2.26.1
	Forgified Fabric BlockRenderLayer Registration (v1): 1.1.52+c290471319
	Jade: 15.10.5+neoforge
	Forgified Fabric Block API (v1): 1.1.0+b0c22bb819
	Sable: 1.2.2
	Forgified Fabric Resource Conditions API (v1): 4.3.0+5bdd099819
	Kotlin For Forge: 5.11.0
	Sable Companion: 1.6.0
	Xaero's Minimap: 25.3.13
	Forgified Fabric Item Group API (v1): 4.1.7+e324903319
	Forgified Fabric Game Test API (v1): 2.0.5+29f188ce19
	SpruceUI: 6.2.5+1.21.1
	Freecam: 1.3.0+mc1.21
	Yumi Minecraft Libraries: Foundation: 1.0.0-beta.1+1.21.1
	Forgified Fabric Biome API (v1): 13.0.31+1e62d33c19
	OptiGUI: 2.3.0-beta.9_1.21
	Forgified Fabric Registry Sync (v0): 5.3.1+f9aace1619
	LambDynamicLights (API): 4.8.8+1.21.1
	AppleSkin: 3.0.9+mc1.21
	Forgified Fabric Recipe API (v1): 5.0.15+59440bcc19
	Forgified Fabric Object Builder API (v1): 15.2.1+cc242efd19
	Just Zoom: 2.1.0
	Forgified Fabric Sound API (v1): 1.0.23+10b84f8419
	Forgified Fabric Message API (v1): 6.0.14+6a754fce19
	Forgified Fabric Data Generation API (v1): 20.2.34+a4c3605619
	Forgified Fabric API (dummy): 0.116.7+2.2.4+1.21.1
	Forgified Fabric Events Interaction (v0): 0.7.13+86e0887119
	Create Crafts & Additions: 1.5.11
```
</details>

### Log: 
https://mclo.gs/pjNcspR
