### ISSUE TITLE
ticking block entity crash when looking at replay when hbm machines are running 

### ISSUE THREAD

**Issue by Heketiitus** [ReplayMod/ReplayMod#836]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 4/3/23 6:41 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraft.world.World.func_189509_E(World.java:225)
	at net.minecraft.world.World.func_175625_s(World.java:2387)
	at com.hbm.lib.Library.ffgeua(Library.java:729)
	at com.hbm.tileentity.machine.TileEntityMachineCoal.ffgeua(TileEntityMachineCoal.java:240)
	at com.hbm.lib.Library.ffgeua(Library.java:772)
	at com.hbm.tileentity.machine.TileEntityMachineCoal.ffgeua(TileEntityMachineCoal.java:240)
	at com.hbm.lib.Library.ffgeua(Library.java:772)
	at com.hbm.tileentity.machine.TileEntityMachineCoal.ffgeua(TileEntityMachineCoal.java:240)
	at com.hbm.lib.Library.ffgeua(Library.java:770)
	at com.hbm.tileentity.machine.TileEntityMachineCoal.ffgeua(TileEntityMachineCoal.java:240)
	at com.hbm.lib.Library.ffgeua(Library.java:772)
	at com.hbm.tileentity.machine.TileEntityMachineCoal.ffgeua(TileEntityMachineCoal.java:240)
	at com.hbm.tileentity.machine.TileEntityMachineCoal.ffgeuaInit(TileEntityMachineCoal.java:248)
	at com.hbm.tileentity.machine.TileEntityMachineCoal.func_73660_a(TileEntityMachineCoal.java:108)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.world.World.func_189509_E(World.java:225)
	at net.minecraft.world.World.func_175625_s(World.java:2387)
	at com.hbm.lib.Library.ffgeua(Library.java:729)
	at com.hbm.tileentity.machine.TileEntityMachineCoal.ffgeua(TileEntityMachineCoal.java:240)
	at com.hbm.lib.Library.ffgeua(Library.java:772)
	at com.hbm.tileentity.machine.TileEntityMachineCoal.ffgeua(TileEntityMachineCoal.java:240)
	at com.hbm.lib.Library.ffgeua(Library.java:772)
	at com.hbm.tileentity.machine.TileEntityMachineCoal.ffgeua(TileEntityMachineCoal.java:240)
	at com.hbm.lib.Library.ffgeua(Library.java:770)
	at com.hbm.tileentity.machine.TileEntityMachineCoal.ffgeua(TileEntityMachineCoal.java:240)
	at com.hbm.lib.Library.ffgeua(Library.java:772)
	at com.hbm.tileentity.machine.TileEntityMachineCoal.ffgeua(TileEntityMachineCoal.java:240)
	at com.hbm.tileentity.machine.TileEntityMachineCoal.ffgeuaInit(TileEntityMachineCoal.java:248)
	at com.hbm.tileentity.machine.TileEntityMachineCoal.func_73660_a(TileEntityMachineCoal.java:108)

-- Block entity being ticked --
Details:
	Name: hbm:tileentity_machine_coal // com.hbm.tileentity.machine.TileEntityMachineCoal
	Block type: ID #823 (tile.machine_coal_off // com.hbm.blocks.machine.MachineCoal // hbm:machine_coal_off)
	Block data value: 4 / 0x4 / 0b0100
	Block location: World: (8,4,-6), Chunk: (at 8,0,10 in 0,-1; contains blocks 0,0,-16 to 15,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Actual block type: ID #823 (tile.machine_coal_off // com.hbm.blocks.machine.MachineCoal // hbm:machine_coal_off)
	Actual block data value: 4 / 0x4 / 0b0100
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1838)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [CameraEntity['Player'/-1789435, l='MpServer', x=-4.13, y=13.73, z=-10.78], EntityOtherPlayerMP['Heketiitus2'/45402, l='MpServer', x=-10.98, y=4.25, z=16.95]]
	Chunk stats: MultiplayerChunkCache: 1521, 1521
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (1691,4,75), Chunk: (at 11,0,11 in 105,4; contains blocks 1680,0,64 to 1695,255,79), Region: (3,0; contains chunks 96,0 to 127,31, blocks 1536,0,0 to 2047,255,511)
	Level time: 679354 game time, 1000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: spectator (ID 3). Hardcore: false. Cheats: false
	Forced entities: 25 total; [EntitySheep['Sheep'/1374353, l='MpServer', x=-36.54, y=4.00, z=1.20], EntitySheep['Sheep'/1373362, l='MpServer', x=-38.98, y=4.00, z=-24.81], EntitySheep['Sheep'/1374499, l='MpServer', x=-34.08, y=4.00, z=-13.48], EntitySheep['Sheep'/1372752, l='MpServer', x=7.51, y=4.00, z=58.99], EntitySheep['Sheep'/1373779, l='MpServer', x=-43.47, y=4.00, z=-1.04], EntitySheep['Sheep'/886211, l='MpServer', x=-14.53, y=4.00, z=-39.25], EntityCow['Cow'/342740, l='MpServer', x=43.17, y=4.00, z=22.28], EntityOtherPlayerMP['Heketiitus2'/45402, l='MpServer', x=-10.98, y=4.25, z=16.95], EntityItemFrame['entity.ItemFrame.name'/45404, l='MpServer', x=-11.97, y=5.50, z=-6.50], EntityItemFrame['entity.ItemFrame.name'/45405, l='MpServer', x=-11.97, y=5.50, z=-4.50], EntityItemFrame['entity.ItemFrame.name'/45406, l='MpServer', x=-11.97, y=5.50, z=-2.50], EntityItemFrame['entity.ItemFrame.name'/45407, l='MpServer', x=-11.97, y=5.50, z=-0.50], EntityItemFrame['entity.ItemFrame.name'/45408, l='MpServer', x=-11.97, y=5.50, z=5.50], CameraEntity['Player'/-1789435, l='MpServer', x=-4.13, y=13.73, z=-10.78], EntityItemFrame['entity.ItemFrame.name'/45409, l='MpServer', x=-11.97, y=5.50, z=3.50], EntityItemFrame['entity.ItemFrame.name'/45410, l='MpServer', x=-11.97, y=5.50, z=9.50], EntityItemFrame['entity.ItemFrame.name'/45411, l='MpServer', x=-11.97, y=5.50, z=7.50], EntitySheep['Sheep'/885870, l='MpServer', x=-47.27, y=4.00, z=15.69], EntityItemFrame['entity.ItemFrame.name'/45412, l='MpServer', x=-11.97, y=5.50, z=11.50], EntityItemFrame['entity.ItemFrame.name'/45413, l='MpServer', x=-4.03, y=5.50, z=9.50], EntityItemFrame['entity.ItemFrame.name'/45414, l='MpServer', x=-4.03, y=5.50, z=7.50], EntityItemFrame['entity.ItemFrame.name'/45415, l='MpServer', x=-4.03, y=5.50, z=11.50], EntityItemFrame['entity.ItemFrame.name'/45416, l='MpServer', x=-11.97, y=5.50, z=13.50], EntitySheep['Sheep'/1374049, l='MpServer', x=-50.49, y=4.00, z=17.35], EntitySheep['Sheep'/1372898, l='MpServer', x=-49.93, y=4.00, z=5.20]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 775305672 bytes (739 MB) / 2516582400 bytes (2400 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID              | Version      | Source                            | Signature                                |
	|:------ |:--------------- |:------------ |:--------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft       | 1.12.2       | minecraft.jar                     | None                                     |
	| LCHIJA | mcp             | 9.42         | minecraft.jar                     | None                                     |
	| LCHIJA | FML             | 8.0.99.99    | forge-1.12.2-14.23.5.2855.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge           | 14.23.5.2855 | forge-1.12.2-14.23.5.2855.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | replaymod       | 1.12.2-2.6.9 | replaymod-1.12.2-2.6.9.jar        | None                                     |
	| LCHIJA | backups         | 1.5.7        | Backups-1.12.2-1.5.7.jar          | None                                     |
	| LCHIJA | crafttweaker    | 4.1.20       | CraftTweaker2-1.12-4.1.20.687.jar | None                                     |
	| LCHIJA | ctgui           | 1.0.0        | CraftTweaker2-1.12-4.1.20.687.jar | None                                     |
	| LCHIJA | jei             | 4.16.1.302   | jei_1.12.2-4.16.1.302.jar         | None                                     |
	| LCHIJA | crafttweakerjei | 2.0.3        | CraftTweaker2-1.12-4.1.20.687.jar | None                                     |
	| LCHIJA | hbm             | hbm-1.8.3a-G | hbm-1.8.3a-G.jar                  | None                                     |

	Loaded coremods (and transformers): 
LoadingPlugin (replaymod-1.12.2-2.6.9.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 517.02' Renderer: 'NVIDIA GeForce RTX 3080/PCIe/SSE2'
	Launched Version: 1.12.2-forge-14.23.5.2855
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce RTX 3080/PCIe/SSE2 GL version 4.6.0 NVIDIA 517.02, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 16x Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz

**Comment by Johni0702** [comment]
This probably needs to be fixed in hbm. Please open an issue on their tracker.
