### ISSUE TITLE
ReplayMod crashing when receiving resource pack

### ISSUE THREAD

**Issue by NickAcPT** [ReplayMod/ReplayMod#86]
Minecraft version: `1.12.2`
Forge version (Not sure if this is important): `14.23.5.2768`
Version: `1.12.2-2.2.0-b7`

Crashes when I press yes on the prompt to download a resourcepack.

```
java.lang.ClassCastException: net.minecraft.client.resources.ResourcePackRepository cannot be cast to com.replaymod.recording.packet.ResourcePackRecorder$IDownloadingPackFinder
	at com.replaymod.recording.packet.ResourcePackRecorder.downloadResourcePack(ResourcePackRecorder.java:192)
	at com.replaymod.recording.packet.ResourcePackRecorder.downloadResourcePackFuture(ResourcePackRecorder.java:179)
	at com.replaymod.recording.packet.ResourcePackRecorder.access$000(ResourcePackRecorder.java:62)
	at com.replaymod.recording.packet.ResourcePackRecorder$1.func_73878_a(ResourcePackRecorder.java:159)
	at net.minecraft.client.gui.GuiYesNo.func_146284_a(SourceFile:50)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1758)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.replaymod.recording.packet.ResourcePackRecorder.downloadResourcePack(ResourcePackRecorder.java:192)
	at com.replaymod.recording.packet.ResourcePackRecorder.downloadResourcePackFuture(ResourcePackRecorder.java:179)
	at com.replaymod.recording.packet.ResourcePackRecorder.access$000(ResourcePackRecorder.java:62)
	at com.replaymod.recording.packet.ResourcePackRecorder$1.func_73878_a(ResourcePackRecorder.java:159)
	at net.minecraft.client.gui.GuiYesNo.func_146284_a(SourceFile:50)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiYesNo

```

**Comment by Johni0702** [comment]
Eh, I think I see what's going on.
I rarely test server resource packs and much less so on older versions and it appears like I broke it for 1.8-1.12.2 at some point during the 1.13/14 update.

You might be able to fix it yourself by removing the `//` before the `MixinDownloadingPackFinder` line in the `mixins.recording.replaymod.json` file inside the RM jar, unless something else is wrong as well (really not sure, would have to try).
