### ISSUE TITLE
Crash when opening Player Overview.

### ISSUE THREAD

**Issue by Magicrafter13** [ReplayMod/ReplayMod#868]
Quilt 1.20.1, can post full log if needed. Presumed relevant information below:

```
[22:47:43] [Render thread/INFO]: Clearing audio channels
[22:47:43] [Render thread/INFO]: Clearing unused audio channels
[22:47:43] [Render thread/INFO]: Minimap session finalized.
[22:47:43] [Render thread/INFO]: Finalizing world map session...
[22:47:43] [Thread-22/INFO]: World map force-cleaned!
[22:47:43] [Render thread/INFO]: World map session finalized.
[22:47:43] [Render thread/INFO]: Stopping worker threads
[22:47:43] [Render thread/INFO]: emissive suffixes loaded: {_e}
[22:47:43] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Gui Layout
	at net.minecraft.class_757.method_3192(class_757.java:954) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524) ~[quilt-loader-0.19.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82) ~[quilt-loader-0.19.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.19.2.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) ~[NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:889) ~[guava-31.1-jre.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3965) ~[guava-31.1-jre.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3989) ~[guava-31.1-jre.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4950) ~[guava-31.1-jre.jar:?]
	at pextystudios.emogg.emoji.EmojiFontRenderer.method_1727(EmojiFontRenderer.java:157) ~[transformed-mod-emogg.i0:0/:?]
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.AbstractGuiCheckbox.calcMinSize(AbstractGuiCheckbox.java:79) ~[transformed-mod-replaymod.i0:0/:?]
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.AbstractGuiElement.getMinSize(AbstractGuiElement.java:182) ~[transformed-mod-replaymod.i0:0/:?]
	at com.replaymod.lib.de.johni0702.minecraft.gui.layout.CustomLayout.layOut(CustomLayout.java:58) ~[transformed-mod-replaymod.i0:0/:?]
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiContainer.layout(AbstractGuiContainer.java:140) ~[transformed-mod-replaymod.i0:0/:?]
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiContainer.layout(AbstractGuiContainer.java:162) ~[transformed-mod-replaymod.i0:0/:?]
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiContainer.layout(AbstractGuiContainer.java:162) ~[transformed-mod-replaymod.i0:0/:?]
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiScrollable.layout(AbstractGuiScrollable.java:90) ~[transformed-mod-replaymod.i0:0/:?]
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiContainer.layout(AbstractGuiContainer.java:162) ~[transformed-mod-replaymod.i0:0/:?]
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiContainer.layout(AbstractGuiContainer.java:162) ~[transformed-mod-replaymod.i0:0/:?]
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiScreen.layout(AbstractGuiScreen.java:95) ~[transformed-mod-replaymod.i0:0/:?]
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiScreen$MinecraftGuiScreen.method_25394(AbstractGuiScreen.java:258) ~[transformed-mod-replaymod.i0:0/:?]
	at net.minecraft.class_437.method_47413(class_437.java:110) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_757.method_3192(class_757.java:945) ~[transformed-mod-minecraft.i0:0/:?]
	... 14 more
---- Minecraft Crash Report ----
// There are four lights!

Time: 2023-07-06 22:47:43
Description: Gui Layout

java.lang.NullPointerException: Gui Layout
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:889)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3965)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3989)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4950)
	at pextystudios.emogg.emoji.EmojiFontRenderer.method_1727(EmojiFontRenderer.java:157)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.AbstractGuiCheckbox.calcMinSize(AbstractGuiCheckbox.java:79)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.AbstractGuiElement.getMinSize(AbstractGuiElement.java:182)
	at com.replaymod.lib.de.johni0702.minecraft.gui.layout.CustomLayout.layOut(CustomLayout.java:58)
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiContainer.layout(AbstractGuiContainer.java:140)
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiContainer.layout(AbstractGuiContainer.java:162)
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiContainer.layout(AbstractGuiContainer.java:162)
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiScrollable.layout(AbstractGuiScrollable.java:90)
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiContainer.layout(AbstractGuiContainer.java:162)
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiContainer.layout(AbstractGuiContainer.java:162)
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiScreen.layout(AbstractGuiScreen.java:95)
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiScreen$MinecraftGuiScreen.method_25394(AbstractGuiScreen.java:258)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:889)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3965)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3989)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4950)
	at pextystudios.emogg.emoji.EmojiFontRenderer.method_1727(EmojiFontRenderer.java:157)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.AbstractGuiCheckbox.calcMinSize(AbstractGuiCheckbox.java:79)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.AbstractGuiElement.getMinSize(AbstractGuiElement.java:182)
Mixins in Stacktrace: None found

-- Render info details --
Details:
	Partial Tick: 0.0
	Mouse X: 98
	Mouse Y: 187
	Layer: 0
Stacktrace:
	at com.replaymod.lib.de.johni0702.minecraft.gui.RenderInfo.addTo(RenderInfo.java:55)
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiContainer.layout(AbstractGuiContainer.java:143)
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiContainer.layout(AbstractGuiContainer.java:162)
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiContainer.layout(AbstractGuiContainer.java:162)
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiScrollable.layout(AbstractGuiScrollable.java:90)
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiContainer.layout(AbstractGuiContainer.java:162)
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiContainer.layout(AbstractGuiContainer.java:162)
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiScreen.layout(AbstractGuiScreen.java:95)
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiScreen$MinecraftGuiScreen.method_25394(AbstractGuiScreen.java:258)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Mixins in Stacktrace:
	net.minecraft.class_437:
		com.replaymod.lib.de.johni0702.minecraft.gui.versions.mixin.MixinScreen (#replaymod:mixins.jgui.json)
		com.tterrag.blur.mixin.MixinScreen (#blur:mixins.blur.json)
		me.pieking1215.invmove.fabric_like.mixin.client.OverlayMixin (#invmove:invmove-fabric-like.mixins.json)
		com.replaymod.lib.de.johni0702.minecraft.gui.versions.mixin.Mixin_PassEventsExt (#replaymod:mixins.jgui.json)
		net.fabricmc.fabric.mixin.screen.ScreenMixin (#quilted_fabric_screen_api_v1:quilted_fabric_screen_api_v1.mixins.json)
		dev.architectury.mixin.fabric.client.MixinScreen (#architectury:architectury.mixins.json)
		me.pieking1215.invmove.mixin.client.BackgroundMixin (#invmove:invmove.mixins.json)
		com.replaymod.core.mixin.GuiScreenAccessor (mixins.core.replaymod.json)
		io.wispforest.owo.mixin.ui.layers.ScreenMixin (#owo:owo.mixins.json)
		fuzs.puzzleslib.mixin.client.ScreenFabricMixin (#puzzleslib:puzzleslib.fabric.mixins.json)
		eu.midnightdust.midnightcontrols.client.mixin.ScreenAccessor (#midnightcontrols:midnightcontrols.mixins.json)
		net.blay09.mods.balm.mixin.ScreenAccessor (#balm-fabric:balm.mixins.json)
		org.quiltmc.qsl.screen.mixin.client.ScreenMixin (#quilt_screen:quilt_screen.mixins.json)
		baritone.launch.mixins.MixinScreen (#baritone:mixins.baritone.json)
		bettercommandblockui.mixin.ScreenAccessor (#bettercommandblockui:bettercommandblockui.mixins.json)
	net.minecraft.class_757:
		nl.enjarai.doabarrelroll.mixin.roll.GameRendererMixin (#do_a_barrel_roll:do-a-barrel-roll.mixins.json)
		com.replaymod.render.mixin.Mixin_Omnidirectional_Rotation (mixins.render.replaymod.json)
		com.replaymod.render.mixin.Mixin_Stereoscopic_Camera (mixins.render.replaymod.json)
		dev.notalpha.dashloader.mixin.option.cache.shader.GameRendererMixin (#dashloader:dashloader.mixins.json)
		net.coderbot.iris.mixin.MixinModelViewBobbing (#iris:mixins.iris.json)
		com.nettakrim.spyglass_astronomy.mixin.GameRendererMixin (#spyglass_astronomy:spyglass_astronomy.mixins.json)
		xaero.common.mixin.MixinGameRenderer (#xaerominimap:xaerominimap.mixins.json)
		net.coderbot.iris.mixin.GameRendererAccessor (#iris:mixins.iris.json)
		com.replaymod.render.mixin.Mixin_Stereoscopic_HandRenderPass (mixins.render.replaymod.json)
		net.xolt.freecam.mixins.GameRendererMixin (#freecam:freecam.mixins.json)
		net.coderbot.iris.mixin.MixinTweakFarPlane (#iris:mixins.iris.json)
		dynamicfps.mixin.GameRendererMixin (#dynamicfps:dynamicfps.mixins.json)
		net.fabricmc.fabric.mixin.client.rendering.shader.GameRendererMixin (#quilted_fabric_rendering_v1:quilted_fabric_rendering_v1.mixins.json)
		org.quiltmc.qsl.screen.mixin.client.GameRendererMixin (#quilt_screen:quilt_screen.mixins.json)
		com.replaymod.render.mixin.MixinEntityRenderer (mixins.render.replaymod.json)
		eu.midnightdust.midnightcontrols.client.mixin.GameRendererMixin (#midnightcontrols:midnightcontrols.mixins.json)
		org.quiltmc.qsl.resource.loader.mixin.client.KeyedClientResourceReloaderMixin (#quilt_resource_loader:quilt_resource_loader.mixins.json)
		net.raphimc.immediatelyfast.injection.mixins.core.compat.MixinGameRenderer (#immediatelyfast:immediatelyfast.mixins.json)
		xaero.map.mixin.MixinGameRenderer (#xaeroworldmap:xaeroworldmap.mixins.json)
		com.replaymod.replay.mixin.Mixin_ShowSpectatedHand_NoOF (mixins.replay.replaymod.json)
		snownee.jade.mixin.GameRendererMixin (#jade:jade.mixins.json)
		io.wispforest.owo.mixin.shader.GameRendererMixin (#owo:owo.mixins.json)
		fuzs.puzzleslib.mixin.client.GameRendererFabricMixin (#puzzleslib:puzzleslib.fabric.mixins.json)
		com.replaymod.render.mixin.Mixin_PreserveDepthDuringGuiRendering (mixins.render.replaymod.json)
		com.logicalgeekboy.logical_zoom.mixin.LogicalZoomMixin (#logical_zoom:logical_zoom.client-mixins.json)
		me.flashyreese.mods.sodiumextra.mixin.prevent_shaders.MixinGameRenderer (#sodium-extra:sodium-extra.mixins.json)
		com.replaymod.render.mixin.Mixin_Omnidirectional_Camera (mixins.render.replaymod.json)
		com.replaymod.render.mixin.Mixin_PreserveDepthDuringHandRendering (mixins.render.replaymod.json)
		com.replaymod.compat.shaders.mixin.MixinShaderEntityRenderer (mixins.compat.shaders.replaymod.json)
		ladysnake.satin.mixin.client.event.GameRendererMixin (#satin:mixins.satin.client.json)
		com.replaymod.replay.mixin.MixinCamera (mixins.replay.replaymod.json)
		dev.architectury.mixin.fabric.client.MixinGameRenderer (#architectury:architectury.mixins.json)
		com.replaymod.render.mixin.GameRendererAccessor (mixins.render.replaymod.json)
		net.coderbot.iris.mixin.MixinGameRenderer (#iris:mixins.iris.json)
		net.coderbot.iris.mixin.MixinGameRenderer_NightVisionCompat (#iris:mixins.iris.json)
		com.replaymod.core.mixin.MixinGameRenderer (mixins.core.replaymod.json)
		com.replaymod.lib.de.johni0702.minecraft.gui.versions.mixin.MixinGameRenderer (#replaymod:mixins.jgui.json)
	net.minecraft.class_310:
		net.coderbot.iris.mixin.MixinMinecraft_Images (#iris:mixins.iris.json)
		net.celeri.dynmus.mixin.MinecraftClientMixin (#dynmus:dynmus-common.mixins.json)
		traben.entity_texture_features.mixin.reloading.MixinMinecraftClient (#entity_texture_features:entity_texture_features-common.mixins.json)
		com.blamejared.ambientenvironment.mixin.MixinMinecraft (#ambientenvironment:ambientenvironment.fabric.mixins.json)
		com.replaymod.core.mixin.MinecraftAccessor (mixins.core.replaymod.json)
		de.maxhenkel.voicechat.mixin.MinecraftMixin (#voicechat:voicechat.mixins.json)
		malte0811.ferritecore.mixin.fabric.MinecraftMixin (#ferritecore:ferritecore.fabric.mixin.json)
		dev.tr7zw.itemswapper.mixin.MinecraftMixin (#itemswapper:itemswapper.mixins.json)
		ca.fxco.memoryleakfix.mixin.customPayloadLeak.Minecraft_freeBufferMixin (#memoryleakfix:memoryleakfix-fabric.mixins.json)
		dev.architectury.mixin.fabric.client.MixinMinecraft (#architectury:architectury.mixins.json)
		com.replaymod.lib.de.johni0702.minecraft.gui.versions.mixin.Mixin_PassEvents_HandleKeybinds (#replaymod:mixins.jgui.json)
		eu.midnightdust.midnightcontrols.client.mixin.MinecraftClientMixin (#midnightcontrols:midnightcontrols.mixins.json)
		ca.fxco.memoryleakfix.mixin.hugeScreenshotLeak.Minecraft_screenshotMixin (#memoryleakfix:memoryleakfix.mixins.json)
		opekope2.optigui.mixin.MinecraftClientMixin (#optigui:optigui.mixins.json)
		xaero.map.mixin.MixinMinecraftClient (#xaeroworldmap:xaeroworldmap.mixins.json)
		me.jellysquid.mods.sodium.mixin.workarounds.issue1486.MixinMinecraftClient (#sodium:sodium.mixins.json)
		ladysnake.satin.mixin.client.event.MinecraftClientMixin (#satin:mixins.satin.client.json)
		pextystudios.emogg.mixin.MinecraftMixin (#emogg:emogg.mixins.json)
		com.tterrag.blur.mixin.MixinMinecraftClient (#blur:mixins.blur.json)
		org.quiltmc.qsl.screen.mixin.client.MinecraftClientMixin (#quilt_screen:quilt_screen.mixins.json)
		io.github.thecsdev.tcdcommons.client.mixin.events.MixinMinecraftClient (#tcdcommons:tcdcommons.client.mixin.events.json)
		org.quiltmc.qsl.command.mixin.client.MinecraftClientMixin (#quilt_client_command:quilt_client_command.mixins.json)
		baritone.launch.mixins.MixinMinecraft (#baritone:mixins.baritone.json)
		traben.entity_texture_features.mixin.reloading.MixinResourceReload (#entity_texture_features:entity_texture_features-common.mixins.json)
		me.jellysquid.mods.sodium.mixin.core.MixinMinecraftClient (#sodium:sodium.mixins.json)
		com.replaymod.core.mixin.MixinMinecraft (mixins.core.replaymod.json)
		org.quiltmc.qsl.lifecycle.mixin.client.MinecraftClientMixin (#quilt_lifecycle_events:quilt_lifecycle_events.mixins.json)
		com.aizistral.nochatreports.common.mixins.client.MixinMinecraft (#nochatreports:mixins/common/nochatreports.mixins.json)
		net.blay09.mods.balm.mixin.MinecraftMixin (#balm-fabric:balm.mixins.json)
		dev.notalpha.dashloader.mixin.main.MinecraftClientMixin (#dashloader:dashloader.mixins.json)
		opekope2.optigui.mixin.MinecraftClientMixin2 (#optigui:optigui.mixins.json)
		net.fabricmc.fabric.mixin.datagen.client.MinecraftClientMixin (#quilted_fabric_data_generation_api_v1:quilted_fabric_data_generation_api_v1.client.mixins.json)
		me.ramidzkh.fabrishot.mixins.MinecraftClientMixin (#fabrishot:mixins.fabrishot.json)
		me.lucko.spark.fabric.mixin.MinecraftClientAccessor (#spark:spark.mixins.json)
		com.replaymod.render.mixin.Mixin_SuppressFramebufferResizeDuringRender (mixins.render.replaymod.json)
		org.quiltmc.qsl.networking.mixin.accessor.MinecraftClientAccessor (#quilt_networking:quilt_networking.mixins.json)
		xaero.pac.common.mixin.MixinMinecraft (#openpartiesandclaims:openpartiesandclaims.mixins.json)
		net.fabricmc.fabric.mixin.event.interaction.client.MinecraftClientMixin (#quilted_fabric_events_interaction_v0:quilted_fabric_events_interaction_v0.client.mixins.json)
		dev.lambdaurora.spruceui.mixin.MinecraftClientMixin (#spruceui:spruceui.mixins.json)
		io.wispforest.owo.mixin.MinecraftClientMixin (#owo:owo.mixins.json)
		xaero.common.mixin.MixinMinecraftClient (#xaerominimap:xaerominimap.mixins.json)
		com.nettakrim.spyglass_astronomy.mixin.MinecraftClientMixin (#spyglass_astronomy:spyglass_astronomy.mixins.json)
		randommcsomethin.fallingleaves.mixin.MinecraftClientMixin (#fallingleaves:fallingleaves.mixins.json)
		fuzs.forgeconfigapiport.mixin.client.MinecraftMixin (#forgeconfigapiport:forgeconfigapiport.common.mixins.json)
		dev.lambdaurora.lambdynlights.mixin.MinecraftClientMixin (#lambdynlights:lambdynlights.mixins.json)
		net.xolt.freecam.mixins.MinecraftClientMixin (#freecam:freecam.mixins.json)
		net.fabricmc.fabric.mixin.registry.sync.client.MinecraftClientMixin (#quilted_fabric_registry_sync_v0:quilted_fabric_registry_sync_v0.client.mixins.json)
		xaeroplus.mixin.client.mc.MixinMinecraftClient (#xaeroplus:xaeroplus.mixins.json)
		org.quiltmc.qsl.resource.loader.mixin.client.MinecraftClientMixin (#quilt_resource_loader:quilt_resource_loader.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_PipelineManagement (#iris:mixins.iris.json)
		ca.fxco.memoryleakfix.mixin.targetEntityLeak.Minecraft_targetClearMixin (#memoryleakfix:memoryleakfix.mixins.json)
		com.aizistral.nochatreports.fabric.mixins.client.MixinMinecraft (#nochatreports:mixins/fabric/nochatreports-fabric.mixins.json)
		shcm.shsupercm.fabric.citresewn.defaults.mixin.types.enchantment.MinecraftClientMixin (#citresewn-defaults:citresewn-defaults.mixins.json)
		io.wispforest.owo.mixin.ui.MinecraftClientMixin (#owo:owo.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_Keybinds (#iris:mixins.iris.json)
		dev.isxander.yacl3.mixin.MinecraftMixin (#yet_another_config_lib_v3:yacl.mixins.json)
		me.axieum.mcmod.authme.mixin.MinecraftClientAccessor (#authme:authme.mixins.json)
		com.replaymod.lib.de.johni0702.minecraft.gui.versions.mixin.MixinMinecraft (#replaymod:mixins.jgui.json)
		dev.kikugie.elytratrims.mixin.client.MinecraftClientMixin (#elytratrims:elytratrims.client.mixins.json)
		fuzs.puzzleslib.mixin.client.MinecraftFabricMixin (#puzzleslib:puzzleslib.fabric.mixins.json)
		org.quiltmc.qsl.base.mixin.client.MinecraftClientMixin (#quilt_base:quilt_base.mixins.json)
		me.flashyreese.mods.sodiumextra.mixin.gui.MinecraftClientAccessor (#sodium-extra:sodium-extra.mixins.json)
		dzwdz.chat_heads.mixin.MinecraftMixin (#chat_heads:chat_heads.mixins.json)
		org.quiltmc.qsl.registry.mixin.client.MinecraftClientMixin (#quilt_registry:quilt_registry.mixins.json)
		fuzs.puzzleslib.mixin.client.accessor.MinecraftFabricAccessor (#puzzleslib:puzzleslib.fabric.mixins.json)
	net.minecraft.client.main.Main:
		link.infra.screenshotclipboard.common.mixin.AWTHackMixin (#screenshotclipboard:screenshotclipboard-common.mixins.json)
		dev.notalpha.dashloader.mixin.main.MainMixin (#dashloader:dashloader.mixins.json)
		com.github.getchoo.smoothboot.mixin.client.MainMixin (#threadtweak:smoothboot.mixins.json)

-- Gui container details --
Details:
	Container: com.replaymod.lib.de.johni0702.minecraft.gui.container.GuiPanel@49f96d75
	Layout: com.replaymod.extras.playeroverview.PlayerOverviewGui$8@37bc36f5

-- Screen render details --
Details:
	Screen name: com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiScreen.MinecraftGuiScreen
	Mouse location: Scaled: (427, 236). Absolute: (1280.000000, 708.000000)
	Screen size: Scaled: (854, 472). Absolute: (2560, 1416). Scale factor of 3.000000

-- Affected level --
Details:
	All players: 2 total; [CameraEntity['Magicrafter13'/-1789435, l='ClientLevel', x=-228.22, y=63.00, z=580.45], class_745['Magicrafter13'/449921, l='ClientLevel', x=-6.42, y=64.00, z=1.67]]
	Chunk stats: 16384, 1529
	Level dimension: minecraft:the_nether
	Level spawn location: World: (0,74,32), Section: (at 0,10,0 in 0,4,2; chunk contains blocks 0,0,32 to 15,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 10061101 game time, 11080667 day time
	Server brand: quilt
	Server type: Non-integrated multiplayer server

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, bedrockwaters/resources, elytratrims/default, itemswapper/default, lambdabettergrass/default, minecraft/supporteatinganimation, seasons/seasonal_lush_caves, visualoverhaul/coloredwaterbucket, visualoverhaul/fancyfurnace, visualoverhaul/nobrewingbottles, visualoverhaul/rounddiscs, file/BetterVanillaBuildingV2.89.zip, axolotlbuckets/axolotl-buckets-small, black_icons, file/BVB Eating Animations.zip, file/BVBDarkGUI old.zip, file/Bright Ores v2.2 (PinkLapis).zip, file/BushyBiomesV2.5.2.zip, file/BvBOverlaysV5.2.zip, file/Incendium_Optional_Resourcepack_1.20.1_v5.3.7.zip, file/RESOURCEPACK - Butterflies and Dragonflies.zip, file/Stefan'sEnchantedBooks 1.20.zip, file/twemogg.zip, continuity/glass_pane_culling_fix, replaymod_lang
```

**Comment by Kepler-17c** [comment]
Please try without the mod that adds emoji - if it doesn't work, please send you full log in our official support Discord server (link on our website).

**Comment by Magicrafter13** [comment]
Wow. I would *never* have expected that mod of all things to cause an issue :sweat_smile:.
