### ISSUE TITLE
Can't export video

### ISSUE THREAD

**Issue by Chloe932** [ReplayMod/ReplayMod#871]
exit code: 255

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2023-07-08 20:21:11
Description: Exporting video

com.replaymod.render.FFmpegWriter$FFmpegStartupException
	at com.replaymod.render.FFmpegWriter.getVideoFile(FFmpegWriter.java:163)
	at com.replaymod.render.FFmpegWriter.consume(FFmpegWriter.java:121)
	at com.replaymod.render.rendering.VideoRenderer$1.consume(VideoRenderer.java:159)
	at com.replaymod.render.rendering.Pipeline$ParallelSafeConsumer.consume(Pipeline.java:150)
	at com.replaymod.render.rendering.Pipeline$ProcessTask.run(Pipeline.java:118)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.replaymod.render.gui.GuiExportFailed.tryToRecover(GuiExportFailed.java:34)

-- Export details --
Details:
	Settings: RenderSettings{renderMethod=Default Rendering, encodingPreset=MP4 - Potato Quality, videoWidth=1920, videoHeight=1080, framesPerSecond=60, bitRate=15728640, outputFile=/Library/Video/2023_07_08_20_14_28.mp4, renderNameTags=false, includeAlphaChannel=false, stabilizeYaw=false, stabilizePitch=false, stabilizeRoll=false, chromaKeyingColor=null, sphericalFovX=360, sphericalFovY=180, injectSphericalMetadata=false, depthMap=false, cameraPathExport=false, antiAliasing=None, exportCommand='', exportArgumentsPreBgra='', exportArguments='-y -f rawvideo -pix_fmt bgra -s %WIDTH%x%HEIGHT% -r %FPS% -i - %FILTERS%-an -c:v libx264 -preset ultrafast -crf 51 -pix_fmt yuv420p "%FILENAME%"', highPerformance=false}
	FFmpeg log: ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers
  built with Apple clang version 14.0.3 (clang-1403.0.22.14.1)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/6.0 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Input #0, rawvideo, from 'fd:':
  Duration: N/A, start: 0.000000, bitrate: 3981312 kb/s
  Stream #0:0: Video: rawvideo (BGRA / 0x41524742), bgra, 1920x1080, 3981312 kb/s, 60 tbr, 60 tbn
2023_07_08_20_14_28.mp4: Permission denied

Stacktrace:
	at com.replaymod.render.gui.GuiExportFailed.tryToRecover(GuiExportFailed.java:34)
	at com.replaymod.render.gui.GuiRenderSettings$7.run(GuiRenderSettings.java:247)
	at com.replaymod.core.versions.scheduler.SchedulerImpl.lambda$runLater$3(SchedulerImpl.java:113)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at com.replaymod.core.versions.scheduler.SchedulerImpl$ReplayModExecutor.method_5383(SchedulerImpl.java:78)
	at com.replaymod.core.versions.scheduler.SchedulerImpl.runTasks(SchedulerImpl.java:85)
	at com.replaymod.core.ReplayMod.runTasks(ReplayMod.java:222)
	at com.replaymod.replay.InputReplayTimer.method_1658(InputReplayTimer.java:67)
	at net.minecraft.class_310.method_1523(class_310.java:1172)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Mac OS X (aarch64) version 13.2.1
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 293726440 bytes (280 MiB) / 838860800 bytes (800 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: Apple Inc.
	Processor Name: Apple M1
	Identifier: Apple Inc. Family 0x1b588bb3 Model 0 Stepping 0
	Microarchitecture: ARM64 SoC: Firestorm + Icestorm
	Frequency (GHz): 3.20
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Apple M1
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 8192.00
	Virtual memory used (MB): 6000.89
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

**Comment by Kepler-17c** [comment]
It says "permission denied" - FFmpeg isn't allowed to write to the location you specified. Please try the default location `.minecraft/replay_videos/`.

If that doesn't help or you have further questions, please use our official support Discord (invite link on our website).

**Comment by Chloe932** [comment]
hi thank you how would I go about doing this?

**Comment by ygerlach** [comment]
> hi thank you how would I go about doing this?

Choose a different place for the output file.
