### ISSUE TITLE
Error replay mod crasheo al ver las repeticiones.

### ISSUE THREAD

**Issue by dannzm** [ReplayMod/ReplayMod#925]
hola tengo un problema con "replay mod" y es que trato de entrar a una repetición se crashea al momento de ver la repetición ya me había pasado antes, pero después se solucionó solo, pero esta vez no me deja ver ninguna repetición, solo una pero no pasa de 10 minutos por que se  crashea, cabe recalcar que he tenido varios mods instalados y he podido ver las repeticiones como siempre, pero estos últimos días no me han dejado ver nada, no sé si sea por los mods, también  he asignado más RAM al juego y tampoco y aproximadamente todas las repeticiones duran entre 1 a 5 horas seguidas. por favor si alguien me puede ayudar se lo agradecería mucho. 

Aquí está el código de error cuando me saca del juego:
The game crashed whilst ticking entity
Error: java.lang.IllegalStateException: Config property is not linked yet. 

Y aquí el informe de error: 
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2023-12-25 17:42:13
Description: Ticking entity

java.lang.IllegalStateException: Config property is not linked yet
	at com.mrcrayfish.framework.api.config.AbstractProperty.get(AbstractProperty.java:89)
	at com.mrcrayfish.goblintraders.entity.GoblinTrader.method_5970(GoblinTrader.java:81)
	at net.minecraft.class_1308.method_5975(class_1308.java:301)
	at net.minecraft.class_1308.method_5670(class_1308.java:288)
	at com.mrcrayfish.goblintraders.entity.AbstractGoblinEntity.method_5670(AbstractGoblinEntity.java:147)
	at net.minecraft.class_1297.method_5773(class_1297.java:474)
	at net.minecraft.class_1309.method_5773(class_1309.java:2380)
	at net.minecraft.class_1308.method_5773(class_1308.java:351)
	at net.minecraft.class_638.method_18646(class_638.java:272)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_638.method_32124(class_638.java:255)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:251)
	at net.minecraft.class_310.method_1574(class_310.java:1901)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mrcrayfish.framework.api.config.AbstractProperty.get(AbstractProperty.java:89)
	at com.mrcrayfish.goblintraders.entity.GoblinTrader.method_5970(GoblinTrader.java:81)
	at net.minecraft.class_1308.method_5975(class_1308.java:301)
	at net.minecraft.class_1308.method_5670(class_1308.java:288)
	at com.mrcrayfish.goblintraders.entity.AbstractGoblinEntity.method_5670(AbstractGoblinEntity.java:147)
	at net.minecraft.class_1297.method_5773(class_1297.java:474)
	at net.minecraft.class_1309.method_5773(class_1309.java:2380)
	at net.minecraft.class_1308.method_5773(class_1308.java:351)
	at net.minecraft.class_638.method_18646(class_638.java:272)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_638.method_32124(class_638.java:255)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:251)

-- Entity being ticked --
Details:
	Entity Type: goblintraders:goblin_trader (com.mrcrayfish.goblintraders.entity.GoblinTrader)
	Entity ID: 2380
	Entity Name: Goblin Trader
	Entity's Exact location: 41.72, 21.00, 157.31
	Entity's Block location: World: (41,21,157), Section: (at 9,5,13 in 2,1,9; chunk contains blocks 32,-64,144 to 47,319,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.00, -0.06, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_638.method_32124(class_638.java:255)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:251)
	at net.minecraft.class_310.method_1574(class_310.java:1901)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 2 total; [CameraEntity['DannyMzgnn'/-1789435, l='ClientLevel', x=44.76, y=64.00, z=95.57], class_745['DannyMzgnn'/2475, l='ClientLevel', x=44.76, y=64.00, z=95.57]]
	Chunk stats: 1024, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (-32,85,48), Section: (at 0,5,0 in -2,5,3; chunk contains blocks -32,-64,48 to -17,319,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 1378496 game time, 2117478 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:821)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, file/qu33n-isab3l.zip, replaymod_lang

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 884999784 bytes (844 MiB) / 1979711488 bytes (1888 MiB) up to 3221225472 bytes (3072 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600X 6-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 3.69
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2504
	Graphics card #0 versionInfo: DriverVersion=31.0.15.4601
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 18760.30
	Virtual memory used (MB): 11435.02
	Swap memory total (MB): 2432.00
	Swap memory used (MB): 48.69
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		architectury: Architectury 9.1.12
		awesomedungeonnether: Awesome dungeon nether 3.1.1
		bclib: BCLib 3.0.13
			wunderlib: WunderLib 1.1.5
		betterend: Better End 4.0.10
		bookshelf: Bookshelf 20.1.6
		chimes: Chimes 2.0.1
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		creativecore: CreativeCore 2.11.10
			net_minecraftforge_eventbus: eventbus 6.0.3
		darkpaintings: DarkPaintings 17.0.4
		durabilitytooltip: Durability Tooltip 1.1.5
		endermanoverhaul: Enderman Overhaul 1.0.3
		fabric-api: Fabric API 0.87.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.2.2+1e61dba177
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.2+6bdb2ed077
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.2+6bdb2ed077
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.0+cdf060b277
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.10+kotlin.1.9.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.22.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.0
		fabricloader: Fabric Loader 0.14.25
		framework: Framework 0.6.16
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			org_javassist_javassist: javassist 3.29.2-GA
			org_reflections_reflections: reflections 0.10.2
		friendsandfoes: Friends&Foes 1.9.2
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.8
		geckolib: Geckolib 4.2.3
			com_eliotlash_mclib_mclib: mclib 20
		goblintraders: Goblin Traders 1.9.0
		inventoryprofilesnext: Inventory Profiles Next 1.10.6
		iris: Iris 1.6.10
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		journeymap: Journeymap 5.9.14
			journeymap-api-fabric: JourneyMap API 1.20-1.9-fabric-SNAPSHOT
		libipn: libIPN 3.0.2
		libraryferret: Library ferret 4.0.0
		minecraft: Minecraft 1.20.1
		onlyhammers: OnlyHammers 1.20.1-0.6
		replaymod: Replay Mod 1.20.1-2.6.13
		resourcefulconfig: Resourcefulconfig 2.1.0
		resourcefullib: Resourceful Lib 2.1.16
			com_teamresourceful_bytecodecs: bytecodecs 1.0.2
			com_teamresourceful_yabn: yabn 1.0.3
		roughlyenoughitems: Roughly Enough Items 12.0.672
			error_notifier: Error Notifier 1.0.9
		sit: Sit 1.20-24
		sodium: Sodium 0.5.3
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8+a
		terralith: Terralith 2.4.5
		wi_zoom: WI Zoom 1.5-MC1.20.1
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.25-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 3.2.0 NVIDIA 546.01, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, file/qu33n-isab3l.zip (incompatible)
	Current Language: es_mx
	CPU: 12x AMD Ryzen 5 5600X 6-Core Processor 

por favor si alguien sabe algo de cómo solucionarlo se lo agradecería mucho, estas grabaciones son muy importantes para mi.

**Comment by dannzm** [comment]
.
