### ISSUE TITLE
Crash during the saving replay file

### ISSUE THREAD

**Issue by XlAlbertlX** [ReplayMod/ReplayMod#932]
I periodically encounter crashes when I record videos on the server. Moreover, after the first crash, the error disappears. What could be the problem?
```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 1/28/24, 1:21 PM
Description: Saving replay file

java.io.IOException: Expected 0 sky light sections but got 18
	at com.replaymod.replaystudio.protocol.packets.PacketUpdateLight.readData(PacketUpdateLight.java:115)
	at com.replaymod.replaystudio.protocol.packets.PacketChunkData.readLoad(PacketChunkData.java:344)
	at com.replaymod.replaystudio.protocol.packets.PacketChunkData.read(PacketChunkData.java:59)
	at com.replaymod.replaystudio.filter.SquashFilter.onPacket(SquashFilter.java:393)
	at com.replaymod.editor.gui.MarkerProcessor.apply(MarkerProcessor.java:217)
	at com.replaymod.recording.packet.PacketListener.lambda$channelInactive$6(PacketListener.java:310)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1928452312 bytes (1839 MiB) / 4026531840 bytes (3840 MiB) up to 10468982784 bytes (9984 MiB)
	CPUs: 6
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.81
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: NVIDIA GeForce RTX 2060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f08
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3742
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 25018.40
	Virtual memory used (MB): 20375.02
	Swap memory total (MB): 8718.26
	Swap memory used (MB): 945.70
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx9983M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	OptiFine Version: OptiFine_1.18.2_HD_U_H9
	OptiFine Build: 20230626-134040
	Render Distance Chunks: 32
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 NVIDIA 537.42
	OpenGlRenderer: NVIDIA GeForce RTX 2060/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 6

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.18.2
	OptiFine jar version: OptiFine_1.18.2_HD_U_H9
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:/Users/holde/AppData/Roaming/.minecraft/.optifine/OptiFine_1.18.2_HD_U_H9/Optifine-mapped.jar
	OptiFabric error: <None>
```

**Comment by Johni0702** [comment]
If you're still having trouble with this, please find the corresponding "raw" replay in `.mincraft/replay_recordings/raw/` and attach it to this issue so I can try to debug it.

**Comment by Bomicz** [comment]
Got the same issue.
[2024_09_23_16_21_08.zip](https://github.com/user-attachments/files/17099024/2024_09_23_16_21_08.zip)

> ---- Minecraft Crash Report ----
// There are four lights!

Time: 2024-09-23 16:21:46
Description: Saving replay file

java.io.IOException: Expected 0 sky light sections but got 18
	at com.replaymod.replaystudio.protocol.packets.PacketUpdateLight.readData(PacketUpdateLight.java:115)
	at com.replaymod.replaystudio.protocol.packets.PacketChunkData.readLoad(PacketChunkData.java:355)
	at com.replaymod.replaystudio.protocol.packets.PacketChunkData.read(PacketChunkData.java:60)
	at com.replaymod.replaystudio.filter.SquashFilter.onPacket(SquashFilter.java:387)
	at com.replaymod.editor.gui.MarkerProcessor.apply(MarkerProcessor.java:218)
	at com.replaymod.recording.packet.PacketListener.lambda$channelInactive$6(PacketListener.java:327)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1100654320 bytes (1049 MiB) / 2080374784 bytes (1984 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5700X 8-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 3.40
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon RX 7800 XT
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x747e
	Graphics card #0 versionInfo: DriverVersion=31.0.24033.1003
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 3.20
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 3.20
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 41910.04
	Virtual memory used (MB): 24620.70
	Swap memory total (MB): 9216.00
	Swap memory used (MB): 84.72
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric-api: Fabric API 0.76.0+1.19.3
			fabric-api-base: Fabric API Base 0.4.21+70be179c85
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.20+49abcf7e85
			fabric-biome-api-v1: Fabric Biome API (v1) 12.1.2+f1c68e5885
			fabric-block-api-v1: Fabric Block API (v1) 1.0.5+e022e5d185
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.31+928d44d585
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.12+1134c5b885
			fabric-command-api-v1: Fabric Command API (v1) 1.2.22+f71b366f85
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+3fc4752e85
			fabric-commands-v0: Fabric Commands (v0) 0.2.39+df3654b385
			fabric-containers-v0: Fabric Containers (v0) 0.1.47+df3654b385
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.2+1d37d50285
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+521b5c5285
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.14+aeb40ebe85
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.3.2+40dc7a9485
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.42+00a2eb1085
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.7+b83334a085
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.40+3baeb27a85
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.45+df3654b385
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.30+99f9db8085
			fabric-item-api-v1: Fabric Item API (v1) 2.1.11+71b8257385
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.13+b5470ac785
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.31+bc01e09785
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.29+df3654b385
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.10+23a79c8a85
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.21+75e9821185
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.25+9e7660c685
			fabric-message-api-v1: Fabric Message API (v1) 5.1.0+c85585f885
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.32+49abcf7e85
			fabric-models-v0: Fabric Models (v0) 0.3.27+11ba9c3b85
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.17+4017a8cb85
			fabric-networking-v0: Fabric Networking (v0) 0.3.34+df3654b385
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.4.2+eb2a3ba985
			fabric-particles-v1: Fabric Particles (v1) 1.0.20+f1e4495b85
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+5176f73d85
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.1.0+f7b4d36485
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.2+3a95925a85
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.8.0+3a95925a85
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.31+df3654b385
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.25+afca2f3e85
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.18+f1e4495b85
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.34+df3654b385
			fabric-rendering-v1: Fabric Rendering (v1) 1.13.0+ad17775585
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.0+e63306e085
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.0+68296ad585
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.41+f1e4495b85
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.13+99f9db8085
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.8+75e9821185
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.15+ccd377ba85
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.3.1+40dc7a9485
		fabricloader: Fabric Loader 0.15.7
			mixinextras: MixinExtras 0.3.5
		fpsreducer: FPS Reducer 1.19.3-2.2
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.19.3
		modmenu: Mod Menu 5.1.0
		optifabric: OptiFabric 1.14.3
			mm: Manningham Mills 2.3
			optifabric-libs: OptiFabric Libraries 1.14.3
		perspectivemod: Perspective Mod Redux 0.0.5_01
			cloth-config2: Cloth Config v4 5.0.34
				cloth-basic-math: Cloth Basic Math 0.5.1
		replaymod: Replay Mod 1.19.3-2.6.14
	OptiFine Version: OptiFine_1.19.3_HD_U_I3
	OptiFine Build: 20230324-184409
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 Core Profile Context 24.5.1.240502
	OpenGlRenderer: AMD Radeon RX 7800 XT
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 16

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.19.3
	OptiFine jar version: OptiFine_1.19.3_HD_U_I3
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:/Users/hiroshi/AppData/Roaming/.minecraft/.optifine/OptiFine_1.19.3_HD_U_I3/Optifine-mapped.jar
	OptiFabric error: <None>
