### ISSUE TITLE
Not saved replays

### ISSUE THREAD

**Issue by jabaGR** [ReplayMod/ReplayMod#956]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2024-04-21 22:33:06
Description: Saving replay file

java.io.IOException: Expected 0 sky light sections but got 18
	at com.replaymod.replaystudio.protocol.packets.PacketUpdateLight.readData(PacketUpdateLight.java:115)
	at com.replaymod.replaystudio.protocol.packets.PacketChunkData.readLoad(PacketChunkData.java:355)
	at com.replaymod.replaystudio.protocol.packets.PacketChunkData.read(PacketChunkData.java:60)
	at com.replaymod.replaystudio.filter.SquashFilter.onPacket(SquashFilter.java:405)
	at com.replaymod.editor.gui.MarkerProcessor.apply(MarkerProcessor.java:215)
	at com.replaymod.recording.packet.PacketListener.lambda$channelInactive$6(PacketListener.java:327)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 303831000 bytes (289 MiB) / 1241513984 bytes (1184 MiB) up to 2113929216 bytes (2016 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i5-12450H
	Identifier: Intel64 Family 6 Model 154 Stepping 3
	Microarchitecture: Alder Lake
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3050 Laptop GPU
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x25a2
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1181
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x46a3
	Graphics card #1 versionInfo: DriverVersion=31.0.101.3358
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 22896.49
	Virtual memory used (MB): 13774.45
	Swap memory total (MB): 15000.00
	Swap memory used (MB): 515.07
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx1988M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		citresewn: CIT Resewn 1.1.4+1.20.4
			citresewn-defaults: CIT Resewn: Defaults 1.1.4+1.20.4
		clientcommands: Client Commands 2.8.13
			betterconfig: BetterConfig 1.2.1
			clientarguments: clientarguments 1.7
			net_fabricmc_mapping-io: mapping-io 0.5.1
		emotecraft: Emotecraft 2.4.0-a.f140890e
			bendy-lib: Bendy api 4.1.0
		fabric-api: Fabric API 0.96.11+1.20.4
			fabric-api-base: Fabric API Base 0.4.36+78d798af4f
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.49+82b1bb3e4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.16+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.16+3e2216cb4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.4+78d798af4f
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.46+78d798af4f
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.7+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.41+f71b366f4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.20+78d798af4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.58+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.86+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.15+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.10+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.23+78d798af4f
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.4+b90db5744f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.2.4+5c0133444f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.61+78d798af4f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.1+09fc25014f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.1+389931eb4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.74+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.46+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.2.0+d6f2b0844f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.26+58f8c0124f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.41+78d798af4f
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.39+df3654b34f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.0+a67ffb5d4f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.9+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.5+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.65+78d798af4f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.8+78d798af4f
			fabric-models-v0: Fabric Models (v0) 0.4.7+9386d8a74f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.7+2e5ac5484f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.0.14+080016e44f
			fabric-particles-v1: Fabric Particles (v1) 1.1.7+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.20+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.19+58f8c0124f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.4+78d798af4f
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.4+78d798af4f
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.53+df3654b34f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.42+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.1+e761c6694f
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.56+df3654b34f
			fabric-rendering-v1: Fabric Rendering (v1) 3.2.0+6fd945a04f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.14+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.20+df798a894f
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.17+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.55+78d798af4f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.17+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.11+eb30349a4f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.14+78d798af4f
		fabricloader: Fabric Loader 0.15.9
			mixinextras: MixinExtras 0.3.5
		iris: Iris 1.6.17
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		journeymap: Journeymap 5.9.24
			journeymap-api-fabric: JourneyMap API 1.20.2-1.9-fabric-SNAPSHOT
		litematica: Litematica 0.17.2
		malilib: MaLiLib 0.18.1
		minecraft: Minecraft 1.20.4
		modmenu: Mod Menu 9.1.0-beta.1
		playeranimator: Player Animator 1.0.2-rc1+1.20.4
		removewardeneffect: Remove Warden Darkness 0.0.2-1.20.4
		replaymod: Replay Mod 1.20.4-2.6.15
		seedcrackerx: SeedCrackerX 2.14.6
			cloth-config: Cloth Config v13 13.0.121
				cloth-basic-math: cloth-basic-math 0.6.1
		sodium: Sodium 0.5.8+mc1.20.4
		tlskincape: TLSkinCape 1.32
	Loaded Shaderpack: (off)

**Comment by cenz24** [comment]
Ik this is late but did u ever found a fix for this problem?
